# Intro to data analysis
## Live coding session
### Yngve Mardal Moe

## Part 1: Loading data from Excel

In [1]:
import pandas as pd

In [2]:
weather = pd.read_excel("weather_data.xlsx")

To view a variable in a notebook, simply type the name of the variable in the end line of a cell

In [3]:
weather  # This is specific for Jupyter notebooks

,dato,albedo,balanse,diffus,fd,fluxm,fluxs,global,grmin,ir√∏d,...,nb,par,rf,sd,sdman,synlig,uv,vh,vhmax,vr
0,1988-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1988-01-02 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1988-01-03 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1988-01-04 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1988-01-05 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1988-01-06 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1988-01-07 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1988-01-08 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1988-01-09 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1988-01-10 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,1988-01-11 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,1988-01-12 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,1988-01-13 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,1988-01-14 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,1988-01-15 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,1988-01-16 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,1988-01-17 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,1988-01-18 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,1988-01-19 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,1988-01-20 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,1988-01-21 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,1988-01-22 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,1988-01-23 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,1988-01-24 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,1988-01-25 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,1988-01-26 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,1988-01-27 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,1988-01-28 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,1988-01-29 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,1988-01-30 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11293,2018-12-02 00:10:00,0.172544,-0.561167,0.460905,NaN,3.291177,0.284358,0.421363,-0.038,65.57986,...,12.0,0.853293,99.96528,NaN,NaN,29.562620,4.857520,2.898785,4.087,√ò
11294,2018-12-03 22:10:00,0.108175,0.017563,0.393376,NaN,6.200490,0.535722,0.384140,4.363,44.84836,...,8.6,0.906667,100.00000,NaN,0.0,49.578825,5.572815,1.775410,4.439,√ò
11295,2018-12-04 00:10:00,0.221060,-3.654298,0.729919,NaN,-7.121333,-0.615283,0.811693,-7.964,38.28223,...,4.7,1.853481,72.02778,NaN,0.0,56.351354,5.366416,3.472875,6.210,NV
11296,2018-12-05 00:10:00,0.223798,-4.569000,2.154242,NaN,-14.243610,-1.230648,2.455054,-12.370,54.21980,...,0.0,3.244609,75.22916,NaN,0.0,43.363145,2.417055,1.735375,4.125,S
11297,2018-12-06 00:10:00,0.291290,-1.070306,0.619717,NaN,-10.252400,-0.885807,0.556293,-11.660,67.33762,...,7.4,1.142509,98.10416,NaN,0.0,27.872674,4.789706,NaN,NaN,NaN
11298,2018-12-07 00:10:00,0.784074,-0.066208,0.530192,NaN,-8.185083,-0.707191,0.498974,-1.009,45.40778,...,8.5,1.359652,99.86806,NaN,10.0,47.503921,7.088299,NaN,NaN,NaN
11299,2018-12-08 00:10:00,2.595680,-0.668164,0.611927,NaN,-7.103809,-0.613769,0.291119,-3.369,29.76043,...,4.4,0.854312,99.50000,NaN,NaN,63.582288,6.657282,2.113271,4.013,N
11300,2018-12-09 00:10:00,0.722303,-1.521313,0.822890,NaN,-6.286635,-0.543165,1.090572,-13.660,45.78611,...,0.2,2.067057,97.26389,NaN,NaN,49.398304,4.815586,1.510097,3.812,NV
11301,2018-12-10 00:10:00,0.751300,-2.938722,0.779939,NaN,-5.871264,-0.507277,0.849219,-10.030,46.02184,...,0.0,2.018458,76.17361,NaN,19.0,47.459701,6.518459,2.992194,6.235,NV
11302,2018-12-11 00:10:00,0.707177,-2.817427,0.563883,NaN,-5.402417,-0.466769,1.406764,-14.990,63.20111,...,0.0,2.828161,75.13465,NaN,18.0,32.623007,4.175883,2.616361,4.832,N
11303,2018-12-12 22:10:00,0.552113,-1.607687,0.568240,NaN,-5.413264,-0.467706,1.891487,-17.580,41.33722,...,0.0,3.027292,98.19514,NaN,17.0,55.550530,3.112250,NaN,NaN,NaN
11304,2018-12-13 22:10:00,0.788596,-0.294080,0.486171,NaN,-5.202694,-0.449513,0.468615,-6.274,36.15185,...,0.2,1.268141,95.26389,NaN,17.0,56.518423,7.329727,2.540396,4.167,N
11305,2018-12-14 00:10:00,0.757965,-0.361724,0.496776,NaN,-4.907326,-0.423993,0.487178,-9.380,37.40683,...,0.0,1.302357,91.85764,NaN,17.0,55.553818,7.039352,1.822951,3.288,N
11306,2018-12-15 00:10:00,0.790336,-0.451263,0.465728,NaN,-4.855365,-0.419503,0.449248,-8.450,36.12814,...,1.0,1.207986,93.70764,NaN,NaN,56.633357,7.238503,1.509257,2.697,N
11307,2018-12-16 00:10:00,0.748424,-0.738231,0.456784,NaN,-4.251715,-0.367348,0.455249,-2.827,37.26573,...,1.5,1.168568,93.99514,NaN,NaN,55.882061,6.852209,2.667333,4.059,√ò
11308,2018-12-17 22:10:00,0.725240,-0.873497,1.135281,NaN,-3.555465,-0.307192,1.270855,-11.490,51.78816,...,1.1,2.706872,99.37917,NaN,20.0,44.146908,4.064932,1.076243,2.788,N
11309,2018-12-18 00:10:00,0.837900,-0.271274,0.598734,NaN,-3.485184,-0.301120,0.559267,-4.897,44.68304,...,0.6,1.501040,99.65278,NaN,19.0,48.695974,6.620986,0.909535,2.079,N
11310,2018-12-19 00:10:00,0.711765,-0.527623,0.233392,NaN,-3.408437,-0.294489,0.225485,-3.135,47.89760,...,3.3,0.626588,99.52847,NaN,19.0,44.108957,7.993443,1.842535,3.027,√ò
11311,2018-12-20 00:10:00,0.816733,-1.097929,0.187892,NaN,-3.567246,-0.308210,0.174457,-0.207,28.23969,...,0.7,0.509647,96.31389,NaN,16.0,63.549099,8.211211,2.526660,3.815,√ò
11312,2018-12-21 22:10:00,0.701868,-0.515824,0.375762,NaN,-3.557246,-0.307346,0.364153,-2.831,37.87324,...,0.5,0.999070,87.70069,NaN,14.0,55.053363,7.073397,2.953264,3.941,N√ò
11313,2018-12-22 00:10:00,0.752722,-0.722865,0.338192,NaN,-3.582708,-0.309546,0.323534,-5.060,34.21312,...,0.0,0.911864,83.18840,NaN,NaN,58.624908,7.161972,1.692528,3.571,N
11314,2018-12-23 00:10:00,0.661407,-1.322467,0.896327,NaN,-4.295028,-0.371090,0.915799,-17.800,48.73107,...,0.0,2.105036,92.95972,NaN,NaN,46.528415,4.740515,0.725639,1.695,NV
11315,2018-12-24 00:10:00,0.684347,-0.834153,0.873651,NaN,-6.058024,-0.523413,0.984602,-18.520,54.26330,...,0.0,1.962061,98.82570,NaN,NaN,41.302402,4.434298,NaN,NaN,NaN
11316,2018-12-25 00:10:00,0.669676,-2.126344,0.477907,NaN,-5.256490,-0.454161,0.606802,-10.280,32.20305,...,0.0,1.571380,91.06236,NaN,14.0,62.261698,5.535252,1.300396,4.915,√ò
11317,2018-12-26 00:10:00,0.684592,-0.875690,0.503858,NaN,-4.962451,-0.428756,0.461216,-11.080,60.84723,...,0.5,0.966637,96.40625,NaN,NaN,33.970474,5.182296,0.841278,1.848,√ò
11318,2018-12-27 00:10:00,0.648644,-1.037384,0.520922,NaN,-3.859840,-0.333490,0.542782,-7.409,38.36279,...,1.8,1.339207,99.99931,NaN,13.0,55.943656,5.693554,0.776569,2.105,N√ò
11319,2018-12-28 00:10:00,0.458021,-1.520098,0.991158,NaN,-4.974732,-0.429817,1.719382,-12.720,57.93696,...,0.0,2.614267,98.92361,NaN,NaN,39.267257,2.795783,NaN,NaN,NaN
11320,2018-12-29 00:10:00,0.879624,-0.617260,0.577520,NaN,-5.268014,-0.455156,0.613190,-11.050,46.90142,...,0.1,1.723672,99.43750,NaN,NaN,47.482347,5.616233,NaN,NaN,NaN
11321,2018-12-30 00:10:00,0.476756,-0.901978,0.896532,NaN,-5.038892,-0.435360,1.807672,-11.050,58.87096,...,0.3,3.238451,99.72916,NaN,NaN,38.155978,2.973062,NaN,NaN,NaN
11322,2018-12-31 22:10:00,0.605755,-1.960404,0.422131,NaN,-4.760121,-0.411274,0.454753,-2.048,24.69542,...,1.9,1.215902,99.46528,NaN,13.0,67.885875,7.418705,4.387930,10.200,S

In [4]:
print(weather)  # Here we see the data frame as a string, as opposed to the HTML above

                     dato    albedo   balanse    diffus  fd      fluxm  \
0     1988-01-01 00:00:00       NaN       NaN       NaN NaN        NaN
1     1988-01-02 00:00:00       NaN       NaN       NaN NaN        NaN
2     1988-01-03 00:00:00       NaN       NaN       NaN NaN        NaN
3     1988-01-04 00:00:00       NaN       NaN       NaN NaN        NaN
4     1988-01-05 00:00:00       NaN       NaN       NaN NaN        NaN
5     1988-01-06 00:00:00       NaN       NaN       NaN NaN        NaN
6     1988-01-07 00:00:00       NaN       NaN       NaN NaN        NaN
7     1988-01-08 00:00:00       NaN       NaN       NaN NaN        NaN
8     1988-01-09 00:00:00       NaN       NaN       NaN NaN        NaN
9     1988-01-10 00:00:00       NaN       NaN       NaN NaN        NaN
10    1988-01-11 00:00:00       NaN       NaN       NaN NaN        NaN
11    1988-01-12 00:00:00       NaN       NaN       NaN NaN        NaN
12    1988-01-13 00:00:00       NaN       NaN       NaN NaN        NaN
13    1988-01-14 00:00:00       NaN       NaN       NaN NaN        NaN
14    1988-01-15 00:00:00       NaN       NaN       NaN NaN        NaN
15    1988-01-16 00:00:00       NaN       NaN       NaN NaN        NaN
16    1988-01-17 00:00:00       NaN       NaN       NaN NaN        NaN
17    1988-01-18 00:00:00       NaN       NaN       NaN NaN        NaN
18    1988-01-19 00:00:00       NaN       NaN       NaN NaN        NaN
19    1988-01-20 00:00:00       NaN       NaN       NaN NaN        NaN
20    1988-01-21 00:00:00       NaN       NaN       NaN NaN        NaN
21    1988-01-22 00:00:00       NaN       NaN       NaN NaN        NaN
22    1988-01-23 00:00:00       NaN       NaN       NaN NaN        NaN
23    1988-01-24 00:00:00       NaN       NaN       NaN NaN        NaN
24    1988-01-25 00:00:00       NaN       NaN       NaN NaN        NaN
25    1988-01-26 00:00:00       NaN       NaN       NaN NaN        NaN
26    1988-01-27 00:00:00       NaN       NaN       NaN NaN        NaN
27    1988-01-28 00:00:00       NaN       NaN       NaN NaN        NaN
28    1988-01-29 00:00:00       NaN       NaN       NaN NaN        NaN
29    1988-01-30 00:00:00       NaN       NaN       NaN NaN        NaN
...                   ...       ...       ...       ...  ..        ...
11293 2018-12-02 00:10:00  0.172544 -0.561167  0.460905 NaN   3.291177
11294 2018-12-03 22:10:00  0.108175  0.017563  0.393376 NaN   6.200490
11295 2018-12-04 00:10:00  0.221060 -3.654298  0.729919 NaN  -7.121333
11296 2018-12-05 00:10:00  0.223798 -4.569000  2.154242 NaN -14.243610
11297 2018-12-06 00:10:00  0.291290 -1.070306  0.619717 NaN -10.252400
11298 2018-12-07 00:10:00  0.784074 -0.066208  0.530192 NaN  -8.185083
11299 2018-12-08 00:10:00  2.595680 -0.668164  0.611927 NaN  -7.103809
11300 2018-12-09 00:10:00  0.722303 -1.521313  0.822890 NaN  -6.286635
11301 2018-12-10 00:10:00  0.751300 -2.938722  0.779939 NaN  -5.871264
11302 2018-12-11 00:10:00  0.707177 -2.817427  0.563883 NaN  -5.402417
11303 2018-12-12 22:10:00  0.552113 -1.607687  0.568240 NaN  -5.413264
11304 2018-12-13 22:10:00  0.788596 -0.294080  0.486171 NaN  -5.202694
11305 2018-12-14 00:10:00  0.757965 -0.361724  0.496776 NaN  -4.907326
11306 2018-12-15 00:10:00  0.790336 -0.451263  0.465728 NaN  -4.855365
11307 2018-12-16 00:10:00  0.748424 -0.738231  0.456784 NaN  -4.251715
11308 2018-12-17 22:10:00  0.725240 -0.873497  1.135281 NaN  -3.555465
11309 2018-12-18 00:10:00  0.837900 -0.271274  0.598734 NaN  -3.485184
11310 2018-12-19 00:10:00  0.711765 -0.527623  0.233392 NaN  -3.408437
11311 2018-12-20 00:10:00  0.816733 -1.097929  0.187892 NaN  -3.567246
11312 2018-12-21 22:10:00  0.701868 -0.515824  0.375762 NaN  -3.557246
11313 2018-12-22 00:10:00  0.752722 -0.722865  0.338192 NaN  -3.582708
11314 2018-12-23 00:10:00  0.661407 -1.322467  0.896327 NaN  -4.295028
11315 2018-12-24 00:10:00  0.684347 -0.834153  0.873651 NaN  -6.058024
11316 2018-12-25 00:10:00  0.669676 -2.126344  0.477907 NaN  -5.256490
11317 2018-12-26 00:10:00  0.684592 -0.875690  0.503858 NaN  -4.962451
11318 2018-12-27 00:10:00  0.648644 -1.037384  0.520922 NaN  -3.859840
11319 2018-12-28 00:10:00  0.458021 -1.520098  0.991158 NaN  -4.974732
11320 2018-12-29 00:10:00  0.879624 -0.617260  0.577520 NaN  -5.268014
11321 2018-12-30 00:10:00  0.476756 -0.901978  0.896532 NaN  -5.038892
11322 2018-12-31 22:10:00  0.605755 -1.960404  0.422131 NaN  -4.760121

          fluxs    global   grmin      ir√∏d  ...    nb       par         rf  \
0           NaN       NaN     NaN       NaN  ...   NaN       NaN        NaN
1           NaN       NaN     NaN       NaN  ...  20.2       NaN        NaN
2           NaN       NaN     NaN       NaN  ...   NaN       NaN        NaN
3           NaN       NaN     NaN       NaN  ...   NaN       NaN        NaN
4           NaN       NaN     NaN       NaN  ...   0.0       NaN        NaN
5           NaN       NaN     NaN       NaN  ...   3.5       NaN        NaN
6           NaN       NaN     NaN       NaN  ...   0.6       NaN        NaN
7           NaN       NaN     NaN       NaN  ...   0.1       NaN        NaN
8           NaN       NaN     NaN       NaN  ...   NaN       NaN        NaN
9           NaN       NaN     NaN       NaN  ...   5.5       NaN        NaN
10          NaN       NaN     NaN       NaN  ...   NaN       NaN        NaN
11          NaN       NaN     NaN       NaN  ...   2.7       NaN        NaN
12          NaN       NaN     NaN       NaN  ...   2.0       NaN        NaN
13          NaN       NaN     NaN       NaN  ...   1.5       NaN        NaN
14          NaN       NaN     NaN       NaN  ...   4.0       NaN        NaN
15          NaN       NaN     NaN       NaN  ...   NaN       NaN        NaN
16          NaN       NaN     NaN       NaN  ...   1.5       NaN        NaN
17          NaN       NaN     NaN       NaN  ...   NaN       NaN        NaN
18          NaN       NaN     NaN       NaN  ...   7.4       NaN        NaN
19          NaN       NaN     NaN       NaN  ...   5.4       NaN        NaN
20          NaN       NaN     NaN       NaN  ...  10.0       NaN        NaN
21          NaN       NaN     NaN       NaN  ...   9.7       NaN        NaN
22          NaN       NaN     NaN       NaN  ...   NaN       NaN        NaN
23          NaN       NaN     NaN       NaN  ...   8.8       NaN        NaN
24          NaN       NaN     NaN       NaN  ...   NaN       NaN        NaN
25          NaN       NaN     NaN       NaN  ...   5.0       NaN        NaN
26          NaN       NaN     NaN       NaN  ...  12.3       NaN        NaN
27          NaN       NaN     NaN       NaN  ...  13.0       NaN        NaN
28          NaN       NaN     NaN       NaN  ...   2.7       NaN        NaN
29          NaN       NaN     NaN       NaN  ...  16.2       NaN        NaN
...         ...       ...     ...       ...  ...   ...       ...        ...
11293  0.284358  0.421363  -0.038  65.57986  ...  12.0  0.853293   99.96528
11294  0.535722  0.384140   4.363  44.84836  ...   8.6  0.906667  100.00000
11295 -0.615283  0.811693  -7.964  38.28223  ...   4.7  1.853481   72.02778
11296 -1.230648  2.455054 -12.370  54.21980  ...   0.0  3.244609   75.22916
11297 -0.885807  0.556293 -11.660  67.33762  ...   7.4  1.142509   98.10416
11298 -0.707191  0.498974  -1.009  45.40778  ...   8.5  1.359652   99.86806
11299 -0.613769  0.291119  -3.369  29.76043  ...   4.4  0.854312   99.50000
11300 -0.543165  1.090572 -13.660  45.78611  ...   0.2  2.067057   97.26389
11301 -0.507277  0.849219 -10.030  46.02184  ...   0.0  2.018458   76.17361
11302 -0.466769  1.406764 -14.990  63.20111  ...   0.0  2.828161   75.13465
11303 -0.467706  1.891487 -17.580  41.33722  ...   0.0  3.027292   98.19514
11304 -0.449513  0.468615  -6.274  36.15185  ...   0.2  1.268141   95.26389
11305 -0.423993  0.487178  -9.380  37.40683  ...   0.0  1.302357   91.85764
11306 -0.419503  0.449248  -8.450  36.12814  ...   1.0  1.207986   93.70764
11307 -0.367348  0.455249  -2.827  37.26573  ...   1.5  1.168568   93.99514
11308 -0.307192  1.270855 -11.490  51.78816  ...   1.1  2.706872   99.37917
11309 -0.301120  0.559267  -4.897  44.68304  ...   0.6  1.501040   99.65278
11310 -0.294489  0.225485  -3.135  47.89760  ...   3.3  0.626588   99.52847
11311 -0.308210  0.174457  -0.207  28.23969  ...   0.7  0.509647   96.31389
11312 -0.307346  0.364153  -2.831  37.87324  ...   0.5  0.999070   87.70069
11313 -0.309546  0.323534  -5.060  34.21312  ...   0.0  0.911864   83.18840
11314 -0.371090  0.915799 -17.800  48.73107  ...   0.0  2.105036   92.95972
11315 -0.523413  0.984602 -18.520  54.26330  ...   0.0  1.962061   98.82570
11316 -0.454161  0.606802 -10.280  32.20305  ...   0.0  1.571380   91.06236
11317 -0.428756  0.461216 -11.080  60.84723  ...   0.5  0.966637   96.40625
11318 -0.333490  0.542782  -7.409  38.36279  ...   1.8  1.339207   99.99931
11319 -0.429817  1.719382 -12.720  57.93696  ...   0.0  2.614267   98.92361
11320 -0.455156  0.613190 -11.050  46.90142  ...   0.1  1.723672   99.43750
11321 -0.435360  1.807672 -11.050  58.87096  ...   0.3  3.238451   99.72916
11322 -0.411274  0.454753  -2.048  24.69542  ...   1.9  1.215902   99.46528

       sd  sdman     synlig        uv        vh   vhmax   vr
0     NaN    NaN        NaN       NaN       NaN     NaN  NaN
1     NaN    NaN        NaN       NaN       NaN     NaN  NaN
2     NaN    NaN        NaN       NaN       NaN     NaN  NaN
3     NaN    NaN        NaN       NaN       NaN     NaN  NaN
4     NaN    NaN        NaN       NaN       NaN     NaN  NaN
5     NaN    NaN        NaN       NaN       NaN     NaN  NaN
6     NaN    NaN        NaN       NaN       NaN     NaN  NaN
7     NaN    NaN        NaN       NaN       NaN     NaN  NaN
8     NaN    NaN        NaN       NaN       NaN     NaN  NaN
9     NaN    NaN        NaN       NaN       NaN     NaN  NaN
10    NaN    NaN        NaN       NaN       NaN     NaN  NaN
11    NaN    NaN        NaN       NaN       NaN     NaN  NaN
12    NaN    NaN        NaN       NaN       NaN     NaN  NaN
13    NaN    NaN        NaN       NaN       NaN     NaN  NaN
14    NaN    NaN        NaN       NaN       NaN     NaN  NaN
15    NaN    NaN        NaN       NaN       NaN     NaN  NaN
16    NaN    NaN        NaN       NaN       NaN     NaN  NaN
17    NaN    NaN        NaN       NaN       NaN     NaN  NaN
18    NaN    NaN        NaN       NaN       NaN     NaN  NaN
19    NaN    NaN        NaN       NaN       NaN     NaN  NaN
20    NaN    NaN        NaN       NaN       NaN     NaN  NaN
21    NaN    NaN        NaN       NaN       NaN     NaN  NaN
22    NaN    NaN        NaN       NaN       NaN     NaN  NaN
23    NaN    NaN        NaN       NaN       NaN     NaN  NaN
24    NaN    NaN        NaN       NaN       NaN     NaN  NaN
25    NaN    NaN        NaN       NaN       NaN     NaN  NaN
26    NaN    NaN        NaN       NaN       NaN     NaN  NaN
27    NaN    NaN        NaN       NaN       NaN     NaN  NaN
28    NaN    NaN        NaN       NaN       NaN     NaN  NaN
29    NaN    NaN        NaN       NaN       NaN     NaN  NaN
...    ..    ...        ...       ...       ...     ...  ...
11293 NaN    NaN  29.562620  4.857520  2.898785   4.087    √ò
11294 NaN    0.0  49.578825  5.572815  1.775410   4.439    √ò
11295 NaN    0.0  56.351354  5.366416  3.472875   6.210   NV
11296 NaN    0.0  43.363145  2.417055  1.735375   4.125    S
11297 NaN    0.0  27.872674  4.789706       NaN     NaN  NaN
11298 NaN   10.0  47.503921  7.088299       NaN     NaN  NaN
11299 NaN    NaN  63.582288  6.657282  2.113271   4.013    N
11300 NaN    NaN  49.398304  4.815586  1.510097   3.812   NV
11301 NaN   19.0  47.459701  6.518459  2.992194   6.235   NV
11302 NaN   18.0  32.623007  4.175883  2.616361   4.832    N
11303 NaN   17.0  55.550530  3.112250       NaN     NaN  NaN
11304 NaN   17.0  56.518423  7.329727  2.540396   4.167    N
11305 NaN   17.0  55.553818  7.039352  1.822951   3.288    N
11306 NaN    NaN  56.633357  7.238503  1.509257   2.697    N
11307 NaN    NaN  55.882061  6.852209  2.667333   4.059    √ò
11308 NaN   20.0  44.146908  4.064932  1.076243   2.788    N
11309 NaN   19.0  48.695974  6.620986  0.909535   2.079    N
11310 NaN   19.0  44.108957  7.993443  1.842535   3.027    √ò
11311 NaN   16.0  63.549099  8.211211  2.526660   3.815    √ò
11312 NaN   14.0  55.053363  7.073397  2.953264   3.941   N√ò
11313 NaN    NaN  58.624908  7.161972  1.692528   3.571    N
11314 NaN    NaN  46.528415  4.740515  0.725639   1.695   NV
11315 NaN    NaN  41.302402  4.434298       NaN     NaN  NaN
11316 NaN   14.0  62.261698  5.535252  1.300396   4.915    √ò
11317 NaN    NaN  33.970474  5.182296  0.841278   1.848    √ò
11318 NaN   13.0  55.943656  5.693554  0.776569   2.105   N√ò
11319 NaN    NaN  39.267257  2.795783       NaN     NaN  NaN
11320 NaN    NaN  47.482347  5.616233       NaN     NaN  NaN
11321 NaN    NaN  38.155978  2.973062       NaN     NaN  NaN
11322 NaN   13.0  67.885875  7.418705  4.387930  10.200    S

[11323 rows x 30 columns]

In [5]:
weather.columns

Index(['dato', 'albedo', 'balanse', 'diffus', 'fd', 'fluxm', 'fluxs', 'global',
       'grmin', 'ir√∏d', 'jt010', 'jt100', 'jt002', 'jt020', 'jt005', 'jt050',
       'lp', 'lt', 'ltmax', 'ltmin', 'nb', 'par', 'rf', 'sd', 'sdman',
       'synlig', 'uv', 'vh', 'vhmax', 'vr'],
      dtype='object')

To see all the columns, we change the pandas settings

In [6]:
pd.set_option('max_columns', 100)

In [7]:
weather

,dato,albedo,balanse,diffus,fd,fluxm,fluxs,global,grmin,ir√∏d,jt010,jt100,jt002,jt020,jt005,jt050,lp,lt,ltmax,ltmin,nb,par,rf,sd,sdman,synlig,uv,vh,vhmax,vr
0,1988-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.100000,5.900,3.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1988-01-02 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.700000,5.300,1.500,20.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1988-01-03 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.300000,2.100,0.200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1988-01-04 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.100000,0.400,-0.100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1988-01-05 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.100000,0.600,-0.500,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1988-01-06 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.500000,0.200,-1.400,3.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1988-01-07 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.300000,0.200,-5.600,0.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1988-01-08 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-6.200000,-4.500,-10.700,0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1988-01-09 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.500000,2.900,-4.900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1988-01-10 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.200000,5.800,1.900,5.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,1988-01-11 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.700000,3.600,0.900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,1988-01-12 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.200000,4.300,-2.800,2.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,1988-01-13 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.600000,4.600,3.000,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,1988-01-14 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.200000,3.900,2.300,1.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,1988-01-15 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.100000,4.300,1.800,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,1988-01-16 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.700000,1.800,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,1988-01-17 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.400000,1.300,0.000,1.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,1988-01-18 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.300000,2.400,0.100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,1988-01-19 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.400000,3.000,-0.800,7.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,1988-01-20 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.700000,2.300,1.000,5.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,1988-01-21 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.900000,3.500,0.300,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,1988-01-22 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,3.500,0.400,9.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,1988-01-23 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.400,-1.100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,1988-01-24 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.100000,-0.400,-1.700,8.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,1988-01-25 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.400,-0.700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,1988-01-26 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.600000,0.000,-0.800,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,1988-01-27 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.300000,0.300,-0.500,12.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,1988-01-28 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.300000,0.700,0.000,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,1988-01-29 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.900000,0.100,-2.800,2.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,1988-01-30 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-3.300000,-2.800,-3.900,16.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11293,2018-12-02 00:10:00,0.172544,-0.561167,0.460905,NaN,3.291177,0.284358,0.421363,-0.038,65.57986,1.039569,5.445042,0.737660,1.422431,0.832167,2.793424,984.5229,4.220986,4.773,2.480,12.0,0.853293,99.96528,NaN,NaN,29.562620,4.857520,2.898785,4.087,√ò
11294,2018-12-03 22:10:00,0.108175,0.017563,0.393376,NaN,6.200490,0.535722,0.384140,4.363,44.84836,2.410222,5.309354,2.739563,2.247729,2.601854,2.943118,973.7991,5.776055,7.378,4.749,8.6,0.906667,100.00000,NaN,0.0,49.578825,5.572815,1.775410,4.439,√ò
11295,2018-12-04 00:10:00,0.221060,-3.654298,0.729919,NaN,-7.121333,-0.615283,0.811693,-7.964,38.28223,3.107917,5.253472,2.774570,2.969076,2.952181,3.321132,987.1948,3.013479,4.880,-1.672,4.7,1.853481,72.02778,NaN,0.0,56.351354,5.366416,3.472875,6.210,NV
11296,2018-12-05 00:10:00,0.223798,-4.569000,2.154242,NaN,-14.243610,-1.230648,2.455054,-12.370,54.21980,1.867806,5.264812,0.946854,2.501972,1.445979,3.536944,1004.8450,-2.114458,0.578,-5.752,0.0,3.244609,75.22916,NaN,0.0,43.363145,2.417055,1.735375,4.125,S
11297,2018-12-06 00:10:00,0.291290,-1.070306,0.619717,NaN,-10.252400,-0.885807,0.556293,-11.660,67.33762,1.261222,5.252576,0.446042,1.917250,0.868993,3.374979,998.6358,-2.138097,0.326,-5.997,7.4,1.142509,98.10416,NaN,0.0,27.872674,4.789706,NaN,NaN,NaN
11298,2018-12-07 00:10:00,0.784074,-0.066208,0.530192,NaN,-8.185083,-0.707191,0.498974,-1.009,45.40778,0.994896,5.191764,0.393667,1.603500,0.723257,3.100965,983.6542,-0.204861,0.300,-0.596,8.5,1.359652,99.86806,NaN,10.0,47.503921,7.088299,NaN,NaN,NaN
11299,2018-12-08 00:10:00,2.595680,-0.668164,0.611927,NaN,-7.103809,-0.613769,0.291119,-3.369,29.76043,0.851104,5.081000,0.394417,1.494625,0.703340,2.917847,968.7765,-0.546965,0.081,-1.948,4.4,0.854312,99.50000,NaN,NaN,63.582288,6.657282,2.113271,4.013,N
11300,2018-12-09 00:10:00,0.722303,-1.521313,0.822890,NaN,-6.286635,-0.543165,1.090572,-13.660,45.78611,0.918299,4.978882,0.438750,1.471201,0.734437,2.795486,971.3123,-2.675701,-0.425,-5.615,0.2,2.067057,97.26389,NaN,NaN,49.398304,4.815586,1.510097,3.812,NV
11301,2018-12-10 00:10:00,0.751300,-2.938722,0.779939,NaN,-5.871264,-0.507277,0.849219,-10.030,46.02184,1.465993,4.872576,0.506958,1.459549,0.804660,2.696285,988.6810,1.157403,3.766,-4.173,0.0,2.018458,76.17361,NaN,19.0,47.459701,6.518459,2.992194,6.235,NV
11302,2018-12-11 00:10:00,0.707177,-2.817427,0.563883,NaN,-5.402417,-0.466769,1.406764,-14.990,63.20111,1.901778,4.759597,0.588812,1.461493,0.863778,2.646722,1009.6670,0.758868,3.735,-6.743,0.0,2.828161,75.13465,NaN,18.0,32.623007,4.175883,2.616361,4.832,N
11303,2018-12-12 22:10:00,0.552113,-1.607687,0.568240,NaN,-5.413264,-0.467706,1.891487,-17.580,41.33722,1.466694,4.693028,0.650132,1.483299,0.917424,2.607875,1020.4720,-6.032153,-2.048,-9.460,0.0,3.027292,98.19514,NaN,17.0,55.550530,3.112250,NaN,NaN,NaN
11304,2018-12-13 22:10:00,0.788596,-0.294080,0.486171,NaN,-5.202694,-0.449513,0.468615,-6.274,36.15185,1.682854,4.605542,0.644826,1.459250,0.901535,2.530319,1022.9900,-5.462028,-4.929,-6.217,0.2,1.268141,95.26389,NaN,17.0,56.518423,7.329727,2.540396,4.167,N
11305,2018-12-14 00:10:00,0.757965,-0.361724,0.496776,NaN,-4.907326,-0.423993,0.487178,-9.380,37.40683,1.807743,4.520215,0.668917,1.401708,0.912125,2.456951,1023.6290,-7.549840,-6.223,-9.140,0.0,1.302357,91.85764,NaN,17.0,55.553818,7.039352,1.822951,3.288,N
11306,2018-12-15 00:10:00,0.790336,-0.451263,0.465728,NaN,-4.855365,-0.419503,0.449248,-8.450,36.12814,0.982826,4.422111,0.677195,1.370590,0.907062,2.394778,1021.1680,-5.627292,-1.944,-8.540,1.0,1.207986,93.70764,NaN,NaN,56.633357,7.238503,1.509257,2.697,N
11307,2018-12-16 00:10:00,0.748424,-0.738231,0.456784,NaN,-4.251715,-0.367348,0.455249,-2.827,37.26573,0.935063,4.357625,0.675847,1.355417,0.904215,2.346479,1009.5020,-0.505632,0.187,-2.040,1.5,1.168568,93.99514,NaN,NaN,55.882061,6.852209,2.667333,4.059,√ò
11308,2018-12-17 22:10:00,0.725240,-0.873497,1.135281,NaN,-3.555465,-0.307192,1.270855,-11.490,51.78816,1.007007,4.282896,0.798264,1.367646,0.963757,2.335264,1007.1630,-3.102604,-1.375,-5.237,1.1,2.706872,99.37917,NaN,20.0,44.146908,4.064932,1.076243,2.788,N
11309,2018-12-18 00:10:00,0.837900,-0.271274,0.598734,NaN,-3.485184,-0.301120,0.559267,-4.897,44.68304,1.072222,4.216403,0.854632,1.397778,1.036910,2.322208,1011.2080,-4.164535,-2.751,-5.016,0.6,1.501040,99.65278,NaN,19.0,48.695974,6.620986,0.909535,2.079,N
11310,2018-12-19 00:10:00,0.711765,-0.527623,0.233392,NaN,-3.408437,-0.294489,0.225485,-3.135,47.89760,1.196875,4.164993,0.916305,1.438201,1.072410,2.313292,1006.1320,-0.015722,1.486,-2.931,3.3,0.626588,99.52847,NaN,19.0,44.108957,7.993443,1.842535,3.027,√ò
11311,2018-12-20 00:10:00,0.816733,-1.097929,0.187892,NaN,-3.567246,-0.308210,0.174457,-0.207,28.23969,1.282688,4.107924,0.955861,1.462951,1.109847,2.316410,1004.1960,0.983722,1.450,0.062,0.7,0.509647,96.31389,NaN,16.0,63.549099,8.211211,2.526660,3.815,√ò
11312,2018-12-21 22:10:00,0.701868,-0.515824,0.375762,NaN,-3.557246,-0.307346,0.364153,-2.831,37.87324,1.750306,4.079236,0.992243,1.478194,1.158118,2.314333,1000.1270,-1.064292,0.037,-2.503,0.5,0.999070,87.70069,NaN,14.0,55.053363,7.073397,2.953264,3.941,N√ò
11313,2018-12-22 00:10:00,0.752722,-0.722865,0.338192,NaN,-3.582708,-0.309546,0.323534,-5.060,34.21312,2.527778,4.049812,1.008451,1.497750,1.178979,2.323424,999.5062,-3.300639,-2.533,-4.271,0.0,0.911864,83.18840,NaN,NaN,58.624908,7.161972,1.692528,3.571,N
11314,2018-12-23 00:10:00,0.661407,-1.322467,0.896327,NaN,-4.295028,-0.371090,0.915799,-17.800,48.73107,1.758174,4.039521,0.904299,1.482236,1.099333,2.309347,1003.3720,-5.367910,-3.273,-10.830,0.0,2.105036,92.95972,NaN,NaN,46.528415,4.740515,0.725639,1.695,NV
11315,2018-12-24 00:10:00,0.684347,-0.834153,0.873651,NaN,-6.058024,-0.523413,0.984602,-18.520,54.26330,1.096764,3.988354,0.650195,1.379646,0.887687,2.250625,1007.2970,-7.872431,-2.061,-12.770,0.0,1.962061,98.82570,NaN,NaN,41.302402,4.434298,NaN,NaN,NaN
11316,2018-12-25 00:10:00,0.669676,-2.126344,0.477907,NaN,-5.256490,-0.454161,0.606802,-10.280,32.20305,0.885320,3.954708,0.493354,1.217285,0.752347,2.191604,1002.8690,-1.082090,5.844,-5.023,0.0,1.571380,91.06236,NaN,14.0,62.261698,5.535252,1.300396,4.915,√ò
11317,2018-12-26 00:10:00,0.684592,-0.875690,0.503858,NaN,-4.962451,-0.428756,0.461216,-11.080,60.84723,0.722833,3.893701,0.442549,1.146104,0.672882,2.096153,1004.6770,-1.380521,0.976,-5.676,0.5,0.966637,96.40625,NaN,NaN,33.970474,5.182296,0.841278,1.848,√ò
11318,2018-12-27 00:10:00,0.648644,-1.037384,0.520922,NaN,-3.859840,-0.333490,0.542782,-7.409,38.36279,0.694146,3.838215,0.449583,1.094819,0.664396,2.068958,1000.7770,-1.244958,0.695,-4.085,1.8,1.339207,99.99931,NaN,13.0,55.943656,5.693554,0.776569,2.105,N√ò
11319,2018-12-28 00:10:00,0.458021,-1.520098,0.991158,NaN,-4.974732,-0.429817,1.719382,-12.720,57.93696,0.775146,3.810514,0.444639,1.082417,0.668576,2.049465,1005.8380,-6.232451,-4.125,-8.200,0.0,2.614267,98.92361,NaN,NaN,39.267257,2.795783,NaN,NaN,NaN
11320,2018-12-29 00:10:00,0.879624,-0.617260,0.577520,NaN,-5.268014,-0.455156,0.613190,-11.050,46.90142,0.660903,3.759500,0.332375,1.023354,0.542597,1.984889,1003.8350,-4.474945,-1.800,-7.296,0.1,1.723672,99.43750,NaN,NaN,47.482347,5.616233,NaN,NaN,NaN
11321,2018-12-30 00:10:00,0.476756,-0.901978,0.896532,NaN,-5.038892,-0.435360,1.807672,-11.050,58.87096,0.611986,3.728389,0.261771,0.933201,0.470632,1.911840,1009.3070,-3.461583,-1.738,-5.724,0.3,3.238451,99.72916,NaN,NaN,38.155978,2.973062,NaN,NaN,NaN
11322,2018-12-31 22:10:00,0.605755,-1.960404,0.422131,NaN,-4.760121,-0.411274,0.454753,-2.048,24.69542,0.509465,3.673660,0.231160,0.871861,0.429556,1.876417,1002.8510,1.882986,4.524,-1.915,1.9,1.215902,99.46528,NaN,13.0,67.885875,7.418705,4.387930,10.200,S

In [8]:
weather = weather.set_index("dato")

In [9]:
weather

,albedo,balanse,diffus,fd,fluxm,fluxs,global,grmin,ir√∏d,jt010,jt100,jt002,jt020,jt005,jt050,lp,lt,ltmax,ltmin,nb,par,rf,sd,sdman,synlig,uv,vh,vhmax,vr
dato,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1988-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.100000,5.900,3.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988-01-02 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.700000,5.300,1.500,20.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988-01-03 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.300000,2.100,0.200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988-01-04 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.100000,0.400,-0.100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988-01-05 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.100000,0.600,-0.500,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988-01-06 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.500000,0.200,-1.400,3.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988-01-07 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.300000,0.200,-5.600,0.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988-01-08 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-6.200000,-4.500,-10.700,0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988-01-09 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.500000,2.900,-4.900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988-01-10 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.200000,5.800,1.900,5.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988-01-11 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.700000,3.600,0.900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988-01-12 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.200000,4.300,-2.800,2.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988-01-13 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.600000,4.600,3.000,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988-01-14 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.200000,3.900,2.300,1.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988-01-15 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.100000,4.300,1.800,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988-01-16 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.700000,1.800,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988-01-17 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.400000,1.300,0.000,1.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988-01-18 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.300000,2.400,0.100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988-01-19 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.400000,3.000,-0.800,7.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988-01-20 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.700000,2.300,1.000,5.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988-01-21 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.900000,3.500,0.300,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988-01-22 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,3.500,0.400,9.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988-01-23 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.400,-1.100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988-01-24 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.100000,-0.400,-1.700,8.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988-01-25 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.400,-0.700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988-01-26 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.600000,0.000,-0.800,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988-01-27 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.300000,0.300,-0.500,12.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988-01-28 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.300000,0.700,0.000,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988-01-29 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.900000,0.100,-2.800,2.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988-01-30 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-3.300000,-2.800,-3.900,16.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-12-02 00:10:00,0.172544,-0.561167,0.460905,NaN,3.291177,0.284358,0.421363,-0.038,65.57986,1.039569,5.445042,0.737660,1.422431,0.832167,2.793424,984.5229,4.220986,4.773,2.480,12.0,0.853293,99.96528,NaN,NaN,29.562620,4.857520,2.898785,4.087,√ò
2018-12-03 22:10:00,0.108175,0.017563,0.393376,NaN,6.200490,0.535722,0.384140,4.363,44.84836,2.410222,5.309354,2.739563,2.247729,2.601854,2.943118,973.7991,5.776055,7.378,4.749,8.6,0.906667,100.00000,NaN,0.0,49.578825,5.572815,1.775410,4.439,√ò
2018-12-04 00:10:00,0.221060,-3.654298,0.729919,NaN,-7.121333,-0.615283,0.811693,-7.964,38.28223,3.107917,5.253472,2.774570,2.969076,2.952181,3.321132,987.1948,3.013479,4.880,-1.672,4.7,1.853481,72.02778,NaN,0.0,56.351354,5.366416,3.472875,6.210,NV
2018-12-05 00:10:00,0.223798,-4.569000,2.154242,NaN,-14.243610,-1.230648,2.455054,-12.370,54.21980,1.867806,5.264812,0.946854,2.501972,1.445979,3.536944,1004.8450,-2.114458,0.578,-5.752,0.0,3.244609,75.22916,NaN,0.0,43.363145,2.417055,1.735375,4.125,S
2018-12-06 00:10:00,0.291290,-1.070306,0.619717,NaN,-10.252400,-0.885807,0.556293,-11.660,67.33762,1.261222,5.252576,0.446042,1.917250,0.868993,3.374979,998.6358,-2.138097,0.326,-5.997,7.4,1.142509,98.10416,NaN,0.0,27.872674,4.789706,NaN,NaN,NaN
2018-12-07 00:10:00,0.784074,-0.066208,0.530192,NaN,-8.185083,-0.707191,0.498974,-1.009,45.40778,0.994896,5.191764,0.393667,1.603500,0.723257,3.100965,983.6542,-0.204861,0.300,-0.596,8.5,1.359652,99.86806,NaN,10.0,47.503921,7.088299,NaN,NaN,NaN
2018-12-08 00:10:00,2.595680,-0.668164,0.611927,NaN,-7.103809,-0.613769,0.291119,-3.369,29.76043,0.851104,5.081000,0.394417,1.494625,0.703340,2.917847,968.7765,-0.546965,0.081,-1.948,4.4,0.854312,99.50000,NaN,NaN,63.582288,6.657282,2.113271,4.013,N
2018-12-09 00:10:00,0.722303,-1.521313,0.822890,NaN,-6.286635,-0.543165,1.090572,-13.660,45.78611,0.918299,4.978882,0.438750,1.471201,0.734437,2.795486,971.3123,-2.675701,-0.425,-5.615,0.2,2.067057,97.26389,NaN,NaN,49.398304,4.815586,1.510097,3.812,NV
2018-12-10 00:10:00,0.751300,-2.938722,0.779939,NaN,-5.871264,-0.507277,0.849219,-10.030,46.02184,1.465993,4.872576,0.506958,1.459549,0.804660,2.696285,988.6810,1.157403,3.766,-4.173,0.0,2.018458,76.17361,NaN,19.0,47.459701,6.518459,2.992194,6.235,NV
2018-12-11 00:10:00,0.707177,-2.817427,0.563883,NaN,-5.402417,-0.466769,1.406764,-14.990,63.20111,1.901778,4.759597,0.588812,1.461493,0.863778,2.646722,1009.6670,0.758868,3.735,-6.743,0.0,2.828161,75.13465,NaN,18.0,32.623007,4.175883,2.616361,4.832,N
2018-12-12 22:10:00,0.552113,-1.607687,0.568240,NaN,-5.413264,-0.467706,1.891487,-17.580,41.33722,1.466694,4.693028,0.650132,1.483299,0.917424,2.607875,1020.4720,-6.032153,-2.048,-9.460,0.0,3.027292,98.19514,NaN,17.0,55.550530,3.112250,NaN,NaN,NaN
2018-12-13 22:10:00,0.788596,-0.294080,0.486171,NaN,-5.202694,-0.449513,0.468615,-6.274,36.15185,1.682854,4.605542,0.644826,1.459250,0.901535,2.530319,1022.9900,-5.462028,-4.929,-6.217,0.2,1.268141,95.26389,NaN,17.0,56.518423,7.329727,2.540396,4.167,N
2018-12-14 00:10:00,0.757965,-0.361724,0.496776,NaN,-4.907326,-0.423993,0.487178,-9.380,37.40683,1.807743,4.520215,0.668917,1.401708,0.912125,2.456951,1023.6290,-7.549840,-6.223,-9.140,0.0,1.302357,91.85764,NaN,17.0,55.553818,7.039352,1.822951,3.288,N
2018-12-15 00:10:00,0.790336,-0.451263,0.465728,NaN,-4.855365,-0.419503,0.449248,-8.450,36.12814,0.982826,4.422111,0.677195,1.370590,0.907062,2.394778,1021.1680,-5.627292,-1.944,-8.540,1.0,1.207986,93.70764,NaN,NaN,56.633357,7.238503,1.509257,2.697,N
2018-12-16 00:10:00,0.748424,-0.738231,0.456784,NaN,-4.251715,-0.367348,0.455249,-2.827,37.26573,0.935063,4.357625,0.675847,1.355417,0.904215,2.346479,1009.5020,-0.505632,0.187,-2.040,1.5,1.168568,93.99514,NaN,NaN,55.882061,6.852209,2.667333,4.059,√ò
2018-12-17 22:10:00,0.725240,-0.873497,1.135281,NaN,-3.555465,-0.307192,1.270855,-11.490,51.78816,1.007007,4.282896,0.798264,1.367646,0.963757,2.335264,1007.1630,-3.102604,-1.375,-5.237,1.1,2.706872,99.37917,NaN,20.0,44.146908,4.064932,1.076243,2.788,N
2018-12-18 00:10:00,0.837900,-0.271274,0.598734,NaN,-3.485184,-0.301120,0.559267,-4.897,44.68304,1.072222,4.216403,0.854632,1.397778,1.036910,2.322208,1011.2080,-4.164535,-2.751,-5.016,0.6,1.501040,99.65278,NaN,19.0,48.695974,6.620986,0.909535,2.079,N
2018-12-19 00:10:00,0.711765,-0.527623,0.233392,NaN,-3.408437,-0.294489,0.225485,-3.135,47.89760,1.196875,4.164993,0.916305,1.438201,1.072410,2.313292,1006.1320,-0.015722,1.486,-2.931,3.3,0.626588,99.52847,NaN,19.0,44.108957,7.993443,1.842535,3.027,√ò
2018-12-20 00:10:00,0.816733,-1.097929,0.187892,NaN,-3.567246,-0.308210,0.174457,-0.207,28.23969,1.282688,4.107924,0.955861,1.462951,1.109847,2.316410,1004.1960,0.983722,1.450,0.062,0.7,0.509647,96.31389,NaN,16.0,63.549099,8.211211,2.526660,3.815,√ò
2018-12-21 22:10:00,0.701868,-0.515824,0.375762,NaN,-3.557246,-0.307346,0.364153,-2.831,37.87324,1.750306,4.079236,0.992243,1.478194,1.158118,2.314333,1000.1270,-1.064292,0.037,-2.503,0.5,0.999070,87.70069,NaN,14.0,55.053363,7.073397,2.953264,3.941,N√ò
2018-12-22 00:10:00,0.752722,-0.722865,0.338192,NaN,-3.582708,-0.309546,0.323534,-5.060,34.21312,2.527778,4.049812,1.008451,1.497750,1.178979,2.323424,999.5062,-3.300639,-2.533,-4.271,0.0,0.911864,83.18840,NaN,NaN,58.624908,7.161972,1.692528,3.571,N
2018-12-23 00:10:00,0.661407,-1.322467,0.896327,NaN,-4.295028,-0.371090,0.915799,-17.800,48.73107,1.758174,4.039521,0.904299,1.482236,1.099333,2.309347,1003.3720,-5.367910,-3.273,-10.830,0.0,2.105036,92.95972,NaN,NaN,46.528415,4.740515,0.725639,1.695,NV
2018-12-24 00:10:00,0.684347,-0.834153,0.873651,NaN,-6.058024,-0.523413,0.984602,-18.520,54.26330,1.096764,3.988354,0.650195,1.379646,0.887687,2.250625,1007.2970,-7.872431,-2.061,-12.770,0.0,1.962061,98.82570,NaN,NaN,41.302402,4.434298,NaN,NaN,NaN
2018-12-25 00:10:00,0.669676,-2.126344,0.477907,NaN,-5.256490,-0.454161,0.606802,-10.280,32.20305,0.885320,3.954708,0.493354,1.217285,0.752347,2.191604,1002.8690,-1.082090,5.844,-5.023,0.0,1.571380,91.06236,NaN,14.0,62.261698,5.535252,1.300396,4.915,√ò
2018-12-26 00:10:00,0.684592,-0.875690,0.503858,NaN,-4.962451,-0.428756,0.461216,-11.080,60.84723,0.722833,3.893701,0.442549,1.146104,0.672882,2.096153,1004.6770,-1.380521,0.976,-5.676,0.5,0.966637,96.40625,NaN,NaN,33.970474,5.182296,0.841278,1.848,√ò
2018-12-27 00:10:00,0.648644,-1.037384,0.520922,NaN,-3.859840,-0.333490,0.542782,-7.409,38.36279,0.694146,3.838215,0.449583,1.094819,0.664396,2.068958,1000.7770,-1.244958,0.695,-4.085,1.8,1.339207,99.99931,NaN,13.0,55.943656,5.693554,0.776569,2.105,N√ò
2018-12-28 00:10:00,0.458021,-1.520098,0.991158,NaN,-4.974732,-0.429817,1.719382,-12.720,57.93696,0.775146,3.810514,0.444639,1.082417,0.668576,2.049465,1005.8380,-6.232451,-4.125,-8.200,0.0,2.614267,98.92361,NaN,NaN,39.267257,2.795783,NaN,NaN,NaN
2018-12-29 00:10:00,0.879624,-0.617260,0.577520,NaN,-5.268014,-0.455156,0.613190,-11.050,46.90142,0.660903,3.759500,0.332375,1.023354,0.542597,1.984889,1003.8350,-4.474945,-1.800,-7.296,0.1,1.723672,99.43750,NaN,NaN,47.482347,5.616233,NaN,NaN,NaN
2018-12-30 00:10:00,0.476756,-0.901978,0.896532,NaN,-5.038892,-0.435360,1.807672,-11.050,58.87096,0.611986,3.728389,0.261771,0.933201,0.470632,1.911840,1009.3070,-3.461583,-1.738,-5.724,0.3,3.238451,99.72916,NaN,NaN,38.155978,2.973062,NaN,NaN,NaN
2018-12-31 22:10:00,0.605755,-1.960404,0.422131,NaN,-4.760121,-0.411274,0.454753,-2.048,24.69542,0.509465,3.673660,0.231160,0.871861,0.429556,1.876417,1002.8510,1.882986,4.524,-1.915,1.9,1.215902,99.46528,NaN,13.0,67.885875,7.418705,4.387930,10.200,S

To look at the top five rows of a DataFrame, use the head function!

In [10]:
weather.head()

,albedo,balanse,diffus,fd,fluxm,fluxs,global,grmin,ir√∏d,jt010,jt100,jt002,jt020,jt005,jt050,lp,lt,ltmax,ltmin,nb,par,rf,sd,sdman,synlig,uv,vh,vhmax,vr
dato,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1988-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.1,5.9,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.7,5.3,1.5,20.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.3,2.1,0.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.1,0.4,-0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.1,0.6,-0.5,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

You can also view the top 12 elements by passing an argument to the head function

In [11]:
weather.head(12)

,albedo,balanse,diffus,fd,fluxm,fluxs,global,grmin,ir√∏d,jt010,jt100,jt002,jt020,jt005,jt050,lp,lt,ltmax,ltmin,nb,par,rf,sd,sdman,synlig,uv,vh,vhmax,vr
dato,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1988-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.1,5.9,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.7,5.3,1.5,20.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.3,2.1,0.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.1,0.4,-0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.1,0.6,-0.5,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988-01-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.5,0.2,-1.4,3.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988-01-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.3,0.2,-5.6,0.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988-01-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-6.2,-4.5,-10.7,0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988-01-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.5,2.9,-4.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988-01-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.2,5.8,1.9,5.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988-01-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.7,3.6,0.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988-01-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.2,4.3,-2.8,2.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

To look at the last five elements of a DataFrame, use the tail function

In [12]:
weather.tail()

,albedo,balanse,diffus,fd,fluxm,fluxs,global,grmin,ir√∏d,jt010,jt100,jt002,jt020,jt005,jt050,lp,lt,ltmax,ltmin,nb,par,rf,sd,sdman,synlig,uv,vh,vhmax,vr
dato,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2018-12-27 00:10:00,0.648644,-1.037384,0.520922,NaN,-3.859840,-0.333490,0.542782,-7.409,38.36279,0.694146,3.838215,0.449583,1.094819,0.664396,2.068958,1000.777,-1.244958,0.695,-4.085,1.8,1.339207,99.99931,NaN,13.0,55.943656,5.693554,0.776569,2.105,N√ò
2018-12-28 00:10:00,0.458021,-1.520098,0.991158,NaN,-4.974732,-0.429817,1.719382,-12.720,57.93696,0.775146,3.810514,0.444639,1.082417,0.668576,2.049465,1005.838,-6.232451,-4.125,-8.200,0.0,2.614267,98.92361,NaN,NaN,39.267257,2.795783,NaN,NaN,NaN
2018-12-29 00:10:00,0.879624,-0.617260,0.577520,NaN,-5.268014,-0.455156,0.613190,-11.050,46.90142,0.660903,3.759500,0.332375,1.023354,0.542597,1.984889,1003.835,-4.474945,-1.800,-7.296,0.1,1.723672,99.43750,NaN,NaN,47.482347,5.616233,NaN,NaN,NaN
2018-12-30 00:10:00,0.476756,-0.901978,0.896532,NaN,-5.038892,-0.435360,1.807672,-11.050,58.87096,0.611986,3.728389,0.261771,0.933201,0.470632,1.911840,1009.307,-3.461583,-1.738,-5.724,0.3,3.238451,99.72916,NaN,NaN,38.155978,2.973062,NaN,NaN,NaN
2018-12-31 22:10:00,0.605755,-1.960404,0.422131,NaN,-4.760121,-0.411274,0.454753,-2.048,24.69542,0.509465,3.673660,0.231160,0.871861,0.429556,1.876417,1002.851,1.882986,4.524,-1.915,1.9,1.215902,99.46528,NaN,13.0,67.885875,7.418705,4.387930,10.200,S

We can extract **columns** from the DataFrame using the ``[ ]`` operator.

In [13]:
# Let us see the air temperature column ('lt')
weather['lt']

dato
1988-01-01 00:00:00    5.100000
1988-01-02 00:00:00    3.700000
1988-01-03 00:00:00    1.300000
1988-01-04 00:00:00    0.100000
1988-01-05 00:00:00   -0.100000
1988-01-06 00:00:00   -0.500000
1988-01-07 00:00:00   -1.300000
1988-01-08 00:00:00   -6.200000
1988-01-09 00:00:00    0.500000
1988-01-10 00:00:00    4.200000
1988-01-11 00:00:00    1.700000
1988-01-12 00:00:00    0.200000
1988-01-13 00:00:00    3.600000
1988-01-14 00:00:00    3.200000
1988-01-15 00:00:00    3.100000
1988-01-16 00:00:00    0.700000
1988-01-17 00:00:00    0.400000
1988-01-18 00:00:00    1.300000
1988-01-19 00:00:00    0.400000
1988-01-20 00:00:00    1.700000
1988-01-21 00:00:00    1.900000
1988-01-22 00:00:00    2.000000
1988-01-23 00:00:00    0.000000
1988-01-24 00:00:00   -1.100000
1988-01-25 00:00:00    0.000000
1988-01-26 00:00:00   -0.600000
1988-01-27 00:00:00    0.300000
1988-01-28 00:00:00    0.300000
1988-01-29 00:00:00   -0.900000
1988-01-30 00:00:00   -3.300000
                         ...
2018-12-02 00:10:00    4.220986
2018-12-03 22:10:00    5.776055
2018-12-04 00:10:00    3.013479
2018-12-05 00:10:00   -2.114458
2018-12-06 00:10:00   -2.138097
2018-12-07 00:10:00   -0.204861
2018-12-08 00:10:00   -0.546965
2018-12-09 00:10:00   -2.675701
2018-12-10 00:10:00    1.157403
2018-12-11 00:10:00    0.758868
2018-12-12 22:10:00   -6.032153
2018-12-13 22:10:00   -5.462028
2018-12-14 00:10:00   -7.549840
2018-12-15 00:10:00   -5.627292
2018-12-16 00:10:00   -0.505632
2018-12-17 22:10:00   -3.102604
2018-12-18 00:10:00   -4.164535
2018-12-19 00:10:00   -0.015722
2018-12-20 00:10:00    0.983722
2018-12-21 22:10:00   -1.064292
2018-12-22 00:10:00   -3.300639
2018-12-23 00:10:00   -5.367910
2018-12-24 00:10:00   -7.872431
2018-12-25 00:10:00   -1.082090
2018-12-26 00:10:00   -1.380521
2018-12-27 00:10:00   -1.244958
2018-12-28 00:10:00   -6.232451
2018-12-29 00:10:00   -4.474945
2018-12-30 00:10:00   -3.461583
2018-12-31 22:10:00    1.882986
Name: lt, Length: 11323, dtype: float64

In [14]:
weather[['lt', 'lp']]

                           lt         lp
dato
1988-01-01 00:00:00  5.100000        NaN
1988-01-02 00:00:00  3.700000        NaN
1988-01-03 00:00:00  1.300000        NaN
1988-01-04 00:00:00  0.100000        NaN
1988-01-05 00:00:00 -0.100000        NaN
1988-01-06 00:00:00 -0.500000        NaN
1988-01-07 00:00:00 -1.300000        NaN
1988-01-08 00:00:00 -6.200000        NaN
1988-01-09 00:00:00  0.500000        NaN
1988-01-10 00:00:00  4.200000        NaN
1988-01-11 00:00:00  1.700000        NaN
1988-01-12 00:00:00  0.200000        NaN
1988-01-13 00:00:00  3.600000        NaN
1988-01-14 00:00:00  3.200000        NaN
1988-01-15 00:00:00  3.100000        NaN
1988-01-16 00:00:00  0.700000        NaN
1988-01-17 00:00:00  0.400000        NaN
1988-01-18 00:00:00  1.300000        NaN
1988-01-19 00:00:00  0.400000        NaN
1988-01-20 00:00:00  1.700000        NaN
1988-01-21 00:00:00  1.900000        NaN
1988-01-22 00:00:00  2.000000        NaN
1988-01-23 00:00:00  0.000000        NaN
1988-01-24 00:00:00 -1.100000        NaN
1988-01-25 00:00:00  0.000000        NaN
1988-01-26 00:00:00 -0.600000        NaN
1988-01-27 00:00:00  0.300000        NaN
1988-01-28 00:00:00  0.300000        NaN
1988-01-29 00:00:00 -0.900000        NaN
1988-01-30 00:00:00 -3.300000        NaN
...                       ...        ...
2018-12-02 00:10:00  4.220986   984.5229
2018-12-03 22:10:00  5.776055   973.7991
2018-12-04 00:10:00  3.013479   987.1948
2018-12-05 00:10:00 -2.114458  1004.8450
2018-12-06 00:10:00 -2.138097   998.6358
2018-12-07 00:10:00 -0.204861   983.6542
2018-12-08 00:10:00 -0.546965   968.7765
2018-12-09 00:10:00 -2.675701   971.3123
2018-12-10 00:10:00  1.157403   988.6810
2018-12-11 00:10:00  0.758868  1009.6670
2018-12-12 22:10:00 -6.032153  1020.4720
2018-12-13 22:10:00 -5.462028  1022.9900
2018-12-14 00:10:00 -7.549840  1023.6290
2018-12-15 00:10:00 -5.627292  1021.1680
2018-12-16 00:10:00 -0.505632  1009.5020
2018-12-17 22:10:00 -3.102604  1007.1630
2018-12-18 00:10:00 -4.164535  1011.2080
2018-12-19 00:10:00 -0.015722  1006.1320
2018-12-20 00:10:00  0.983722  1004.1960
2018-12-21 22:10:00 -1.064292  1000.1270
2018-12-22 00:10:00 -3.300639   999.5062
2018-12-23 00:10:00 -5.367910  1003.3720
2018-12-24 00:10:00 -7.872431  1007.2970
2018-12-25 00:10:00 -1.082090  1002.8690
2018-12-26 00:10:00 -1.380521  1004.6770
2018-12-27 00:10:00 -1.244958  1000.7770
2018-12-28 00:10:00 -6.232451  1005.8380
2018-12-29 00:10:00 -4.474945  1003.8350
2018-12-30 00:10:00 -3.461583  1009.3070
2018-12-31 22:10:00  1.882986  1002.8510

[11323 rows x 2 columns]

To get a single row, use the ``loc`` indexer

In [15]:
weather.loc['2018-12-01']

,albedo,balanse,diffus,fd,fluxm,fluxs,global,grmin,ir√∏d,jt010,jt100,jt002,jt020,jt005,jt050,lp,lt,ltmax,ltmin,nb,par,rf,sd,sdman,synlig,uv,vh,vhmax,vr
dato,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2018-12-01 00:10:00,0.189925,-2.036509,1.079653,NaN,2.981885,0.257635,1.137375,0.547,43.09908,0.577597,5.588583,-0.040903,1.119347,0.29716,2.765424,990.4388,5.167132,6.555,3.174,4.5,2.5389,97.88194,NaN,NaN,52.561718,4.339202,3.822826,6.556,S

Let's get all rows corresponding to January 2014

In [16]:
weather.loc['2014-01']

,albedo,balanse,diffus,fd,fluxm,fluxs,global,grmin,ir√∏d,jt010,jt100,jt002,jt020,jt005,jt050,lp,lt,ltmax,ltmin,nb,par,rf,sd,sdman,synlig,uv,vh,vhmax,vr
dato,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2014-01-01 22:10:00,0.212504,1.472058,0.314151,NaN,NaN,NaN,0.308431,0.048,46.17082,2.813993,3.807889,2.873403,2.792799,3.118674,3.120056,995.4855,2.909611,4.623,0.818,5.0,0.735746,97.43264,NaN,NaN,46.891749,6.937431,3.377445,5.554,S√ò
2014-01-02 22:10:00,0.181289,1.600755,0.161916,NaN,NaN,NaN,0.152044,-0.100,38.70572,2.807681,3.759681,2.386132,2.673368,2.861694,3.287507,990.0685,2.492007,3.380,0.617,15.8,0.412501,98.36459,NaN,NaN,50.849030,10.445250,3.113667,5.287,√ò
2014-01-03 00:10:00,0.183521,1.028623,0.353300,NaN,NaN,NaN,0.327961,2.163,53.62943,3.041687,3.781222,3.143861,2.772701,3.156861,3.270778,985.8883,4.437792,5.770,2.594,14.4,0.790246,99.05070,NaN,NaN,38.923273,7.447297,4.290292,7.250,S√ò
2014-01-04 00:10:00,0.147176,1.728845,0.341543,NaN,NaN,NaN,0.373690,1.314,38.20015,3.465236,3.835611,3.711555,3.232215,3.777701,3.351972,984.2529,4.818438,6.252,2.932,6.5,0.880677,99.16805,NaN,NaN,53.420503,8.379347,3.478229,5.983,S
2014-01-05 22:10:00,0.212335,2.409874,0.603599,NaN,NaN,NaN,0.687287,0.619,40.08245,3.208542,3.892028,3.094361,3.312042,3.387715,3.766500,989.8094,3.392854,5.188,2.633,1.7,1.727642,97.84306,NaN,NaN,52.209421,7.708129,2.243389,4.011,√ò
2014-01-06 22:10:00,0.329765,1.238854,0.184821,NaN,NaN,NaN,0.158275,-0.414,54.11974,2.986569,3.960194,2.841632,3.160111,3.012729,3.681653,985.3823,3.214160,6.796,0.328,13.7,0.422200,99.44375,NaN,NaN,37.094517,8.785743,3.700549,5.633,S√ò
2014-01-07 22:10:00,0.194982,-0.349197,0.622471,NaN,NaN,NaN,0.638080,4.604,47.55056,3.786535,3.972236,4.325660,3.402458,4.207562,3.649917,983.3116,6.806174,7.270,5.978,0.4,1.499442,98.80139,NaN,NaN,46.061272,6.388168,5.227292,7.670,S
2014-01-08 22:10:00,0.196094,-2.379199,0.653858,NaN,NaN,NaN,0.675346,-2.803,46.64856,4.164826,3.991146,4.238542,3.848118,4.305611,3.885139,985.8708,5.226771,6.315,2.176,0.6,1.579445,98.90694,NaN,NaN,46.257383,7.094057,2.864708,4.692,S
2014-01-09 00:10:00,0.194018,-1.139041,0.512747,NaN,NaN,NaN,0.425245,-5.762,64.13011,3.039271,4.107639,2.338681,3.485132,2.687472,3.946931,983.6486,0.781535,2.054,-1.754,0.7,0.964647,99.35764,NaN,NaN,28.427266,7.442624,2.393750,5.606,N
2014-01-10 22:10:00,0.204915,-2.920590,0.786588,NaN,NaN,NaN,0.845087,-6.255,41.87250,2.501563,4.155972,1.839042,2.887687,2.075500,3.812910,984.5569,-0.245035,1.085,-1.567,0.1,2.056103,95.49722,NaN,NaN,50.880173,7.247327,2.114028,5.135,S√ò
2014-01-11 00:10:00,0.215595,-1.329761,0.295450,NaN,NaN,NaN,0.347738,-6.082,53.57596,1.610049,4.173409,1.022993,2.271278,1.300840,3.501167,987.3982,-2.515472,-0.132,-4.910,0.5,0.865655,98.24861,NaN,NaN,38.210797,8.213243,2.289465,3.665,N
2014-01-12 00:10:00,0.721612,-4.030578,0.557348,NaN,NaN,NaN,1.494851,-20.070,61.37142,1.150104,4.109160,0.686625,1.827653,0.982243,3.249438,1000.1930,-8.539660,-4.807,-13.450,1.1,3.451746,82.40375,NaN,NaN,32.848259,5.780321,2.603243,5.169,N√ò
2014-01-13 22:10:00,0.641957,-1.968539,0.592201,NaN,NaN,NaN,0.601325,-21.260,62.65536,0.837021,4.017562,0.278451,1.484944,0.561611,2.858181,1004.7610,-11.602150,-8.750,-14.650,2.1,1.367761,88.93333,NaN,NaN,30.109814,7.234826,2.504076,14.940,N
2014-01-14 00:10:00,0.841800,-0.444984,0.406355,NaN,NaN,NaN,0.386488,-7.630,41.17762,0.644417,3.892208,0.215062,1.164361,0.351861,2.839701,1003.5390,-7.071583,-6.262,-8.710,1.8,1.036451,92.48681,NaN,NaN,48.386550,10.435830,2.986965,3.772,N
2014-01-15 00:10:00,0.881850,-0.478213,0.504128,NaN,NaN,NaN,0.477611,-6.733,42.84245,0.586903,3.707757,0.289250,0.954417,0.275840,2.541285,1003.2310,-5.701576,-5.168,-6.357,3.1,1.258280,91.79583,NaN,NaN,47.646848,9.510702,2.632521,3.501,N
2014-01-16 00:10:00,0.889896,-0.615672,0.780552,NaN,NaN,NaN,0.748477,-5.488,41.72948,0.550993,3.630653,0.249493,0.985250,0.292528,2.531243,1002.6650,-4.056833,-2.933,-5.311,3.3,1.962133,92.18542,NaN,NaN,49.266151,9.004369,3.630361,5.164,√ò
2014-01-17 00:10:00,0.893542,-0.638727,0.594913,NaN,NaN,NaN,0.573658,-7.800,42.86040,0.606639,3.528424,0.290208,0.885361,0.315590,2.249569,1002.5770,-5.269493,-3.902,-7.320,1.3,1.507763,84.76250,NaN,NaN,47.838138,9.301462,3.240375,4.257,N√ò
2014-01-18 00:10:00,0.868377,-0.805972,1.062402,NaN,NaN,NaN,1.033010,-7.020,47.28304,0.600347,3.447965,0.320410,0.864299,0.299646,2.083861,1008.5520,-5.792931,-5.116,-6.777,0.3,2.542353,84.77778,NaN,NaN,44.312800,8.404160,3.355729,4.269,N√ò
2014-01-19 00:10:00,0.880867,-0.620819,0.720859,NaN,NaN,NaN,0.687006,-6.553,44.38214,0.598847,3.360403,0.338590,0.821764,0.263125,2.143063,1013.4830,-4.447340,-3.557,-5.607,0.0,1.798579,82.46597,NaN,NaN,46.352002,9.265858,3.259305,4.168,N√ò
2014-01-20 00:10:00,0.858891,-1.126792,1.302063,NaN,NaN,NaN,1.296169,-7.670,49.19464,0.614215,3.313972,0.339000,0.821347,0.267472,1.859799,1013.6030,-4.559326,-3.631,-5.673,0.0,3.204240,77.28333,NaN,NaN,43.082664,7.722696,3.135750,4.354,N√ò
2014-01-21 22:10:00,0.853018,-0.612652,0.979695,NaN,NaN,NaN,0.934390,-7.210,48.16451,0.611896,3.229111,0.415514,0.827229,0.288854,1.801917,1013.2330,-5.125340,-4.218,-6.840,0.0,2.339277,79.72292,NaN,NaN,43.774190,8.061300,3.094014,4.248,N√ò
2014-01-22 22:10:00,0.849186,-0.571402,0.948478,NaN,NaN,NaN,0.912553,-8.530,45.19728,0.608299,3.201056,0.313201,0.782160,0.300736,1.956215,1015.4470,-7.418555,-6.844,-8.290,0.0,2.276052,84.67292,NaN,NaN,46.340610,8.462110,3.391014,4.613,N√ò
2014-01-23 22:10:00,0.885702,-0.768759,1.087048,NaN,NaN,NaN,1.037285,-7.890,46.64390,0.483743,3.150208,0.348486,0.717521,0.229222,1.867264,1014.1990,-7.025542,-6.175,-8.150,1.0,2.561767,90.23959,NaN,NaN,45.532679,7.823421,2.263674,4.119,√ò
2014-01-24 00:10:00,0.859729,-0.934193,1.058551,NaN,NaN,NaN,1.016161,-7.300,45.43210,0.485264,3.093924,0.378764,0.708917,0.269132,1.699729,1017.0770,-6.483986,-5.700,-7.510,0.3,2.559413,89.24792,NaN,NaN,46.213812,8.354088,1.586271,2.600,N√ò
2014-01-25 22:10:00,0.886273,-0.622330,0.631492,NaN,NaN,NaN,0.607217,-7.880,47.20062,0.453576,3.082236,0.374007,0.735611,0.305840,1.724437,1012.1280,-5.626743,-4.411,-7.250,0.1,1.623076,81.49306,NaN,NaN,44.028979,8.770401,4.731340,6.499,S√ò
2014-01-26 22:10:00,0.879077,-0.903486,1.040124,NaN,NaN,NaN,0.980839,-7.760,46.25964,0.498882,3.025778,0.304201,0.704521,0.227035,1.686306,1005.9510,-6.516278,-5.617,-7.220,1.2,2.477634,84.52500,NaN,NaN,45.326076,8.414284,2.217306,4.702,√ò
2014-01-27 00:10:00,0.881399,-0.622692,1.019614,NaN,NaN,NaN,0.978601,-6.132,45.15895,0.530375,2.965472,0.331389,0.688937,0.291910,1.658563,994.2891,-3.420632,-2.267,-5.608,4.2,2.550632,90.53472,NaN,NaN,46.676003,8.165047,2.814889,3.875,√ò
2014-01-28 00:10:00,0.948150,-0.748412,0.601627,NaN,NaN,NaN,0.564784,-3.142,33.64758,0.531292,2.901375,0.336368,0.732931,0.309354,1.804292,1001.5910,-1.520465,-0.950,-2.506,4.3,1.681810,94.68195,NaN,NaN,57.334958,9.017462,2.618021,4.571,√ò
2014-01-29 22:10:00,0.847508,-1.021778,1.055636,NaN,NaN,NaN,1.022918,-6.277,45.07858,0.505958,2.905549,0.282785,0.717514,0.290750,1.625465,1011.2420,-3.189854,-0.984,-5.909,0.2,2.651105,75.23458,NaN,NaN,46.455871,8.465549,3.253924,4.864,N√ò
2014-01-30 00:10:00,0.910618,-0.711955,0.726389,NaN,NaN,NaN,0.690855,-6.520,43.22348,0.500069,2.839118,0.372431,0.693507,0.288187,1.630792,1011.4320,-5.092417,-4.374,-6.041,3.7,1.907678,90.70000,NaN,NaN,47.898825,8.877695,2.977556,4.533,N√ò
2014-01-31 00:10:00,0.917848,-0.703838,1.086653,NaN,NaN,NaN,1.016007,-5.958,43.64675,0.601500,2.876903,0.363167,0.707778,0.301722,1.512285,1005.4990,-4.143743,-3.377,-4.856,2.3,2.774536,93.61945,NaN,NaN,47.261659,9.091591,2.084021,2.969,N√ò

If you use a CSV file, then you might need some conversion. To do this, google "strptime"

If we want the percentage infra red ('ir√∏d') and ultra violet ('uv') radation in january 2018, we do that the following way

In [17]:
weather.loc['2018-01', ['ir√∏d', 'uv']]

                         ir√∏d        uv
dato
2018-01-01 00:10:00  41.68492  4.944655
2018-01-02 00:10:00  50.90939  4.407947
2018-01-03 22:10:00  50.43779  6.166358
2018-01-04 00:10:00  41.68610  6.385012
2018-01-05 00:10:00  31.26810  6.911481
2018-01-06 00:10:00  71.58167  3.922499
2018-01-07 00:10:00  47.92217  5.154746
2018-01-08 22:10:00  64.19691  3.270998
2018-01-09 00:10:00  37.52836  7.166275
2018-01-10 22:10:00  52.97937  4.112136
2018-01-11 00:10:00  35.87284  7.394621
2018-01-12 22:10:00  41.11026  7.070111
2018-01-13 22:10:00  37.29935  7.415319
2018-01-14 22:10:00  46.05742  7.180796
2018-01-15 00:10:00  55.25262  5.453138
2018-01-16 00:10:00  34.93584  6.255599
2018-01-17 00:10:00  44.82857  5.902848
2018-01-18 00:10:00  38.41044  6.866032
2018-01-19 22:10:00  36.99257  6.845589
2018-01-20 00:10:00  45.70993  6.542763
2018-01-21 00:10:00  44.80058  5.839026
2018-01-22 22:10:00  40.41504  5.909199
2018-01-23 00:10:00  41.22897  6.826710
2018-01-24 00:10:00  32.82938  6.696863
2018-01-25 00:10:00  39.85447  5.288078
2018-01-26 22:10:00  49.41974  4.743165
2018-01-27 22:10:00  55.11729  3.391768
2018-01-28 22:10:00  45.21668  5.240556
2018-01-29 00:10:00  46.11165  6.277312
2018-01-30 00:10:00  48.43203  5.639763
2018-01-31 00:10:00  35.21358  4.951124

We can also get a single column, say the air temperatue in 1999

In [18]:
weather.loc['1999', 'lt']

dato
1999-01-01     0.153903
1999-01-02     0.493326
1999-01-03     2.111910
1999-01-04     1.806611
1999-01-05    -0.470500
1999-01-06    -0.738715
1999-01-07    -4.256354
1999-01-08    -8.490702
1999-01-09    -5.214153
1999-01-10    -6.186375
1999-01-11    -7.354569
1999-01-12    -9.621805
1999-01-13   -11.692083
1999-01-14    -9.006458
1999-01-15    -8.878549
1999-01-16     1.910299
1999-01-17     2.123500
1999-01-18     3.252875
1999-01-19     4.174271
1999-01-20     4.682986
1999-01-21     3.626618
1999-01-22     0.962097
1999-01-23     3.334271
1999-01-24     3.796500
1999-01-25     1.852035
1999-01-26    -2.974493
1999-01-27    -7.668715
1999-01-28   -15.295417
1999-01-29   -10.329820
1999-01-30    -7.335423
                ...
1999-12-02    -0.519368
1999-12-03    -4.967569
1999-12-04    -4.043188
1999-12-05    -6.524750
1999-12-06     4.648896
1999-12-07     4.013826
1999-12-08    -1.438625
1999-12-09    -1.691951
1999-12-10    -2.942819
1999-12-11    -7.728215
1999-12-12    -5.186931
1999-12-13    -5.132569
1999-12-14   -11.280000
1999-12-15   -10.584350
1999-12-16   -13.016110
1999-12-17     0.015194
1999-12-18    -3.019139
1999-12-19    -3.934826
1999-12-20    -6.991076
1999-12-21    -9.842299
1999-12-22    -1.109354
1999-12-23     2.378521
1999-12-24     3.685639
1999-12-25     3.936014
1999-12-26     2.677250
1999-12-27     0.364792
1999-12-28    -1.422833
1999-12-29    -5.257854
1999-12-30    -6.288204
1999-12-31    -8.955556
Name: lt, Length: 365, dtype: float64

### Exercises

 1. Extract solely the 'uv' column from the data frame
 2. Extract the 'uv' and the 'ir√∏d' column from the data frame
 3. Exstract all columns from december 2018


*Detour:*
We can also have undered lists like so

 * Element 1
 * Eleemnt 2
   - Sub element

In [19]:
# 1:
weather['uv']

dato
1988-01-01 00:00:00         NaN
1988-01-02 00:00:00         NaN
1988-01-03 00:00:00         NaN
1988-01-04 00:00:00         NaN
1988-01-05 00:00:00         NaN
1988-01-06 00:00:00         NaN
1988-01-07 00:00:00         NaN
1988-01-08 00:00:00         NaN
1988-01-09 00:00:00         NaN
1988-01-10 00:00:00         NaN
1988-01-11 00:00:00         NaN
1988-01-12 00:00:00         NaN
1988-01-13 00:00:00         NaN
1988-01-14 00:00:00         NaN
1988-01-15 00:00:00         NaN
1988-01-16 00:00:00         NaN
1988-01-17 00:00:00         NaN
1988-01-18 00:00:00         NaN
1988-01-19 00:00:00         NaN
1988-01-20 00:00:00         NaN
1988-01-21 00:00:00         NaN
1988-01-22 00:00:00         NaN
1988-01-23 00:00:00         NaN
1988-01-24 00:00:00         NaN
1988-01-25 00:00:00         NaN
1988-01-26 00:00:00         NaN
1988-01-27 00:00:00         NaN
1988-01-28 00:00:00         NaN
1988-01-29 00:00:00         NaN
1988-01-30 00:00:00         NaN
                         ...
2018-12-02 00:10:00    4.857520
2018-12-03 22:10:00    5.572815
2018-12-04 00:10:00    5.366416
2018-12-05 00:10:00    2.417055
2018-12-06 00:10:00    4.789706
2018-12-07 00:10:00    7.088299
2018-12-08 00:10:00    6.657282
2018-12-09 00:10:00    4.815586
2018-12-10 00:10:00    6.518459
2018-12-11 00:10:00    4.175883
2018-12-12 22:10:00    3.112250
2018-12-13 22:10:00    7.329727
2018-12-14 00:10:00    7.039352
2018-12-15 00:10:00    7.238503
2018-12-16 00:10:00    6.852209
2018-12-17 22:10:00    4.064932
2018-12-18 00:10:00    6.620986
2018-12-19 00:10:00    7.993443
2018-12-20 00:10:00    8.211211
2018-12-21 22:10:00    7.073397
2018-12-22 00:10:00    7.161972
2018-12-23 00:10:00    4.740515
2018-12-24 00:10:00    4.434298
2018-12-25 00:10:00    5.535252
2018-12-26 00:10:00    5.182296
2018-12-27 00:10:00    5.693554
2018-12-28 00:10:00    2.795783
2018-12-29 00:10:00    5.616233
2018-12-30 00:10:00    2.973062
2018-12-31 22:10:00    7.418705
Name: uv, Length: 11323, dtype: float64

In [20]:
# 2:
weather[['uv', 'ir√∏d']]

                           uv      ir√∏d
dato
1988-01-01 00:00:00       NaN       NaN
1988-01-02 00:00:00       NaN       NaN
1988-01-03 00:00:00       NaN       NaN
1988-01-04 00:00:00       NaN       NaN
1988-01-05 00:00:00       NaN       NaN
1988-01-06 00:00:00       NaN       NaN
1988-01-07 00:00:00       NaN       NaN
1988-01-08 00:00:00       NaN       NaN
1988-01-09 00:00:00       NaN       NaN
1988-01-10 00:00:00       NaN       NaN
1988-01-11 00:00:00       NaN       NaN
1988-01-12 00:00:00       NaN       NaN
1988-01-13 00:00:00       NaN       NaN
1988-01-14 00:00:00       NaN       NaN
1988-01-15 00:00:00       NaN       NaN
1988-01-16 00:00:00       NaN       NaN
1988-01-17 00:00:00       NaN       NaN
1988-01-18 00:00:00       NaN       NaN
1988-01-19 00:00:00       NaN       NaN
1988-01-20 00:00:00       NaN       NaN
1988-01-21 00:00:00       NaN       NaN
1988-01-22 00:00:00       NaN       NaN
1988-01-23 00:00:00       NaN       NaN
1988-01-24 00:00:00       NaN       NaN
1988-01-25 00:00:00       NaN       NaN
1988-01-26 00:00:00       NaN       NaN
1988-01-27 00:00:00       NaN       NaN
1988-01-28 00:00:00       NaN       NaN
1988-01-29 00:00:00       NaN       NaN
1988-01-30 00:00:00       NaN       NaN
...                       ...       ...
2018-12-02 00:10:00  4.857520  65.57986
2018-12-03 22:10:00  5.572815  44.84836
2018-12-04 00:10:00  5.366416  38.28223
2018-12-05 00:10:00  2.417055  54.21980
2018-12-06 00:10:00  4.789706  67.33762
2018-12-07 00:10:00  7.088299  45.40778
2018-12-08 00:10:00  6.657282  29.76043
2018-12-09 00:10:00  4.815586  45.78611
2018-12-10 00:10:00  6.518459  46.02184
2018-12-11 00:10:00  4.175883  63.20111
2018-12-12 22:10:00  3.112250  41.33722
2018-12-13 22:10:00  7.329727  36.15185
2018-12-14 00:10:00  7.039352  37.40683
2018-12-15 00:10:00  7.238503  36.12814
2018-12-16 00:10:00  6.852209  37.26573
2018-12-17 22:10:00  4.064932  51.78816
2018-12-18 00:10:00  6.620986  44.68304
2018-12-19 00:10:00  7.993443  47.89760
2018-12-20 00:10:00  8.211211  28.23969
2018-12-21 22:10:00  7.073397  37.87324
2018-12-22 00:10:00  7.161972  34.21312
2018-12-23 00:10:00  4.740515  48.73107
2018-12-24 00:10:00  4.434298  54.26330
2018-12-25 00:10:00  5.535252  32.20305
2018-12-26 00:10:00  5.182296  60.84723
2018-12-27 00:10:00  5.693554  38.36279
2018-12-28 00:10:00  2.795783  57.93696
2018-12-29 00:10:00  5.616233  46.90142
2018-12-30 00:10:00  2.973062  58.87096
2018-12-31 22:10:00  7.418705  24.69542

[11323 rows x 2 columns]

In [21]:
weather.loc['2018-12']

,albedo,balanse,diffus,fd,fluxm,fluxs,global,grmin,ir√∏d,jt010,jt100,jt002,jt020,jt005,jt050,lp,lt,ltmax,ltmin,nb,par,rf,sd,sdman,synlig,uv,vh,vhmax,vr
dato,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2018-12-01 00:10:00,0.189925,-2.036509,1.079653,NaN,2.981885,0.257635,1.137375,0.547,43.09908,0.577597,5.588583,-0.040903,1.119347,0.297160,2.765424,990.4388,5.167132,6.555,3.174,4.5,2.538900,97.88194,NaN,NaN,52.561718,4.339202,3.822826,6.556,S
2018-12-02 00:10:00,0.172544,-0.561167,0.460905,NaN,3.291177,0.284358,0.421363,-0.038,65.57986,1.039569,5.445042,0.737660,1.422431,0.832167,2.793424,984.5229,4.220986,4.773,2.480,12.0,0.853293,99.96528,NaN,NaN,29.562620,4.857520,2.898785,4.087,√ò
2018-12-03 22:10:00,0.108175,0.017563,0.393376,NaN,6.200490,0.535722,0.384140,4.363,44.84836,2.410222,5.309354,2.739563,2.247729,2.601854,2.943118,973.7991,5.776055,7.378,4.749,8.6,0.906667,100.00000,NaN,0.0,49.578825,5.572815,1.775410,4.439,√ò
2018-12-04 00:10:00,0.221060,-3.654298,0.729919,NaN,-7.121333,-0.615283,0.811693,-7.964,38.28223,3.107917,5.253472,2.774570,2.969076,2.952181,3.321132,987.1948,3.013479,4.880,-1.672,4.7,1.853481,72.02778,NaN,0.0,56.351354,5.366416,3.472875,6.210,NV
2018-12-05 00:10:00,0.223798,-4.569000,2.154242,NaN,-14.243610,-1.230648,2.455054,-12.370,54.21980,1.867806,5.264812,0.946854,2.501972,1.445979,3.536944,1004.8450,-2.114458,0.578,-5.752,0.0,3.244609,75.22916,NaN,0.0,43.363145,2.417055,1.735375,4.125,S
2018-12-06 00:10:00,0.291290,-1.070306,0.619717,NaN,-10.252400,-0.885807,0.556293,-11.660,67.33762,1.261222,5.252576,0.446042,1.917250,0.868993,3.374979,998.6358,-2.138097,0.326,-5.997,7.4,1.142509,98.10416,NaN,0.0,27.872674,4.789706,NaN,NaN,NaN
2018-12-07 00:10:00,0.784074,-0.066208,0.530192,NaN,-8.185083,-0.707191,0.498974,-1.009,45.40778,0.994896,5.191764,0.393667,1.603500,0.723257,3.100965,983.6542,-0.204861,0.300,-0.596,8.5,1.359652,99.86806,NaN,10.0,47.503921,7.088299,NaN,NaN,NaN
2018-12-08 00:10:00,2.595680,-0.668164,0.611927,NaN,-7.103809,-0.613769,0.291119,-3.369,29.76043,0.851104,5.081000,0.394417,1.494625,0.703340,2.917847,968.7765,-0.546965,0.081,-1.948,4.4,0.854312,99.50000,NaN,NaN,63.582288,6.657282,2.113271,4.013,N
2018-12-09 00:10:00,0.722303,-1.521313,0.822890,NaN,-6.286635,-0.543165,1.090572,-13.660,45.78611,0.918299,4.978882,0.438750,1.471201,0.734437,2.795486,971.3123,-2.675701,-0.425,-5.615,0.2,2.067057,97.26389,NaN,NaN,49.398304,4.815586,1.510097,3.812,NV
2018-12-10 00:10:00,0.751300,-2.938722,0.779939,NaN,-5.871264,-0.507277,0.849219,-10.030,46.02184,1.465993,4.872576,0.506958,1.459549,0.804660,2.696285,988.6810,1.157403,3.766,-4.173,0.0,2.018458,76.17361,NaN,19.0,47.459701,6.518459,2.992194,6.235,NV
2018-12-11 00:10:00,0.707177,-2.817427,0.563883,NaN,-5.402417,-0.466769,1.406764,-14.990,63.20111,1.901778,4.759597,0.588812,1.461493,0.863778,2.646722,1009.6670,0.758868,3.735,-6.743,0.0,2.828161,75.13465,NaN,18.0,32.623007,4.175883,2.616361,4.832,N
2018-12-12 22:10:00,0.552113,-1.607687,0.568240,NaN,-5.413264,-0.467706,1.891487,-17.580,41.33722,1.466694,4.693028,0.650132,1.483299,0.917424,2.607875,1020.4720,-6.032153,-2.048,-9.460,0.0,3.027292,98.19514,NaN,17.0,55.550530,3.112250,NaN,NaN,NaN
2018-12-13 22:10:00,0.788596,-0.294080,0.486171,NaN,-5.202694,-0.449513,0.468615,-6.274,36.15185,1.682854,4.605542,0.644826,1.459250,0.901535,2.530319,1022.9900,-5.462028,-4.929,-6.217,0.2,1.268141,95.26389,NaN,17.0,56.518423,7.329727,2.540396,4.167,N
2018-12-14 00:10:00,0.757965,-0.361724,0.496776,NaN,-4.907326,-0.423993,0.487178,-9.380,37.40683,1.807743,4.520215,0.668917,1.401708,0.912125,2.456951,1023.6290,-7.549840,-6.223,-9.140,0.0,1.302357,91.85764,NaN,17.0,55.553818,7.039352,1.822951,3.288,N
2018-12-15 00:10:00,0.790336,-0.451263,0.465728,NaN,-4.855365,-0.419503,0.449248,-8.450,36.12814,0.982826,4.422111,0.677195,1.370590,0.907062,2.394778,1021.1680,-5.627292,-1.944,-8.540,1.0,1.207986,93.70764,NaN,NaN,56.633357,7.238503,1.509257,2.697,N
2018-12-16 00:10:00,0.748424,-0.738231,0.456784,NaN,-4.251715,-0.367348,0.455249,-2.827,37.26573,0.935063,4.357625,0.675847,1.355417,0.904215,2.346479,1009.5020,-0.505632,0.187,-2.040,1.5,1.168568,93.99514,NaN,NaN,55.882061,6.852209,2.667333,4.059,√ò
2018-12-17 22:10:00,0.725240,-0.873497,1.135281,NaN,-3.555465,-0.307192,1.270855,-11.490,51.78816,1.007007,4.282896,0.798264,1.367646,0.963757,2.335264,1007.1630,-3.102604,-1.375,-5.237,1.1,2.706872,99.37917,NaN,20.0,44.146908,4.064932,1.076243,2.788,N
2018-12-18 00:10:00,0.837900,-0.271274,0.598734,NaN,-3.485184,-0.301120,0.559267,-4.897,44.68304,1.072222,4.216403,0.854632,1.397778,1.036910,2.322208,1011.2080,-4.164535,-2.751,-5.016,0.6,1.501040,99.65278,NaN,19.0,48.695974,6.620986,0.909535,2.079,N
2018-12-19 00:10:00,0.711765,-0.527623,0.233392,NaN,-3.408437,-0.294489,0.225485,-3.135,47.89760,1.196875,4.164993,0.916305,1.438201,1.072410,2.313292,1006.1320,-0.015722,1.486,-2.931,3.3,0.626588,99.52847,NaN,19.0,44.108957,7.993443,1.842535,3.027,√ò
2018-12-20 00:10:00,0.816733,-1.097929,0.187892,NaN,-3.567246,-0.308210,0.174457,-0.207,28.23969,1.282688,4.107924,0.955861,1.462951,1.109847,2.316410,1004.1960,0.983722,1.450,0.062,0.7,0.509647,96.31389,NaN,16.0,63.549099,8.211211,2.526660,3.815,√ò
2018-12-21 22:10:00,0.701868,-0.515824,0.375762,NaN,-3.557246,-0.307346,0.364153,-2.831,37.87324,1.750306,4.079236,0.992243,1.478194,1.158118,2.314333,1000.1270,-1.064292,0.037,-2.503,0.5,0.999070,87.70069,NaN,14.0,55.053363,7.073397,2.953264,3.941,N√ò
2018-12-22 00:10:00,0.752722,-0.722865,0.338192,NaN,-3.582708,-0.309546,0.323534,-5.060,34.21312,2.527778,4.049812,1.008451,1.497750,1.178979,2.323424,999.5062,-3.300639,-2.533,-4.271,0.0,0.911864,83.18840,NaN,NaN,58.624908,7.161972,1.692528,3.571,N
2018-12-23 00:10:00,0.661407,-1.322467,0.896327,NaN,-4.295028,-0.371090,0.915799,-17.800,48.73107,1.758174,4.039521,0.904299,1.482236,1.099333,2.309347,1003.3720,-5.367910,-3.273,-10.830,0.0,2.105036,92.95972,NaN,NaN,46.528415,4.740515,0.725639,1.695,NV
2018-12-24 00:10:00,0.684347,-0.834153,0.873651,NaN,-6.058024,-0.523413,0.984602,-18.520,54.26330,1.096764,3.988354,0.650195,1.379646,0.887687,2.250625,1007.2970,-7.872431,-2.061,-12.770,0.0,1.962061,98.82570,NaN,NaN,41.302402,4.434298,NaN,NaN,NaN
2018-12-25 00:10:00,0.669676,-2.126344,0.477907,NaN,-5.256490,-0.454161,0.606802,-10.280,32.20305,0.885320,3.954708,0.493354,1.217285,0.752347,2.191604,1002.8690,-1.082090,5.844,-5.023,0.0,1.571380,91.06236,NaN,14.0,62.261698,5.535252,1.300396,4.915,√ò
2018-12-26 00:10:00,0.684592,-0.875690,0.503858,NaN,-4.962451,-0.428756,0.461216,-11.080,60.84723,0.722833,3.893701,0.442549,1.146104,0.672882,2.096153,1004.6770,-1.380521,0.976,-5.676,0.5,0.966637,96.40625,NaN,NaN,33.970474,5.182296,0.841278,1.848,√ò
2018-12-27 00:10:00,0.648644,-1.037384,0.520922,NaN,-3.859840,-0.333490,0.542782,-7.409,38.36279,0.694146,3.838215,0.449583,1.094819,0.664396,2.068958,1000.7770,-1.244958,0.695,-4.085,1.8,1.339207,99.99931,NaN,13.0,55.943656,5.693554,0.776569,2.105,N√ò
2018-12-28 00:10:00,0.458021,-1.520098,0.991158,NaN,-4.974732,-0.429817,1.719382,-12.720,57.93696,0.775146,3.810514,0.444639,1.082417,0.668576,2.049465,1005.8380,-6.232451,-4.125,-8.200,0.0,2.614267,98.92361,NaN,NaN,39.267257,2.795783,NaN,NaN,NaN
2018-12-29 00:10:00,0.879624,-0.617260,0.577520,NaN,-5.268014,-0.455156,0.613190,-11.050,46.90142,0.660903,3.759500,0.332375,1.023354,0.542597,1.984889,1003.8350,-4.474945,-1.800,-7.296,0.1,1.723672,99.43750,NaN,NaN,47.482347,5.616233,NaN,NaN,NaN
2018-12-30 00:10:00,0.476756,-0.901978,0.896532,NaN,-5.038892,-0.435360,1.807672,-11.050,58.87096,0.611986,3.728389,0.261771,0.933201,0.470632,1.911840,1009.3070,-3.461583,-1.738,-5.724,0.3,3.238451,99.72916,NaN,NaN,38.155978,2.973062,NaN,NaN,NaN
2018-12-31 22:10:00,0.605755,-1.960404,0.422131,NaN,-4.760121,-0.411274,0.454753,-2.048,24.69542,0.509465,3.673660,0.231160,0.871861,0.429556,1.876417,1002.8510,1.882986,4.524,-1.915,1.9,1.215902,99.46528,NaN,13.0,67.885875,7.418705,4.387930,10.200,S

## Behind the scenes of Pandas
A data frame is a collection of numpy arrays stored in an efficient manner. Accessing this array is sometimes useful, and we can therefore do that with the ``values`` attribute

In [22]:
weather.values

array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [0.8796244, -0.6172602, 0.5775197, ..., nan, nan, nan],
       [0.476756, -0.9019776, 0.8965321, ..., nan, nan, nan],
       [0.605755, -1.960404, 0.4221315, ..., 4.38793, 10.2, 'S']],
      dtype=object)

We won't focus much on numpy here, suffice to say, its working behind the scenes and it is highly efficient.

### Data transformations
To illustrate the usefulness of numpy, we will do som esimple data transformations.

Specifically, we want the amount of radiation, not percentages, as is stored in 'ir√∏d', 'uv' and 'synlig'

In [23]:
weather['uv_amount'] = weather['uv']*weather['global']/100
weather['ir_amount'] = weather['ir√∏d']*weather['global']/100
weather['visible_amount'] = weather['synlig']*weather['global']/100

In [24]:
weather.tail()

,albedo,balanse,diffus,fd,fluxm,fluxs,global,grmin,ir√∏d,jt010,jt100,jt002,jt020,jt005,jt050,lp,lt,ltmax,ltmin,nb,par,rf,sd,sdman,synlig,uv,vh,vhmax,vr,uv_amount,ir_amount,visible_amount
dato,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2018-12-27 00:10:00,0.648644,-1.037384,0.520922,NaN,-3.859840,-0.333490,0.542782,-7.409,38.36279,0.694146,3.838215,0.449583,1.094819,0.664396,2.068958,1000.777,-1.244958,0.695,-4.085,1.8,1.339207,99.99931,NaN,13.0,55.943656,5.693554,0.776569,2.105,N√ò,0.030904,0.208226,0.303652
2018-12-28 00:10:00,0.458021,-1.520098,0.991158,NaN,-4.974732,-0.429817,1.719382,-12.720,57.93696,0.775146,3.810514,0.444639,1.082417,0.668576,2.049465,1005.838,-6.232451,-4.125,-8.200,0.0,2.614267,98.92361,NaN,NaN,39.267257,2.795783,NaN,NaN,NaN,0.048070,0.996158,0.675154
2018-12-29 00:10:00,0.879624,-0.617260,0.577520,NaN,-5.268014,-0.455156,0.613190,-11.050,46.90142,0.660903,3.759500,0.332375,1.023354,0.542597,1.984889,1003.835,-4.474945,-1.800,-7.296,0.1,1.723672,99.43750,NaN,NaN,47.482347,5.616233,NaN,NaN,NaN,0.034438,0.287595,0.291157
2018-12-30 00:10:00,0.476756,-0.901978,0.896532,NaN,-5.038892,-0.435360,1.807672,-11.050,58.87096,0.611986,3.728389,0.261771,0.933201,0.470632,1.911840,1009.307,-3.461583,-1.738,-5.724,0.3,3.238451,99.72916,NaN,NaN,38.155978,2.973062,NaN,NaN,NaN,0.053743,1.064194,0.689735
2018-12-31 22:10:00,0.605755,-1.960404,0.422131,NaN,-4.760121,-0.411274,0.454753,-2.048,24.69542,0.509465,3.673660,0.231160,0.871861,0.429556,1.876417,1002.851,1.882986,4.524,-1.915,1.9,1.215902,99.46528,NaN,13.0,67.885875,7.418705,4.387930,10.200,S,0.033737,0.112303,0.308713

We can also use pandas to compute summary statistics, which is done with NumPy behind the scenes.

In [25]:
weather.mean()

albedo               0.334882
balanse              3.116438
diffus               4.158940
fd                   2.557109
fluxm                0.048990
fluxs                0.020836
global               9.157744
grmin               33.661247
ir√∏d                50.634207
jt010                7.280770
jt100                7.148726
jt002                7.233166
jt020                7.126354
jt005                7.242559
jt050                7.540423
lp                1000.022702
lt                   6.377937
ltmax               10.196489
ltmin                2.191760
nb                   2.703469
par                 20.525249
rf                  79.941759
sd                   2.168282
sdman                8.543985
synlig              43.691033
uv                   5.686159
vh                   2.710846
vhmax                5.576081
uv_amount            0.462978
ir_amount            4.775528
visible_amount       4.015093
dtype: float64

In [26]:
print("Standard deviation")
weather.std()

Standard deviation

albedo              0.225832
balanse             4.869500
diffus              3.289472
fd                  1.713003
fluxm              18.684980
fluxs               0.860714
global              8.231386
grmin             517.371215
ir√∏d                6.446930
jt010               6.691971
jt100               4.375169
jt002               7.070294
jt020               6.392470
jt005               6.871104
jt050               5.508264
lp                 12.446097
lt                  8.037329
ltmax               8.761555
ltmin               7.750335
nb                  6.084917
par                18.557807
rf                 14.589230
sd                  4.645082
sdman              11.983551
synlig              5.903798
uv                  1.231517
vh                  1.355322
vhmax               2.316607
uv_amount           0.387988
ir_amount           4.266682
visible_amount      3.622270
dtype: float64

In [27]:
print("Median")
weather.median()

Median

albedo               0.240000
balanse              1.403642
diffus               3.462354
fd                   2.394997
fluxm                0.256625
fluxs                0.021455
global               6.636849
grmin               -1.060000
ir√∏d                50.799770
jt010                6.606208
jt100                6.600000
jt002                6.400000
jt020                6.340927
jt005                6.697535
jt050                7.062048
lp                1000.527000
lt                   6.306361
ltmax               10.090000
ltmin                2.278000
nb                   0.100000
par                 14.928625
rf                  82.631599
sd                   0.000000
sdman                1.000000
synlig              43.884343
uv                   5.391731
vh                   2.446858
vhmax                5.287000
uv_amount            0.363645
ir_amount            3.491697
visible_amount       2.917559
dtype: float64

For a single column

In [28]:
weather['nb'].mean()

2.70346864161538

In [29]:

weather[['nb', 'ltmin']].mean()

nb       2.703469
ltmin    2.191760
dtype: float64

### Using numpy on data frames

We want to round our air temperature down to nearest integer.

In [30]:
rounded_temperature = weather['lt'].astype(int)

ValueError: Cannot convert non-finite values (NA or inf) to integer

Let us round the numbers down to nearest integer using NumPy

In [31]:
import numpy as np

In [32]:
np.floor(weather['lt'])

dato
1988-01-01 00:00:00    5.0
1988-01-02 00:00:00    3.0
1988-01-03 00:00:00    1.0
1988-01-04 00:00:00    0.0
1988-01-05 00:00:00   -1.0
1988-01-06 00:00:00   -1.0
1988-01-07 00:00:00   -2.0
1988-01-08 00:00:00   -7.0
1988-01-09 00:00:00    0.0
1988-01-10 00:00:00    4.0
1988-01-11 00:00:00    1.0
1988-01-12 00:00:00    0.0
1988-01-13 00:00:00    3.0
1988-01-14 00:00:00    3.0
1988-01-15 00:00:00    3.0
1988-01-16 00:00:00    0.0
1988-01-17 00:00:00    0.0
1988-01-18 00:00:00    1.0
1988-01-19 00:00:00    0.0
1988-01-20 00:00:00    1.0
1988-01-21 00:00:00    1.0
1988-01-22 00:00:00    2.0
1988-01-23 00:00:00    0.0
1988-01-24 00:00:00   -2.0
1988-01-25 00:00:00    0.0
1988-01-26 00:00:00   -1.0
1988-01-27 00:00:00    0.0
1988-01-28 00:00:00    0.0
1988-01-29 00:00:00   -1.0
1988-01-30 00:00:00   -4.0
                      ...
2018-12-02 00:10:00    4.0
2018-12-03 22:10:00    5.0
2018-12-04 00:10:00    3.0
2018-12-05 00:10:00   -3.0
2018-12-06 00:10:00   -3.0
2018-12-07 00:10:00   -1.0
2018-12-08 00:10:00   -1.0
2018-12-09 00:10:00   -3.0
2018-12-10 00:10:00    1.0
2018-12-11 00:10:00    0.0
2018-12-12 22:10:00   -7.0
2018-12-13 22:10:00   -6.0
2018-12-14 00:10:00   -8.0
2018-12-15 00:10:00   -6.0
2018-12-16 00:10:00   -1.0
2018-12-17 22:10:00   -4.0
2018-12-18 00:10:00   -5.0
2018-12-19 00:10:00   -1.0
2018-12-20 00:10:00    0.0
2018-12-21 22:10:00   -2.0
2018-12-22 00:10:00   -4.0
2018-12-23 00:10:00   -6.0
2018-12-24 00:10:00   -8.0
2018-12-25 00:10:00   -2.0
2018-12-26 00:10:00   -2.0
2018-12-27 00:10:00   -2.0
2018-12-28 00:10:00   -7.0
2018-12-29 00:10:00   -5.0
2018-12-30 00:10:00   -4.0
2018-12-31 22:10:00    1.0
Name: lt, Length: 11323, dtype: float64

Alternatively, we could remove all nan values before rounding.

In [33]:

print(len(weather['lt'].dropna()), len(weather['lt']))

10957 11323

In [34]:
weather['lt'].dropna().astype(int)

dato
1988-01-01 00:00:00    5
1988-01-02 00:00:00    3
1988-01-03 00:00:00    1
1988-01-04 00:00:00    0
1988-01-05 00:00:00    0
1988-01-06 00:00:00    0
1988-01-07 00:00:00   -1
1988-01-08 00:00:00   -6
1988-01-09 00:00:00    0
1988-01-10 00:00:00    4
1988-01-11 00:00:00    1
1988-01-12 00:00:00    0
1988-01-13 00:00:00    3
1988-01-14 00:00:00    3
1988-01-15 00:00:00    3
1988-01-16 00:00:00    0
1988-01-17 00:00:00    0
1988-01-18 00:00:00    1
1988-01-19 00:00:00    0
1988-01-20 00:00:00    1
1988-01-21 00:00:00    1
1988-01-22 00:00:00    2
1988-01-23 00:00:00    0
1988-01-24 00:00:00   -1
1988-01-25 00:00:00    0
1988-01-26 00:00:00    0
1988-01-27 00:00:00    0
1988-01-28 00:00:00    0
1988-01-29 00:00:00    0
1988-01-30 00:00:00   -3
                      ..
2018-12-02 00:10:00    4
2018-12-03 22:10:00    5
2018-12-04 00:10:00    3
2018-12-05 00:10:00   -2
2018-12-06 00:10:00   -2
2018-12-07 00:10:00    0
2018-12-08 00:10:00    0
2018-12-09 00:10:00   -2
2018-12-10 00:10:00    1
2018-12-11 00:10:00    0
2018-12-12 22:10:00   -6
2018-12-13 22:10:00   -5
2018-12-14 00:10:00   -7
2018-12-15 00:10:00   -5
2018-12-16 00:10:00    0
2018-12-17 22:10:00   -3
2018-12-18 00:10:00   -4
2018-12-19 00:10:00    0
2018-12-20 00:10:00    0
2018-12-21 22:10:00   -1
2018-12-22 00:10:00   -3
2018-12-23 00:10:00   -5
2018-12-24 00:10:00   -7
2018-12-25 00:10:00   -1
2018-12-26 00:10:00   -1
2018-12-27 00:10:00   -1
2018-12-28 00:10:00   -6
2018-12-29 00:10:00   -4
2018-12-30 00:10:00   -3
2018-12-31 22:10:00    1
Name: lt, Length: 10957, dtype: int32

In [35]:
weather['rounded_lt'] = weather['lt'].dropna().astype(int)
weather['rounded_lt']

dato
1988-01-01 00:00:00    5.0
1988-01-02 00:00:00    3.0
1988-01-03 00:00:00    1.0
1988-01-04 00:00:00    0.0
1988-01-05 00:00:00    0.0
1988-01-06 00:00:00    0.0
1988-01-07 00:00:00   -1.0
1988-01-08 00:00:00   -6.0
1988-01-09 00:00:00    0.0
1988-01-10 00:00:00    4.0
1988-01-11 00:00:00    1.0
1988-01-12 00:00:00    0.0
1988-01-13 00:00:00    3.0
1988-01-14 00:00:00    3.0
1988-01-15 00:00:00    3.0
1988-01-16 00:00:00    0.0
1988-01-17 00:00:00    0.0
1988-01-18 00:00:00    1.0
1988-01-19 00:00:00    0.0
1988-01-20 00:00:00    1.0
1988-01-21 00:00:00    1.0
1988-01-22 00:00:00    2.0
1988-01-23 00:00:00    0.0
1988-01-24 00:00:00   -1.0
1988-01-25 00:00:00    0.0
1988-01-26 00:00:00    0.0
1988-01-27 00:00:00    0.0
1988-01-28 00:00:00    0.0
1988-01-29 00:00:00    0.0
1988-01-30 00:00:00   -3.0
                      ...
2018-12-02 00:10:00    4.0
2018-12-03 22:10:00    5.0
2018-12-04 00:10:00    3.0
2018-12-05 00:10:00   -2.0
2018-12-06 00:10:00   -2.0
2018-12-07 00:10:00    0.0
2018-12-08 00:10:00    0.0
2018-12-09 00:10:00   -2.0
2018-12-10 00:10:00    1.0
2018-12-11 00:10:00    0.0
2018-12-12 22:10:00   -6.0
2018-12-13 22:10:00   -5.0
2018-12-14 00:10:00   -7.0
2018-12-15 00:10:00   -5.0
2018-12-16 00:10:00    0.0
2018-12-17 22:10:00   -3.0
2018-12-18 00:10:00   -4.0
2018-12-19 00:10:00    0.0
2018-12-20 00:10:00    0.0
2018-12-21 22:10:00   -1.0
2018-12-22 00:10:00   -3.0
2018-12-23 00:10:00   -5.0
2018-12-24 00:10:00   -7.0
2018-12-25 00:10:00   -1.0
2018-12-26 00:10:00   -1.0
2018-12-27 00:10:00   -1.0
2018-12-28 00:10:00   -6.0
2018-12-29 00:10:00   -4.0
2018-12-30 00:10:00   -3.0
2018-12-31 22:10:00    1.0
Name: rounded_lt, Length: 11323, dtype: float64

## Universal functions (numpy ufunc)

To round the data we first used the universal function ``np.floor``. A universal function is a function that is applied element-wise on an array (or data frame), yileding new array (or dataframe).

We can combine the numpy ufuncs to create new ufuncs that we might be interested in.

In this example, we will create a completely useless function that converts the temperature from Celsius to Kelvin before taking the logarithm.

In [36]:
def log_kelvin(temperature):
    return np.log(temperature + 273)

In [37]:
weather['log_kelvin_lt'] = log_kelvin(weather['lt'])

In [38]:
weather['log_kelvin_lt']

dato
1988-01-01 00:00:00    5.627981
1988-01-02 00:00:00    5.622934
1988-01-03 00:00:00    5.614222
1988-01-04 00:00:00    5.609838
1988-01-05 00:00:00    5.609105
1988-01-06 00:00:00    5.607639
1988-01-07 00:00:00    5.604699
1988-01-08 00:00:00    5.586499
1988-01-09 00:00:00    5.611302
1988-01-10 00:00:00    5.624739
1988-01-11 00:00:00    5.615680
1988-01-12 00:00:00    5.610204
1988-01-13 00:00:00    5.622572
1988-01-14 00:00:00    5.621125
1988-01-15 00:00:00    5.620763
1988-01-16 00:00:00    5.612033
1988-01-17 00:00:00    5.610936
1988-01-18 00:00:00    5.614222
1988-01-19 00:00:00    5.610936
1988-01-20 00:00:00    5.615680
1988-01-21 00:00:00    5.616407
1988-01-22 00:00:00    5.616771
1988-01-23 00:00:00    5.609472
1988-01-24 00:00:00    5.605434
1988-01-25 00:00:00    5.609472
1988-01-26 00:00:00    5.607272
1988-01-27 00:00:00    5.610570
1988-01-28 00:00:00    5.610570
1988-01-29 00:00:00    5.606170
1988-01-30 00:00:00    5.597310
                         ...
2018-12-02 00:10:00    5.624815
2018-12-03 22:10:00    5.630409
2018-12-04 00:10:00    5.620450
2018-12-05 00:10:00    5.601696
2018-12-06 00:10:00    5.601609
2018-12-07 00:10:00    5.608721
2018-12-08 00:10:00    5.607466
2018-12-09 00:10:00    5.599622
2018-12-10 00:10:00    5.613702
2018-12-11 00:10:00    5.612248
2018-12-12 22:10:00    5.587128
2018-12-13 22:10:00    5.589262
2018-12-14 00:10:00    5.581427
2018-12-15 00:10:00    5.588644
2018-12-16 00:10:00    5.607618
2018-12-17 22:10:00    5.598042
2018-12-18 00:10:00    5.594100
2018-12-19 00:10:00    5.609414
2018-12-20 00:10:00    5.613069
2018-12-21 22:10:00    5.605566
2018-12-22 00:10:00    5.597308
2018-12-23 00:10:00    5.589613
2018-12-24 00:10:00    5.580211
2018-12-25 00:10:00    5.605500
2018-12-26 00:10:00    5.604402
2018-12-27 00:10:00    5.604901
2018-12-28 00:10:00    5.586378
2018-12-29 00:10:00    5.592944
2018-12-30 00:10:00    5.596711
2018-12-31 22:10:00    5.616346
Name: log_kelvin_lt, Length: 11323, dtype: float64

## Advanced indexing with groupby

We want to look whether the summary statistics for the dataset vary across the different seasons. To do this, we start by adding a month column to the DataFrame.

In [39]:
weather['month'] = weather.index.month

In [40]:
weather['month']

dato
1988-01-01 00:00:00     1
1988-01-02 00:00:00     1
1988-01-03 00:00:00     1
1988-01-04 00:00:00     1
1988-01-05 00:00:00     1
1988-01-06 00:00:00     1
1988-01-07 00:00:00     1
1988-01-08 00:00:00     1
1988-01-09 00:00:00     1
1988-01-10 00:00:00     1
1988-01-11 00:00:00     1
1988-01-12 00:00:00     1
1988-01-13 00:00:00     1
1988-01-14 00:00:00     1
1988-01-15 00:00:00     1
1988-01-16 00:00:00     1
1988-01-17 00:00:00     1
1988-01-18 00:00:00     1
1988-01-19 00:00:00     1
1988-01-20 00:00:00     1
1988-01-21 00:00:00     1
1988-01-22 00:00:00     1
1988-01-23 00:00:00     1
1988-01-24 00:00:00     1
1988-01-25 00:00:00     1
1988-01-26 00:00:00     1
1988-01-27 00:00:00     1
1988-01-28 00:00:00     1
1988-01-29 00:00:00     1
1988-01-30 00:00:00     1
                       ..
2018-12-02 00:10:00    12
2018-12-03 22:10:00    12
2018-12-04 00:10:00    12
2018-12-05 00:10:00    12
2018-12-06 00:10:00    12
2018-12-07 00:10:00    12
2018-12-08 00:10:00    12
2018-12-09 00:10:00    12
2018-12-10 00:10:00    12
2018-12-11 00:10:00    12
2018-12-12 22:10:00    12
2018-12-13 22:10:00    12
2018-12-14 00:10:00    12
2018-12-15 00:10:00    12
2018-12-16 00:10:00    12
2018-12-17 22:10:00    12
2018-12-18 00:10:00    12
2018-12-19 00:10:00    12
2018-12-20 00:10:00    12
2018-12-21 22:10:00    12
2018-12-22 00:10:00    12
2018-12-23 00:10:00    12
2018-12-24 00:10:00    12
2018-12-25 00:10:00    12
2018-12-26 00:10:00    12
2018-12-27 00:10:00    12
2018-12-28 00:10:00    12
2018-12-29 00:10:00    12
2018-12-30 00:10:00    12
2018-12-31 22:10:00    12
Name: month, Length: 11323, dtype: int64

In [41]:
weather.groupby(weather['month'])

When we group by ``weather['month']``, we separate the weather data frame into twelve new dataframes. Each row in ``weather``, whose corresponding row in ``weather['month']`` is equal to 1 is placed in the first data frame. Similarly,  the rows in ``weather`` that match up with the rows where ``weather['month']`` is equal to two, are placed in the secon data frame.

In [42]:
weather.groupby(weather['month']).mean()

,albedo,balanse,diffus,fd,fluxm,fluxs,global,grmin,ir√∏d,jt010,jt100,jt002,jt020,jt005,jt050,lp,lt,ltmax,ltmin,nb,par,rf,sd,sdman,synlig,uv,vh,vhmax,uv_amount,ir_amount,visible_amount,rounded_lt,log_kelvin_lt
month,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,0.576290,-1.327403,0.807633,NaN,-3.197319,-0.275320,1.147371,-9.324145,50.737009,-0.103263,2.708579,-0.472967,0.242851,-0.422143,1.516468,998.426378,-2.648489,0.039490,-5.636071,2.652294,2.356126,88.667176,6.017857,8.927273,42.588789,6.663097,2.673763,5.430006,0.069039,0.613216,0.463400,-2.525806,5.599527
2,0.585779,-0.994159,2.023248,NaN,-2.586172,-0.222870,3.288178,-9.515172,51.067871,-0.303540,2.083003,-0.665687,-0.062679,-0.589772,1.224957,998.982206,-2.326450,0.898955,-5.746568,2.221637,7.096589,84.750212,3.998246,16.830000,42.810643,6.102609,2.726839,5.423426,0.183090,1.761076,1.344570,-2.206368,5.600741
3,0.473343,0.861134,3.825906,NaN,-0.160723,-0.013715,7.906774,-8.326237,51.012467,0.320577,1.873289,0.039998,0.347081,0.180215,1.271347,1000.416952,0.663428,4.751788,-3.503341,1.704707,17.323149,77.072037,4.187931,15.523810,43.560902,5.487687,2.762913,5.740201,0.397194,4.187327,3.310596,0.540366,5.611798
4,0.260724,4.605714,5.826006,NaN,4.560446,0.392995,12.185827,-3.878684,50.770781,4.011935,2.854604,4.240446,3.674601,4.248816,3.337575,1001.800937,5.274515,9.836783,0.632758,2.034570,26.856941,73.584072,0.086667,4.765789,44.014357,5.214600,2.820466,5.819732,0.589585,6.358593,5.238843,4.825556,5.628546
5,0.234172,7.965406,7.381541,2.841231,6.653774,0.574755,17.890620,0.319297,50.747468,10.094823,6.227333,10.492027,9.508806,10.332636,8.185120,1002.121939,10.849306,15.694901,5.470263,1.891663,39.828232,68.168495,0.096774,0.150000,44.162120,5.097060,2.916147,6.115052,0.873838,9.227209,7.837405,10.364516,5.648367
6,0.224904,9.164776,8.159775,3.387248,6.356127,0.548929,19.563571,4.734269,50.336732,14.417567,9.774996,14.860073,13.837226,14.635050,12.348497,1000.054751,14.569947,19.025925,9.413918,2.624761,44.391928,69.907581,0.000000,NaN,44.405287,5.224943,2.844272,5.890922,0.985658,9.949662,8.690347,14.094444,5.661419
7,0.218341,9.016934,7.935507,3.524832,4.533191,0.390244,18.375615,7.632463,49.818423,17.016289,12.529080,17.746668,16.438869,17.193734,15.101972,999.718365,16.826548,21.329823,11.719114,2.797679,42.118644,74.654198,0.000000,NaN,44.865845,5.318069,2.648819,5.609593,0.938762,9.259180,8.227459,16.358065,5.669246
8,0.225253,6.577065,6.342983,2.559505,0.210065,0.198356,14.223156,-10.249343,50.122659,16.323914,13.702338,16.794489,16.032941,16.315127,15.482797,1000.275075,15.636469,20.224859,10.696004,3.511639,32.780529,78.000755,0.000000,NaN,44.510271,5.347937,2.562693,5.458456,0.729857,7.176087,6.237385,15.138710,5.665130
9,0.235592,2.933991,4.097570,1.616527,-1.579586,-0.129463,8.968385,370.747622,50.695325,12.590957,12.628203,12.702697,12.640561,12.523064,13.039788,1001.538903,11.520368,15.805335,6.879758,3.024179,20.500809,80.480487,0.000000,NaN,43.880664,5.431517,2.641628,5.425961,0.457779,4.666077,3.866958,11.044444,5.650755
10,0.241506,0.190386,2.164501,0.989414,-4.405676,-0.379122,3.940239,79.309161,50.607849,7.556540,9.984979,7.385467,8.026256,7.324187,9.285327,1000.186887,6.132303,9.478480,2.505058,3.662703,8.807080,84.965400,0.000000,4.000000,43.640882,5.753758,2.625996,5.239594,0.203910,2.090324,1.644218,5.708602,5.631597
11,0.320631,-1.094317,0.944422,0.000000,-5.084117,-0.439323,1.411056,-4.299427,50.948877,3.168577,6.717228,2.956102,3.624933,2.870800,5.338126,998.492711,1.572713,4.084258,-1.360142,3.556695,3.012742,89.119761,1.289474,1.013953,42.900280,6.209988,2.713606,5.231757,0.076386,0.765346,0.562289,1.427778,5.615092
12,0.471917,-1.354443,0.544837,0.000000,-4.845287,-0.418902,0.730623,-8.556184,50.792585,0.698567,4.204406,0.317610,1.121059,0.345806,2.825331,998.340526,-2.069497,0.571923,-5.264557,2.665098,1.432716,89.966217,3.935484,8.621622,42.845689,6.393451,2.599228,5.499084,0.042002,0.399281,0.300864,-1.930108,5.601658

We can also group by multiple variables, let us group by year and month.

In [43]:
weather['year'] = weather.index.year

In [44]:
weather.groupby([weather['year'], weather['month']]).mean()

              albedo    balanse     diffus        fd      fluxm     fluxs  \
year month
1988 1           NaN        NaN        NaN       NaN        NaN       NaN
     2           NaN        NaN        NaN       NaN        NaN       NaN
     3           NaN        NaN        NaN       NaN        NaN       NaN
     4           NaN        NaN        NaN       NaN        NaN       NaN
     5      0.240800   8.972400   6.001200       NaN        NaN       NaN
     6      0.231111   9.830741   6.357037       NaN        NaN       NaN
     7      0.223000   7.185333   7.032333       NaN        NaN       NaN
     8      0.238276   5.867241   5.084483       NaN        NaN       NaN
     9      0.243333   2.356296   3.377692       NaN        NaN       NaN
     10     0.288077  -0.610385   2.074231       NaN        NaN       NaN
     11     0.423000  -2.425333   1.146667       NaN        NaN       NaN
     12     0.735333  -1.880667   0.515667       NaN        NaN       NaN
1989 1      0.225172  -2.721034   0.817931       NaN        NaN       NaN
     2      0.265556  -1.368148   1.619630       NaN        NaN       NaN
     3      0.223226   1.420645   3.434194       NaN        NaN       NaN
     4      0.216000   3.463667   5.084667       NaN        NaN       NaN
     5      0.254516   7.369677   5.761290       NaN        NaN       NaN
     6      0.247500   9.671786   6.675000       NaN        NaN       NaN
     7      0.233214   8.355357   6.732500       NaN        NaN       NaN
     8      0.246207   4.975517   5.820345       NaN        NaN       NaN
     9      0.260714   2.839286   2.985000       NaN        NaN       NaN
     10          NaN  -1.781034   1.524138       NaN        NaN       NaN
     11     0.275455  -2.329091   0.758182       NaN        NaN       NaN
     12     0.400968  -2.010323   0.457742       NaN        NaN       NaN
1990 1      0.342903  -1.817419   0.647742       NaN        NaN       NaN
     2      0.213077  -0.746923   1.243077       NaN        NaN       NaN
     3      0.280690   0.972414   3.045172       NaN        NaN       NaN
     4      0.255714   4.271429   7.099286       NaN        NaN       NaN
     5      0.255484   8.458710   8.279032       NaN        NaN       NaN
     6      0.226000   7.964483   8.194800       NaN        NaN       NaN
...              ...        ...        ...       ...        ...       ...
2016 7      0.219608   8.760595  11.044307       NaN   4.812296  0.415782
     8      0.232123   5.362952   7.618797       NaN   1.436022  0.124072
     9      0.242359   2.687009   5.271522       NaN   0.457797  0.039554
     10     0.239483  -0.470490   2.050566       NaN  -5.335233 -0.460964
     11     0.328145  -1.786588   1.282482       NaN  -6.038246 -0.521704
     12     0.238223  -2.055584   0.709503       NaN  -4.566007 -0.394503
2017 1      0.273643  -1.741463   0.905419       NaN  -3.826894 -0.330644
     2      0.608297  -1.027885   2.261545       NaN  -2.075670 -0.179338
     3      0.308784   1.282314   4.244221       NaN  -0.089608 -0.007742
     4      0.249136   4.094198   8.499720       NaN   1.619920  0.139961
     5      0.230421   6.629230   9.055980  3.466667   6.686611  0.577723
     6      0.217196   8.097596   9.577506  3.679310   5.313374  0.459075
     7      0.223415   8.618810  10.345582  4.093548   4.771629  0.412269
     8      0.222929   5.402878   8.132749  2.924645   2.317100  0.200197
     9      0.230391   1.276886   5.348603  1.665200  -0.664603 -0.057422
     10     0.247620  -0.712104   3.408103  1.369690 -11.055601 -0.955204
     11     0.388057  -2.280462   1.303748       NaN  -7.483098 -0.646540
     12     0.566657  -1.653746   0.814956       NaN  -3.193061 -0.275881
2018 1      0.704478  -1.508288   1.000068       NaN  -1.941205 -0.167720
     2      0.756667  -1.485366   2.708390       NaN  -1.804921 -0.155945
     3      0.719597  -1.322930   5.268509       NaN  -1.551799 -0.134075
     4      0.345246   3.995996   6.560670       NaN   3.701229  0.319786
     5      0.230545   9.013674   8.370875  4.320679  12.459105  1.076467
     6      0.216661  10.105925   9.416289  5.806667   7.620137  0.658380
     7      0.203536  10.660636   8.634094  6.593548   8.536547  0.737558
     8      0.196231   5.468839   7.956325  3.738710   0.276122  0.023857
     9      0.214717   2.106218   5.245420  2.570000  -3.149628 -0.272128
     10     0.238793  -0.365834   2.768081  0.704762  -6.248281 -0.539851
     11     0.203602  -1.047731   1.159144       NaN  -5.910428 -0.510661
     12     0.668381  -1.243333   0.653213       NaN  -4.588814 -0.396474

               global      grmin       ir√∏d      jt010      jt100      jt002  \
year month
1988 1            NaN        NaN        NaN        NaN        NaN        NaN
     2            NaN        NaN        NaN        NaN        NaN        NaN
     3            NaN        NaN        NaN        NaN        NaN        NaN
     4            NaN        NaN        NaN        NaN        NaN        NaN
     5      19.720400        NaN  50.420000  12.008000   6.860000        NaN
     6      20.712593        NaN  50.337037  16.896296  10.467857        NaN
     7      14.866333        NaN  50.540000  16.513333  12.753333        NaN
     8      13.526552        NaN  50.924138  15.175862  12.751724        NaN
     9       8.457037        NaN  50.729630  12.328000  11.800000        NaN
     10      3.493462        NaN  51.919231   5.948148   8.629630        NaN
     11      1.798000        NaN  54.553333   0.223333   4.203333        NaN
     12      0.803000        NaN  51.463333  -0.603333   2.176667        NaN
1989 1       1.238621        NaN  55.706897  -0.524138   1.403226        NaN
     2       2.812963        NaN  53.907407   0.364286   1.375000        NaN
     3       5.788065        NaN  50.570968   2.351613   1.983871        NaN
     4       9.508000        NaN  50.753333   4.620000   3.410000        NaN
     5      18.581290        NaN  52.035484   9.354839   6.116129        NaN
     6      20.944643        NaN  51.532143  13.185714   9.010714        NaN
     7      18.133571        NaN  50.546429  15.425000  11.739286        NaN
     8      11.984483        NaN  50.444828  14.265517  12.337931        NaN
     9       9.186071        NaN  51.850000  11.385714  11.082143        NaN
     10      4.203793        NaN        NaN        NaN        NaN        NaN
     11      1.333636        NaN  50.754545   3.359091   6.200000        NaN
     12      0.707742        NaN  49.451613  -0.819355   2.735484        NaN
1990 1       0.901613        NaN  50.900000  -0.500000   1.387097        NaN
     2       1.672308        NaN  49.338462   1.084615   1.300000        NaN
     3       7.545172        NaN  53.148276   2.493103   2.358621        NaN
     4      11.671786        NaN  52.607143   5.496429   3.989286        NaN
     5      19.874839        NaN  53.635484  10.377419   7.093548        NaN
     6      17.147333        NaN  51.736667  13.600000   9.589655        NaN
...               ...        ...        ...        ...        ...        ...
2016 7      19.652169   6.931839  47.294924  17.090054  12.832294  17.729072
     8      14.641105   5.792129  46.718384  15.700502  13.531286  16.004883
     9      10.554054   3.990767  47.758733  14.605387  13.305083  14.772602
     10      4.129014  -0.868581  46.990075   7.436224  10.416787   7.014595
     11      1.660038  -6.234133  49.345975   2.576328   6.669142   2.077913
     12      0.893656  -6.381742  49.184195   0.204835   4.021860  -0.150705
2017 1       1.300772  -8.224548  48.897107  -0.339408   2.685637  -0.702853
     2       3.575744  -7.279429  46.197657  -0.367898   2.035062  -0.506069
     3       7.991870  -4.795387  47.976750  -0.239047   1.683853  -0.174131
     4      14.065926  -5.860133  47.836346   3.620961   3.124707   3.980804
     5      17.146469   0.736065  46.481208   9.165236   5.705695   9.891351
     6      19.649584   5.343233  46.150257  14.091077   9.827467  14.725262
     7      20.430993   5.786677  46.808785  15.705910  12.002618  16.307231
     8      15.384474   5.852355  46.844001  15.506438  12.964693  15.889375
     9       7.072249   5.193800  44.705422  12.924322  12.457954  12.966674
     10      4.674338  -0.889742  49.510969   7.771880  10.107360   7.429156
     11      2.148998  -6.268200  52.262972   2.377675   6.432201   1.906889
     12      0.869214  -9.071903  44.720191   0.309234   3.692640   0.038692
2018 1       1.059359  -8.401161  44.687227  -0.063091   2.580788  -0.223880
     2       3.735215 -10.651821  46.873048  -0.206378   2.056982  -0.353070
     3       9.467900 -12.262839  47.189376  -0.340456   1.725947  -0.456385
     4      14.512068  -4.308700  46.266562   1.655025   1.878062   2.089192
     5      23.010046   1.460484  47.706569  11.537924   6.514195  12.476347
     6      24.626828   5.848233  47.410984  15.495124  10.732889  16.263080
     7      24.097960   7.993645  46.912427  18.168179  13.197987  19.049959
     8      14.931245   4.617710  46.726319  15.879534  13.931620  16.084675
     9       9.860936   3.134000  48.327016  12.550455  12.611535  12.459936
     10      5.062992  -2.497677  49.654447   7.791625  10.062614   7.357515
     11      1.270950  -2.466333  47.195626   4.822615   7.565684   4.403387
     12      0.796074  -7.879613  45.140034   1.284619   4.489807   0.741258

                jt020      jt005      jt050           lp         lt  \
year month
1988 1            NaN        NaN        NaN          NaN   0.577419
     2            NaN        NaN        NaN          NaN  -1.544828
     3            NaN        NaN        NaN          NaN  -2.356667
     4            NaN        NaN        NaN          NaN   2.110000
     5      11.496000  12.232000   9.512000          NaN  12.187097
     6      16.340741  17.162963  13.985714          NaN  17.683333
     7      16.200000  16.306667  15.313333          NaN  15.758065
     8      14.937931  14.806897  14.437931          NaN  14.535484
     9      12.212000  11.540000  12.628000          NaN  11.750000
     10      6.066667   4.637037   7.711111          NaN   4.458065
     11      0.353333  -0.896667   2.253333          NaN  -2.243333
     12     -0.543333  -1.500000   0.833333          NaN  -3.280645
1989 1      -0.567742  -1.244828   0.506452          NaN   2.754839
     2       0.260714  -0.242857   0.942857          NaN   2.614286
     3       2.151613   1.887097   2.261290          NaN   3.283871
     4       4.396667   4.236667   4.260000          NaN   4.573333
     5       9.029032   9.238710   8.090323          NaN  10.603226
     6      12.789286  13.282143  11.496429          NaN  14.463333
     7      15.060714  15.435714  14.046429          NaN  16.087097
     8      14.051724  13.924138  13.855172          NaN  13.570968
     9      11.267857  10.814286  11.646429          NaN  10.706667
     10           NaN        NaN        NaN          NaN   6.293548
     11      3.500000   2.263636   5.100000          NaN   1.820000
     12     -0.677419  -1.980645   0.983871          NaN  -2.864516
1990 1      -0.532258  -1.238710   0.458065          NaN   1.312903
     2       1.015385   0.707692   1.123077          NaN   3.550000
     3       2.351724   1.979310   2.510345          NaN   4.596774
     4       5.267857   5.164286   4.921429          NaN   6.373333
     5       9.974194  10.316129   9.058065          NaN  11.851613
     6      13.134483  13.631034  11.910345          NaN  14.573333
...               ...        ...        ...          ...        ...
2016 7      16.578486  17.560577  15.076135   998.049526  16.482642
     8      15.530784  15.987056  14.824960  1000.005668  14.906185
     9      14.549102  14.828676  14.117773  1003.115717  14.418778
     10      7.994876   7.339060   9.096426  1015.898142   5.578512
     11      3.221579   2.437317   4.607155   999.608583   0.547338
     12      0.734209   0.140392   1.949444  1003.935868   0.787770
2017 1       0.101325  -0.389966   1.013625  1002.960126  -1.321210
     2      -0.053941  -0.318531   0.645335  1003.412971  -1.868429
     3       0.002038  -0.108780   0.541026   997.950252   2.167789
     4       3.477486   3.915559   3.164653   999.917570   4.671407
     5       8.571944   9.660158   7.146142  1005.805755  11.125230
     6      13.564191  14.526975  12.036794   996.061630  14.540294
     7      15.244825  16.118947  13.912473   998.131523  16.212180
     8      15.242929  15.832008  14.363889   999.072123  14.733640
     9      12.995056  13.072024  10.478753  1002.603740  11.657505
     10      8.243667   7.717735   9.099338   997.395666   6.867135
     11      3.002240   2.256892   4.351032   991.862597   1.408590
     12      0.755190   0.280634   1.788993   988.243665  -1.934525
2018 1       0.272923  -0.032589   1.046826   995.286197  -2.242236
     2       0.084123  -0.175992   0.730422  1008.600250  -4.618707
     3      -0.061644  -0.305243   0.521653  1000.202732  -3.454439
     4       1.547896   1.944217   1.431670  1000.348543   5.329019
     5      10.735736  12.136369   8.799808  1008.673961  15.259366
     6      14.875673  15.999995  13.169085  1001.253707  16.992781
     7      17.487285  18.736279  15.700444  1002.960765  20.544472
     8      15.733412  16.097785  15.128632   999.411839  15.621896
     9      12.679791  12.610105  12.778881   999.552967  12.311987
     10      8.190925   7.645368   9.035024  1000.178916   6.937797
     11      5.198988   4.672397   6.128296  1009.284230   3.154925
     12      1.471351   0.970264   2.512676  1000.917535  -1.698744

                ltmax      ltmin        nb        par         rf        sd  \
year month
1988 1       1.706452  -0.845161  6.290476        NaN        NaN       NaN
     2       0.624138  -4.200000  3.914286        NaN        NaN       NaN
     3       1.090000  -6.343333  3.826087        NaN        NaN       NaN
     4       6.066667  -2.036667  1.539130        NaN        NaN       NaN
     5      16.941935   7.845161  1.240000        NaN  60.000000       NaN
     6      23.276667  11.853333  1.493333  59.160000  65.785714       NaN
     7      19.512903  11.661290  5.341935  39.220000  78.033333       NaN
     8      18.948387   9.887097  5.861290  35.696897  77.137931       NaN
     9      16.033333   7.540000  2.876667  20.477037  76.160000       NaN
     10      7.754839   0.990323  3.986957   7.970385  83.629630       NaN
     11      1.506667  -6.023333  0.968182   3.854333  82.700000       NaN
     12      0.429032  -8.251613  1.121739   1.179000  84.233333       NaN
1989 1       5.429032  -0.561290  0.418519   2.190000  79.190323       NaN
     2       4.985714  -0.200000  2.895000   5.902963  78.117857       NaN
     3       6.461290   0.238710  4.575000  13.122258  81.167742       NaN
     4       8.133333   0.433333  3.312500  21.742333  73.423333       NaN
     5      15.609677   4.774194  0.651852  43.630645  60.158065       NaN
     6      19.300000   8.463333  2.745833  49.733929  65.432143       NaN
     7      21.745161   9.993548  2.437037  43.169643  64.371429       NaN
     8      18.183871   9.009677  5.556522  28.325862  76.593103       NaN
     9      15.683333   5.736667  2.313636  21.453571  78.735714       NaN
     10           NaN        NaN  2.691304        NaN  81.220690       NaN
     11      4.710000  -0.890000  3.037500   2.409545  82.627273       NaN
     12      0.283871  -6.538710  1.633333   0.863548  85.480645       NaN
1990 1       3.322581  -1.129032  4.104348   1.369032  85.022581       NaN
     2       5.657143   1.707143  6.920000   3.150769  87.707692       NaN
     3       8.667742   0.906452  0.703448  17.198621  68.582759       NaN
     4      10.836667   1.603333  2.888000  27.091071  70.628571       NaN
     5      17.483871   5.461290  0.400000  46.296129  60.058065       NaN
     6      18.986667   9.576667  4.480952  40.081333  68.820690       NaN
...               ...        ...       ...        ...        ...       ...
2016 7      20.841935  11.842935  1.716129  46.638548  79.031735       NaN
     8      19.122903  10.460645  4.345161  34.634558  81.545280       NaN
     9      18.847667   9.787833  1.240000  24.717568  82.944998       NaN
     10      8.435194   2.548968  1.025806   9.443530  80.813575       NaN
     11      3.115200  -2.474967  2.400000   3.724252  86.135737  1.250000
     12      3.670968  -2.357516  0.822581   1.820102  88.731588       NaN
2017 1       1.604742  -4.450581  1.967742   2.673057  89.300722  0.000000
     2       0.739107  -4.837393  2.575000   8.162283  88.698161  6.460714
     3       5.948419  -1.478774  1.406452  18.355857  79.561990  1.222581
     4       9.335367  -0.276500  1.123333  32.538106  70.832986  0.086667
     5      15.567839   6.122000  2.254839  40.602695  73.683139  0.096774
     6      18.505333  10.050833  3.083333  46.920710  72.488046  0.000000
     7      20.789032  11.129161  1.432258  48.642446  70.825048  0.000000
     8      18.832581  10.702677  4.248387  36.950464  81.739215  0.000000
     9      14.672667   8.866633  4.006667  17.142112  86.843125  0.000000
     10     10.762290   3.049161  4.454839  10.740695  83.430881  0.000000
     11      4.628933  -2.246433  3.393333   4.670737  89.101392  1.300000
     12      0.903355  -5.625516  2.341935   1.745946  92.660790  3.935484
2018 1       0.006613  -5.384452  3.006452   2.454890  94.835545       NaN
     2      -2.320071  -7.614286  1.564286   8.828382  84.612383       NaN
     3       0.554645  -7.948968  0.748387  21.998753  68.663190       NaN
     4      10.451333   0.172433  1.073333  34.073683  73.521368       NaN
     5      21.399194   8.174677  0.977419  53.984315  64.475974       NaN
     6      21.985333  11.422100  2.860000  59.027742  62.494384       NaN
     7      26.295806  13.969677  1.635484  58.396721  65.675934       NaN
     8      20.053871  10.840129  1.441935  35.987214  76.712291       NaN
     9      16.337667   8.204000  4.023333  23.862330  77.921020       NaN
     10     10.624935   2.876032  1.422581  11.762298  84.887012       NaN
     11      5.212100   0.808967  4.506667   2.788651  95.057384       NaN
     12      0.398258  -4.480806  2.058065   1.665585  93.765815       NaN

                sdman     synlig        uv        vh      vhmax  uv_amount  \
year month
1988 1            NaN        NaN       NaN       NaN        NaN        NaN
     2            NaN        NaN       NaN       NaN        NaN        NaN
     3            NaN        NaN       NaN       NaN        NaN        NaN
     4            NaN        NaN       NaN       NaN        NaN        NaN
     5            NaN  44.336000  5.244000       NaN        NaN   1.022780
     6            NaN  44.140741  5.522222  2.528571   6.076923   1.117751
     7            NaN  43.486667  5.973333  3.343333   6.906667   0.860646
     8            NaN  43.241379  5.834483  2.668966   6.113793   0.758037
     9            NaN  43.503704  5.766667  3.016000   6.732000   0.458759
     10           NaN  42.030769  6.050000  2.211111   5.359259   0.194390
     11           NaN  39.646667  5.800000  2.013333   4.610000   0.097979
     12           NaN  41.803333  6.733333  2.163333   5.506667   0.050305
1989 1            NaN  38.620690  5.672414  3.887097   7.987097   0.067763
     2            NaN  40.162963  5.929630  3.914286   7.957143   0.152494
     3            NaN  43.200000  6.229032  3.190323   6.758065   0.327246
     4            NaN  43.150000  6.096667  2.683333   6.173333   0.527897
     5            NaN  42.403226  5.561290  3.564516   7.529032   1.001601
     6            NaN  42.725000  5.742857  3.078571   7.028571   1.183515
     7            NaN  43.635714  5.817857  3.007143   6.600000   1.021952
     8            NaN  43.500000  6.055172  2.855172   6.196552   0.696238
     9            NaN  42.332143  5.817857  2.471429   5.832143   0.503150

### This is not the best way to group data if you are grouping by time.

We want to use the pandas Grouper object

In [46]:
weather.groupby(pd.Grouper(freq='M')).mean()

,albedo,balanse,diffus,fd,fluxm,fluxs,global,grmin,ir√∏d,jt010,jt100,jt002,jt020,jt005,jt050,lp,lt,ltmax,ltmin,nb,par,rf,sd,sdman,synlig,uv,vh,vhmax,uv_amount,ir_amount,visible_amount,rounded_lt,log_kelvin_lt,month,year
dato,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1988-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.577419,1.706452,-0.845161,6.290476,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.451613,5.611549,1,1988
1988-02-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.544828,0.624138,-4.200000,3.914286,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.517241,5.603731,2,1988
1988-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.356667,1.090000,-6.343333,3.826087,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.100000,5.600743,3,1988
1988-04-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.110000,6.066667,-2.036667,1.539130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.800000,5.617152,4,1988
1988-05-31,0.240800,8.972400,6.001200,NaN,NaN,NaN,19.720400,NaN,50.420000,12.008000,6.860000,NaN,11.496000,12.232000,9.512000,NaN,12.187097,16.941935,7.845161,1.240000,NaN,60.000000,NaN,NaN,44.336000,5.244000,NaN,NaN,1.022780,9.974430,8.723190,11.774194,5.653051,5,1988
1988-06-30,0.231111,9.830741,6.357037,NaN,NaN,NaN,20.712593,NaN,50.337037,16.896296,10.467857,NaN,16.340741,17.162963,13.985714,NaN,17.683333,23.276667,11.853333,1.493333,59.160000,65.785714,NaN,NaN,44.140741,5.522222,2.528571,6.076923,1.117751,10.491773,9.103068,17.333333,5.672171,6,1988
1988-07-31,0.223000,7.185333,7.032333,NaN,NaN,NaN,14.866333,NaN,50.540000,16.513333,12.753333,NaN,16.200000,16.306667,15.313333,NaN,15.758065,19.512903,11.661290,5.341935,39.220000,78.033333,NaN,NaN,43.486667,5.973333,3.343333,6.906667,0.860646,7.611202,6.394486,15.354839,5.665575,7,1988
1988-08-31,0.238276,5.867241,5.084483,NaN,NaN,NaN,13.526552,NaN,50.924138,15.175862,12.751724,NaN,14.937931,14.806897,14.437931,NaN,14.535484,18.948387,9.887097,5.861290,35.696897,77.137931,NaN,NaN,43.241379,5.834483,2.668966,6.113793,0.758037,6.956256,5.812259,14.064516,5.661325,8,1988
1988-09-30,0.243333,2.356296,3.377692,NaN,NaN,NaN,8.457037,NaN,50.729630,12.328000,11.800000,NaN,12.212000,11.540000,12.628000,NaN,11.750000,16.033333,7.540000,2.876667,20.477037,76.160000,NaN,NaN,43.503704,5.766667,3.016000,6.732000,0.458759,4.394964,3.603313,11.333333,5.651594,9,1988
1988-10-31,0.288077,-0.610385,2.074231,NaN,NaN,NaN,3.493462,NaN,51.919231,5.948148,8.629630,NaN,6.066667,4.637037,7.711111,NaN,4.458065,7.754839,0.990323,3.986957,7.970385,83.629630,NaN,NaN,42.030769,6.050000,2.211111,5.359259,0.194390,1.878518,1.420553,4.193548,5.625578,10,1988
1988-11-30,0.423000,-2.425333,1.146667,NaN,NaN,NaN,1.798000,NaN,54.553333,0.223333,4.203333,NaN,0.353333,-0.896667,2.253333,NaN,-2.243333,1.506667,-6.023333,0.968182,3.854333,82.700000,NaN,NaN,39.646667,5.800000,2.013333,4.610000,0.097979,1.008521,0.691500,-2.033333,5.601066,11,1988
1988-12-31,0.735333,-1.880667,0.515667,NaN,NaN,NaN,0.803000,NaN,51.463333,-0.603333,2.176667,NaN,-0.543333,-1.500000,0.833333,NaN,-3.280645,0.429032,-8.251613,1.121739,1.179000,84.233333,NaN,NaN,41.803333,6.733333,2.163333,5.506667,0.050305,0.424068,0.328627,-3.129032,5.597203,12,1988
1989-01-31,0.225172,-2.721034,0.817931,NaN,NaN,NaN,1.238621,NaN,55.706897,-0.524138,1.403226,NaN,-0.567742,-1.244828,0.506452,NaN,2.754839,5.429032,-0.561290,0.418519,2.190000,79.190323,NaN,NaN,38.620690,5.672414,3.887097,7.987097,0.067763,0.702624,0.468233,2.483871,5.619454,1,1989
1989-02-28,0.265556,-1.368148,1.619630,NaN,NaN,NaN,2.812963,NaN,53.907407,0.364286,1.375000,NaN,0.260714,-0.242857,0.942857,NaN,2.614286,4.985714,-0.200000,2.895000,5.902963,78.117857,NaN,NaN,40.162963,5.929630,3.914286,7.957143,0.152494,1.581523,1.078946,2.285714,5.618971,2,1989
1989-03-31,0.223226,1.420645,3.434194,NaN,NaN,NaN,5.788065,NaN,50.570968,2.351613,1.983871,NaN,2.151613,1.887097,2.261290,NaN,3.283871,6.461290,0.238710,4.575000,13.122258,81.167742,NaN,NaN,43.200000,6.229032,3.190323,6.758065,0.327246,3.072638,2.388181,2.806452,5.621405,3,1989
1989-04-30,0.216000,3.463667,5.084667,NaN,NaN,NaN,9.508000,NaN,50.753333,4.620000,3.410000,NaN,4.396667,4.236667,4.260000,NaN,4.573333,8.133333,0.433333,3.312500,21.742333,73.423333,NaN,NaN,43.150000,6.096667,2.683333,6.173333,0.527897,5.033530,3.946573,4.166667,5.625994,4,1989
1989-05-31,0.254516,7.369677,5.761290,NaN,NaN,NaN,18.581290,NaN,52.035484,9.354839,6.116129,NaN,9.029032,9.238710,8.090323,NaN,10.603226,15.609677,4.774194,0.651852,43.630645,60.158065,NaN,NaN,42.403226,5.561290,3.564516,7.529032,1.001601,9.761131,7.818558,10.193548,5.647532,5,1989
1989-06-30,0.247500,9.671786,6.675000,NaN,NaN,NaN,20.944643,NaN,51.532143,13.185714,9.010714,NaN,12.789286,13.282143,11.496429,NaN,14.463333,19.300000,8.463333,2.745833,49.733929,65.432143,NaN,NaN,42.725000,5.742857,3.078571,7.028571,1.183515,10.809689,8.951439,14.000000,5.661012,6,1989
1989-07-31,0.233214,8.355357,6.732500,NaN,NaN,NaN,18.133571,NaN,50.546429,15.425000,11.739286,NaN,15.060714,15.435714,14.046429,NaN,16.087097,21.745161,9.993548,2.437037,43.169643,64.371429,NaN,NaN,43.635714,5.817857,3.007143,6.600000,1.021952,9.284355,7.827264,15.677419,5.666683,7,1989
1989-08-31,0.246207,4.975517,5.820345,NaN,NaN,NaN,11.984483,NaN,50.444828,14.265517,12.337931,NaN,14.051724,13.924138,13.855172,NaN,13.570968,18.183871,9.009677,5.556522,28.325862,76.593103,NaN,NaN,43.500000,6.055172,2.855172,6.196552,0.696238,6.157850,5.130396,13.129032,5.657957,8,1989
1989-09-30,0.260714,2.839286,2.985000,NaN,NaN,NaN,9.186071,NaN,51.850000,11.385714,11.082143,NaN,11.267857,10.814286,11.646429,NaN,10.706667,15.683333,5.736667,2.313636,21.453571,78.735714,NaN,NaN,42.332143,5.817857,2.471429,5.832143,0.503150,4.889380,3.793541,10.266667,5.647898,9,1989
1989-10-31,NaN,-1.781034,1.524138,NaN,NaN,NaN,4.203793,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.293548,NaN,NaN,2.691304,NaN,81.220690,NaN,NaN,NaN,NaN,2.548276,NaN,NaN,NaN,NaN,5.838710,5.632219,10,1989
1989-11-30,0.275455,-2.329091,0.758182,NaN,NaN,NaN,1.333636,NaN,50.754545,3.359091,6.200000,NaN,3.500000,2.263636,5.100000,NaN,1.820000,4.710000,-0.890000,3.037500,2.409545,82.627273,NaN,NaN,43.177273,6.068182,2.540909,6.150000,0.074569,0.699445,0.559623,1.600000,5.615971,11,1989
1989-12-31,0.400968,-2.010323,0.457742,NaN,NaN,NaN,0.707742,NaN,49.451613,-0.819355,2.735484,NaN,-0.677419,-1.980645,0.983871,NaN,-2.864516,0.283871,-6.538710,1.633333,0.863548,85.480645,NaN,NaN,43.851613,6.696774,2.103226,4.967742,0.043826,0.358651,0.305265,-2.580645,5.598797,12,1989
1990-01-31,0.342903,-1.817419,0.647742,NaN,NaN,NaN,0.901613,NaN,50.900000,-0.500000,1.387097,NaN,-0.532258,-1.238710,0.458065,NaN,1.312903,3.322581,-1.129032,4.104348,1.369032,85.022581,NaN,NaN,42.458065,6.641935,3.467742,7.109677,0.056576,0.465453,0.379585,1.096774,5.614194,1,1990
1990-02-28,0.213077,-0.746923,1.243077,NaN,NaN,NaN,1.672308,NaN,49.338462,1.084615,1.300000,NaN,1.015385,0.707692,1.123077,NaN,3.550000,5.657143,1.707143,6.920000,3.150769,87.707692,NaN,NaN,44.092308,6.569231,5.084615,9.115385,0.102164,0.873708,0.696436,3.214286,5.622344,2,1990
1990-03-31,0.280690,0.972414,3.045172,NaN,NaN,NaN,7.545172,NaN,53.148276,2.493103,2.358621,NaN,2.351724,1.979310,2.510345,NaN,4.596774,8.667742,0.906452,0.703448,17.198621,68.582759,NaN,NaN,41.262069,5.589655,5.182759,10.262069,0.400026,4.077559,3.067587,4.161290,5.626115,3,1990
1990-04-30,0.255714,4.271429,7.099286,NaN,NaN,NaN,11.671786,NaN,52.607143,5.496429,3.989286,NaN,5.267857,5.164286,4.921429,NaN,6.373333,10.836667,1.603333,2.888000,27.091071,70.628571,NaN,NaN,41.664286,5.728571,3.278571,7.342857,0.635004,6.269210,4.767572,5.933333,5.632475,4,1990
1990-05-31,0.255484,8.458710,8.279032,NaN,NaN,NaN,19.874839,NaN,53.635484,10.377419,7.093548,NaN,9.974194,10.316129,9.058065,NaN,11.851613,17.483871,5.461290,0.400000,46.296129,60.058065,NaN,NaN,40.932258,5.432258,2.841935,6.748387,1.055604,10.722228,8.097006,11.387097,5.651927,5,1990
1990-06-30,0.226000,7.964483,8.194800,NaN,NaN,NaN,17.147333,NaN,51.736667,13.600000,9.589655,NaN,13.134483,13.631034,11.910345,NaN,14.573333,18.986667,9.576667,4.480952,40.081333,68.820690,NaN,NaN,42.270000,5.993333,2.741379,6.141379,0.985109,9.005184,7.157040,14.200000,5.661460,6,1990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-07-31,0.219608,8.760595,11.044307,NaN,4.812296,0.415782,19.652169,6.931839,47.294924,17.090054,12.832294,17.729072,16.578486,17.560577,15.076135,998.049526,16.482642,20.841935,11.842935,1.716129,46.638548,79.031735,NaN,NaN,47.676600,5.028476,2.542978,5.512107,0.979398,9.310141,9.362630,16.032258,5.668068,7,2016
2016-08-31,0.232123,5.362952,7.618797,NaN,1.436022,0.124072,14.641105,5.792129,46.718384,15.700502,13.531286,16.004883,15.530784,15.987056,14.824960,1000.005668,14.906185,19.122903,10.460645,4.345161,34.634558,81.545280,NaN,NaN,48.198750,5.082866,2.762680,5.868613,0.715764,6.937616,6.987726,14.354839,5.662613,8,2016
2016-09-30,0.242359,2.687009,5.271522,NaN,0.457797,0.039554,10.554054,3.990767,47.758733,14.605387,13.305083,14.772602,14.549102,14.828676,14.117773,1003.115717,14.418778,18.847667,9.787833,1.240000,24.717568,82.944998,NaN,NaN,47.440667,4.800600,2.793669,5.786458,0.494534,5.086688,4.972833,13.933333,5.660915,9,2016
2016-10-31,0.239483,-0.470490,2.050566,NaN,-5.335233,-0.460964,4.129014,-0.868581,46.990075,7.436224,10.416787,7.014595,7.994876,7.339060,9.096426,1015.898142,5.578512,8.435194,2.548968,1.025806,9.443530,80.813575,NaN,NaN,47.763598,5.246327,2.484168,4.394826,0.184057,2.111027,1.833930,5.032258,5.629679,10,2016
2016-11-30,0.328145,-1.786588,1.282482,NaN,-6.038246,-0.521704,1.660038,-6.234133,49.345975,2.576328,6.669142,2.077913,3.221579,2.437317,4.607155,999.608583,0.547338,3.115200,-2.474967,2.400000,3.724252,86.135737,1.250000,NaN,46.284728,4.369297,2.824288,5.503333,0.071473,0.863730,0.724835,0.500000,5.611378,11,2016
2016-12-31,0.238223,-2.055584,0.709503,NaN,-4.566007,-0.394503,0.893656,-6.381742,49.184195,0.204835,4.021860,-0.150705,0.734209,0.140392,1.949444,1003.935868,0.787770,3.670968,-2.357516,0.822581,1.820102,88.731588,NaN,NaN,46.326664,4.489140,2.810407,5.934036,0.035199,0.452796,0.405660,0.741935,5.612277,12,2016
2017-01-31,0.273643,-1.741463,0.905419,NaN,-3.826894,-0.330644,1.300772,-8.224548,48.897107,-0.339408,2.685637,-0.702853,0.101325,-0.389966,1.013625,1002.960126,-1.321210,1.604742,-4.450581,1.967742,2.673057,89.300722,0.000000,0.004545,46.694647,4.408246,2.277970,5.305821,0.050884,0.677780,0.572108,-1.193548,5.604556,1,2017
2017-02-28,0.608297,-1.027885,2.261545,NaN,-2.075670,-0.179338,3.575744,-7.279429,46.197657,-0.367898,2.035062,-0.506069,-0.053941,-0.318531,0.645335,1003.412971,-1.868429,0.739107,-4.837393,2.575000,8.162283,88.698161,6.460714,6.160000,48.216563,5.585780,2.341890,4.488708,0.172338,1.764730,1.638676,-1.642857,5.602534,2,2017
2017-03-31,0.308784,1.282314,4.244221,NaN,-0.089608,-0.007742,7.991870,-4.795387,47.976750,-0.239047,1.683853,-0.174131,0.002038,-0.108780,0.541026,997.950252,2.167789,5.948419,-1.478774,1.406452,18.355857,79.561990,1.222581,0.739130,47.120839,4.902411,2.724360,5.398000,0.363202,3.993490,3.635178,1.903226,5.617329,3,2017
2017-04-30,0.249136,4.094198,8.499720,NaN,1.619920,0.139961,14.065926,-5.860133,47.836346,3.620961,3.124707,3.980804,3.477486,3.915559,3.164653,999.917570,4.671407,9.335367,-0.276500,1.123333,32.538106,70.832986,0.086667,1.241176,47.338992,4.824662,3.046118,6.065700,0.653052,6.852239,6.560635,4.266667,5.626396,4,2017
2017-05-31,0.230421,6.629230,9.055980,3.466667,6.686611,0.577723,17.146469,0.736065,46.481208,9.165236,5.705695,9.891351,8.571944,9.660158,7.146142,1005.805755,11.125230,15.567839,6.122000,2.254839,40.602695,73.683139,0.096774,0.157895,48.365709,5.153083,2.516183,5.330000,0.828000,8.201443,8.117026,10.677419,5.649314,5,2017
2017-06-30,0.217196,8.097596,9.577506,3.679310,5.313374,0.459075,19.649584,5.343233,46.150257,14.091077,9.827467,14.725262,13.564191,14.526975,12.036794,996.061630,14.540294,18.505333,10.050833,3.083333,46.920710,72.488046,0.000000,NaN,48.656923,5.192820,2.808913,5.352300,0.974020,9.274336,9.401229,14.166667,5.661338,6,2017
2017-07-31,0.223415,8.618810,10.345582,4.093548,4.771629,0.412269,20.430993,5.786677,46.808785,15.705910,12.002618,16.307231,15.244825,16.118947,13.912473,998.131523,16.212180,20.789032,11.129161,1.432258,48.642446,70.825048,0.000000,NaN,48.182662,5.008552,2.576571,5.129355,0.999827,9.660200,9.770966,15.806452,5.667149,7,2017
2017-08-31,0.222929,5.402878,8.132749,2.924645,2.317100,0.200197,15.384474,5.852355,46.844001,15.506438,12.964693,15.889375,15.242929,15.832008,14.363889,999.072123,14.733640,18.832581,10.702677,4.248387,36.950464,81.739215,0.000000,NaN,48.156047,4.999952,2.840530,5.396839,0.743506,7.315928,7.325039,14.290323,5.662025,8,2017
2017-09-30,0.230391,1.276886,5.348603,1.665200,-0.664603,-0.057422,7.072249,5.193800,44.705422,12.924322,12.457954,12.966674,12.995056,13.072024,10.478753,1002.603740,11.657505,14.672667,8.866633,4.006667,17.142112,86.843125,0.000000,NaN,49.976865,5.317713,2.035154,4.020571,0.356582,3.257174,3.458493,11.166667,5.651279,9,2017
2017-10-31,0.247620,-0.712104,3.408103,1.369690,-11.055601,-0.955204,4.674338,-0.889742,49.510969,7.771880,10.107360,7.429156,8.243667,7.717735,9.099338,997.395666,6.867135,10.762290,3.049161,4.454839,10.740695,83.430881,0.000000,NaN,45.737506,4.751525,2.432459,5.167593,0.205299,2.403002,2.066037,6.322581,5.634263,10,2017
2017-11-30,0.388057,-2.280462,1.303748,NaN,-7.483098,-0.646540,2.148998,-6.268200,52.262972,2.377675,6.432201,1.906889,3.002240,2.256892,4.351032,991.862597,1.408590,4.628933,-2.246433,3.393333,4.670737,89.101392,1.300000,1.880952,43.562112,4.174916,2.913279,5.405565,0.082924,1.200211,0.865863,1.333333,5.614556,11,2017
2017-12-31,0.566657,-1.653746,0.814956,NaN,-3.193061,-0.275881,0.869214,-9.071903,44.720191,0.309234,3.692640,0.038692,0.755190,0.280634,1.788993,988.243665,-1.934525,0.903355,-5.625516,2.341935,1.745946,92.660790,3.935484,4.894737,49.769877,5.509932,2.348489,5.086826,0.038652,0.422491,0.408072,-1.741935,5.602282,12,2017
2018-01-31,0.704478,-1.508288,1.000068,NaN,-1.941205,-0.167720,1.059359,-8.401161,44.687227,-0.063091,2.580788,-0.223880,0.272923,-0.032589,1.046826,995.286197,-2.242236,0.006613,-5.384452,3.006452,2.454890,94.835545,NaN,17.850000,49.500758,5.812016,3.228349,5.931778,0.056497,0.502786,0.500076,-1.870968,5.601175,1,2018
2018-02-28,0.756667,-1.485366,2.708390,NaN,-1.804921,-0.155945,3.735215,-10.651821,46.873048,-0.206378,2.056982,-0.353070,0.084123,-0.175992,0.730422,1008.600250,-4.618707,-2.320071,-7.614286,1.564286,8.828382,84.612383,NaN,27.500000,47.599915,5.527037,2.693732,4.709107,0.192677,1.851201,1.691337,-4.178571,5.592318,2,2018
2018-03-31,0.719597,-1.322930,5.268509,NaN,-1.551799,-0.134075,9.467900,-12.262839,47.189376,-0.340456,1.725947,-0.456385,-0.061644,-0.305243,0.521653,1000.202732,-3.454439,0.554645,-7.948968,0.748387,21.998753,68.663190,NaN,33.421053,47.480104,5.330520,2.033768,4.090613,0.463780,4.710053,4.294067,-3.096774,5.596661,3,2018
2018-04-30,0.345246,3.995996,6.560670,NaN,3.701229,0.319786,14.512068,-4.308700,46.266562,1.655025,1.878062,2.089192,1.547896,1.944217,1.431670,1000.348543,5.329019,10.451333,0.172433,1.073333,34.073683,73.521368,NaN,7.619048,48.704871,5.028567,2.366346,5.235233,0.686102,6.960016,6.865950,4.933333,5.628736,4,2018
2018-05-31,0.230545,9.013674,8.370875,4.320679,12.459105,1.076467,23.010046,1.460484,47.706569,11.537924,6.514195,12.476347,10.735736,12.136369,8.799808,1008.673961,15.259366,21.399194,8.174677,0.977419,53.984315,64.475974,NaN,0.000000,47.570120,4.723312,2.422919,5.288871,1.066648,11.075889,10.867509,14.774194,5.663753,5,2018
2018-06-30,0.216661,10.105925,9.416289,5.806667,7.620137,0.658380,24.626828,5.848233,47.410984,15.495124,10.732889,16.263080,14.875673,15.999995,13.169085,1001.253707,16.992781,21.985333,11.422100,2.860000,59.027742,62.494384,NaN,NaN,47.726885,4.862131,3.037686,6.094667,1.179606,11.743100,11.704122,16.433333,5.669789,6,2018
2018-07-31,0.203536,10.660636,8.634094,6.593548,8.536547,0.737558,24.097960,7.993645,46.912427,18.168179,13.197987,19.049959,17.487285,18.736279,15.700444,1002.960765,20.544472,26.295806,13.969677,1.635484,58.396721,65.675934,NaN,NaN,48.222164,4.865409,2.372298,5.537903,1.163079,11.337568,11.597313,20.096774,5.682013,7,2018
2018-08-31,0.196231,5.468839,7.956325,3.738710,0.276122,0.023857,14.931245,4.617710,46.726319,15.879534,13.931620,16.084675,15.733412,16.097785,15.128632,999.411839,15.621896,20.053871,10.840129,1.441935,35.987214,76.712291,NaN,NaN,48.252680,5.021002,2.790709,5.855097,0.730025,7.053435,7.147785,15.064516,5.665084,8,2018
2018-09-30,0.214717,2.106218,5.245420,2.570000,-3.149628,-0.272128,9.860936,3.134000,48.327016,12.550455,12.611535,12.459936,12.679791,12.610105,12.778881,999.552967,12.311987,16.337667,8.204000,4.023333,23.862330,77.921020,NaN,NaN,46.771172,4.901812,3.510028,6.915300,0.465148,4.844410,4.551378,11.833333,5.653530,9,2018
2018-10-31,0.238793,-0.365834,2.768081,0.704762,-6.248281,-0.539851,5.062992,-2.497677,49.654447,7.791625,10.062614,7.357515,8.190925,7.645368,9.035024,1000.178916,6.937797,10.624935,2.876032,1.422581,11.762298,84.887012,NaN,4.000000,45.585580,4.759973,2.928179,5.666742,0.223776,2.609549,2.229667,6.516129,5.634442,10,2018
2018-11-30,0.203602,-1.047731,1.159144,NaN,-5.910428,-0.510661,1.270950,-2.466333,47.195626,4.822615,7.565684,4.403387,5.198988,4.672397,6.128296,1009.284230,3.154925,5.212100,0.808967,4.506667,2.788651,95.057384,NaN,0.186364,47.422011,5.382363,2.320993,4.348200,0.057322,0.645702,0.567926,2.900000,5.620788,11,2018
2018-12-31,0.668381,-1.243333,0.653213,NaN,-4.588814,-0.396474,0.796074,-7.879613,45.140034,1.284619,4.489807,0.741258,1.471351,0.970264,2.512676,1000.917535,-1.698744,0.398258,-4.480806,2.058065,1.665585,93.765815,NaN,12.555556,49.257195,5.602771,2.104571,4.104333,0.037058,0.385555,0.373461,-1.580645,5.603147,12,2018

We can store the grouped dataset in a variable

In [47]:
weekly_weather_mean = weather.groupby(pd.Grouper(freq='W')).mean()

In [48]:
weekly_weather_mean

,albedo,balanse,diffus,fd,fluxm,fluxs,global,grmin,ir√∏d,jt010,jt100,jt002,jt020,jt005,jt050,lp,lt,ltmax,ltmin,nb,par,rf,sd,sdman,synlig,uv,vh,vhmax,uv_amount,ir_amount,visible_amount,rounded_lt,log_kelvin_lt,month,year
dato,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1988-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.366667,4.433333,1.566667,20.200000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.000000,5.621712,1.000000,1988.0
1988-01-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.471429,0.800000,-3.042857,1.940000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.428571,5.607689,1.000000,1988.0
1988-01-17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.842857,3.400000,0.742857,2.340000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.428571,5.616188,1.000000,1988.0
1988-01-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.885714,2.100000,-0.257143,8.260000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.571429,5.612703,1.000000,1988.0
1988-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.142857,-0.642857,-1.857143,9.840000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.857143,5.605260,1.000000,1988.0
1988-02-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.257143,2.928571,-0.800000,7.416667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.857143,5.614056,2.000000,1988.0
1988-02-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.342857,0.785714,-3.685714,5.580000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.428571,5.604502,2.000000,1988.0
1988-02-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.671429,0.828571,-2.542857,1.320000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.571429,5.606992,2.000000,1988.0
1988-02-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-5.400000,-1.885714,-9.900000,0.640000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-5.000000,5.589446,2.000000,1988.0
1988-03-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.228571,0.314286,-3.657143,1.666667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.000000,5.604943,2.857143,1988.0
1988-03-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-4.371429,0.971429,-9.985714,1.516667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-4.000000,5.593310,3.000000,1988.0
1988-03-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-5.114286,0.642857,-11.885714,3.020000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-4.714286,5.590517,3.000000,1988.0
1988-03-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.342857,1.500000,-2.500000,1.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,5.608206,3.000000,1988.0
1988-04-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.283333,4.600000,-0.050000,12.625000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.833333,5.617797,3.428571,1988.0
1988-04-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.042857,4.628571,-2.471429,0.275000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.714286,5.613277,4.000000,1988.0
1988-04-17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.071429,4.971429,-2.128571,1.580000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.857143,5.617011,4.000000,1988.0
1988-04-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.385714,4.885714,-2.142857,3.950000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.285714,5.614526,4.000000,1988.0
1988-05-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.914286,9.671429,-1.371429,0.328571,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.428571,5.623695,4.142857,1988.0
1988-05-08,0.205000,8.020000,5.260000,NaN,NaN,NaN,17.115000,NaN,49.750000,10.350000,4.700000,NaN,9.950000,11.450000,7.250000,NaN,9.100000,13.742857,5.285714,2.133333,NaN,71.000000,NaN,NaN,45.200000,5.050000,NaN,NaN,0.861045,8.520150,7.733805,8.428571,5.642235,5.000000,1988.0
1988-05-15,0.234286,9.500000,5.337143,NaN,NaN,NaN,20.777143,NaN,50.728571,11.557143,5.857143,NaN,10.871429,11.800000,8.757143,NaN,13.828571,17.642857,8.685714,0.000000,NaN,50.428571,NaN,NaN,44.214286,5.057143,NaN,NaN,1.039293,10.574049,9.163801,13.714286,5.658869,5.000000,1988.0
1988-05-22,0.254286,8.610000,5.528571,NaN,NaN,NaN,21.015714,NaN,50.971429,11.214286,7.185714,NaN,11.000000,11.028571,9.628571,NaN,10.342857,17.100000,6.042857,0.200000,NaN,56.428571,NaN,NaN,43.757143,5.271429,NaN,NaN,1.101023,10.725960,9.188731,10.142857,5.646627,5.000000,1988.0
1988-05-29,0.244286,8.932857,7.298571,NaN,NaN,NaN,18.507143,NaN,49.914286,12.857143,7.685714,NaN,12.242857,13.128571,10.142857,NaN,15.214286,19.614286,10.400000,2.980000,NaN,67.571429,NaN,NaN,44.714286,5.371429,NaN,NaN,0.976880,9.274749,8.255514,14.571429,5.663606,5.000000,1988.0
1988-06-05,0.238571,6.544286,7.214286,NaN,NaN,NaN,12.885714,NaN,48.557143,14.300000,9.000000,NaN,13.771429,14.385714,12.042857,NaN,13.828571,17.314286,10.728571,4.416667,NaN,79.714286,NaN,NaN,45.271429,6.171429,NaN,NaN,0.776914,6.301107,5.807693,13.428571,5.658857,5.714286,1988.0
1988-06-12,0.240000,10.190000,4.330000,NaN,NaN,NaN,22.772500,NaN,50.400000,15.225000,9.900000,NaN,14.825000,15.325000,12.940000,NaN,16.328571,22.785714,9.671429,1.528571,NaN,55.800000,NaN,NaN,44.350000,5.250000,3.266667,NaN,1.189712,11.487990,10.094797,16.000000,5.667534,6.000000,1988.0
1988-06-19,0.235714,11.787143,6.198571,NaN,NaN,NaN,24.772857,NaN,50.600000,16.514286,10.328571,NaN,15.928571,16.900000,13.600000,NaN,18.028571,24.014286,11.785714,0.100000,67.045000,60.000000,NaN,NaN,44.128571,5.271429,2.457143,6.350000,1.305067,12.541089,10.926701,17.571429,5.673414,6.000000,1988.0
1988-06-26,0.227143,10.572857,5.811429,NaN,NaN,NaN,22.764286,NaN,51.057143,18.700000,11.042857,NaN,18.014286,19.214286,15.071429,NaN,20.542857,26.500000,13.714286,0.000000,60.122857,63.285714,NaN,NaN,43.628571,5.314286,2.100000,5.714286,1.199703,11.658671,9.905911,20.285714,5.682011,6.000000,1988.0
1988-07-03,0.205714,9.245714,7.524286,NaN,NaN,NaN,18.267143,NaN,50.914286,19.014286,12.214286,NaN,18.528571,19.085714,16.271429,NaN,19.585714,24.285714,14.942857,3.628571,47.624286,71.714286,NaN,NaN,43.342857,5.742857,3.000000,6.585714,1.013104,9.408807,7.845231,19.285714,5.678724,6.428571,1988.0
1988-07-10,0.204286,7.177143,7.540000,NaN,NaN,NaN,14.788571,NaN,51.100000,16.671429,12.714286,NaN,16.400000,16.414286,15.485714,NaN,15.671429,19.285714,11.857143,4.028571,39.092857,78.571429,NaN,NaN,43.000000,5.900000,3.171429,6.828571,0.869803,7.579786,6.338983,15.285714,5.665283,7.000000,1988.0
1988-07-17,0.221429,7.074286,7.107143,NaN,NaN,NaN,14.638571,NaN,50.157143,16.028571,12.600000,NaN,15.714286,15.871429,14.885714,NaN,15.757143,19.857143,11.328571,9.285714,38.901429,80.000000,NaN,NaN,43.800000,6.042857,2.957143,6.685714,0.849756,7.454853,6.333963,15.285714,5.665581,7.000000,1988.0
1988-07-24,0.233333,6.160000,6.791667,NaN,NaN,NaN,12.598333,NaN,49.300000,17.083333,12.800000,NaN,16.633333,17.150000,15.416667,NaN,16.342857,20.157143,12.171429,3.471429,33.371667,81.000000,NaN,NaN,44.533333,6.166667,2.266667,5.100000,0.737500,6.348447,5.512387,15.857143,5.667601,7.000000,1988.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-06-17,0.206310,7.602643,9.023040,4.885714,4.008234,0.346312,19.690841,8.578714,46.712004,15.536306,10.841031,16.106654,15.055584,15.939009,13.442103,995.859471,14.863477,18.527143,11.650000,11.228571,47.504211,75.805560,NaN,NaN,48.254715,5.033280,3.456334,6.551143,0.961675,9.316093,9.413073,14.285714,5.662478,6.000000,2018.0
2018-06-24,0.211725,8.408021,12.186024,3.900000,1.776541,0.153493,20.422071,3.154857,46.870246,13.964217,11.257084,14.335019,13.746269,14.256757,12.965871,997.366229,13.742616,17.652857,8.494286,0.400000,49.337783,64.979574,NaN,NaN,48.097849,5.031906,3.475875,6.287571,1.014351,9.606556,9.801164,13.285714,5.658562,6.000000,2018.0
2018-07-01,0.214791,12.792833,8.331141,6.771429,10.460048,0.903748,29.497701,5.416000,47.879477,16.467131,11.544811,17.397004,15.713930,17.049523,13.858256,1010.412571,19.755486,25.635714,12.658571,0.014285,70.422049,52.053193,NaN,NaN,47.420925,4.699598,2.604654,5.533286,1.384423,14.134339,13.978940,19.142857,5.679309,6.142857,2018.0
2018-07-08,0.210538,12.375810,7.577553,6.942857,9.346155,0.807508,28.430071,6.430429,47.350186,17.353940,12.272221,18.282806,16.627660,17.936897,14.763154,1001.827214,19.982401,26.118571,12.430000,0.042856,68.338180,56.352570,NaN,NaN,47.907319,4.742495,2.551866,5.165571,1.346097,13.474658,13.609316,19.571429,5.680105,7.000000,2018.0
2018-07-15,0.203087,10.154865,8.621715,5.357143,8.240762,0.712002,22.946673,8.915286,46.949930,17.519029,12.859136,18.380436,16.875646,18.071091,15.212499,1004.695571,19.993810,25.574286,14.104286,4.014286,55.629829,67.602061,NaN,NaN,48.140512,4.909558,2.537990,5.818857,1.119183,10.776586,11.050905,19.571429,5.680132,7.000000,2018.0
2018-07-22,0.200981,10.347783,9.799790,7.885714,8.142804,0.703538,22.939101,7.378000,46.579910,18.893451,13.501923,19.825596,18.149910,19.500039,16.186390,1000.279000,20.133186,25.594286,14.360000,0.671428,55.614760,72.798501,NaN,NaN,48.562649,4.857441,2.160047,5.018571,1.104221,10.723735,11.111146,19.714286,5.680619,7.000000,2018.0
2018-07-29,0.200289,10.348302,8.208179,7.014286,8.699943,0.751675,23.359571,9.949143,47.153046,19.036556,14.019880,19.899641,18.355259,19.600913,16.544603,1002.970600,22.174306,27.791429,15.488571,1.485715,57.084414,67.505219,NaN,NaN,47.973133,4.873821,2.514653,6.290429,1.134661,11.030535,11.194375,21.571429,5.687556,7.000000,2018.0
2018-08-05,0.194355,8.499026,9.532195,4.828571,5.012931,0.433117,19.583246,8.272000,46.178849,18.682510,14.420486,19.254156,18.227907,19.120901,16.787501,1004.702486,19.894871,25.274286,14.634286,1.185714,47.732527,69.907181,NaN,NaN,48.811244,5.009907,2.656037,5.912143,0.970658,9.078432,9.534156,19.285714,5.679806,7.714286,2018.0
2018-08-12,0.189452,5.433049,9.176436,4.500000,-0.435899,-0.037662,14.665916,6.478857,46.138380,16.811270,14.426001,16.970716,16.719426,17.011283,16.038781,998.107071,16.281894,20.574286,12.048571,3.757143,34.259683,76.605444,NaN,NaN,48.824022,5.037598,3.041157,6.500857,0.733207,6.794657,7.138052,15.714286,5.667376,8.000000,2018.0
2018-08-19,0.191046,4.135422,6.787797,2.971429,-0.613878,-0.053039,12.606615,4.886571,46.306851,15.334503,13.958623,15.495931,15.280110,15.533293,14.892223,998.227386,15.153161,19.225714,10.374714,1.428571,30.581520,81.016676,NaN,NaN,48.407923,5.285226,3.011922,6.081000,0.627299,5.968648,6.010669,14.571429,5.663482,8.000000,2018.0
2018-08-26,0.204685,5.485909,7.367958,3.071429,-0.684206,-0.059115,15.626710,1.583857,47.703371,14.699089,13.559079,14.802440,14.607133,14.849683,14.272251,995.532857,13.772901,18.385714,8.233000,0.428571,38.070821,76.625030,NaN,NaN,47.425373,4.871256,2.427344,5.951714,0.743139,7.548846,7.334726,13.428571,5.658682,8.000000,2018.0
2018-09-02,0.206583,4.483110,8.719389,3.300000,0.175942,0.015201,13.217849,1.986429,47.445394,14.168830,13.146151,14.348859,14.025386,14.344256,13.677460,1006.502629,14.091427,18.700000,9.318857,0.600000,32.230641,77.637183,NaN,NaN,47.695108,4.859498,2.385551,4.505857,0.630547,6.352240,6.235061,13.428571,5.659799,8.285714,2018.0
2018-09-09,0.193864,2.734939,6.091258,2.514286,2.159208,0.186556,8.790161,7.597000,45.192501,14.599007,12.952947,14.954799,14.355119,14.884773,13.722061,1006.188371,15.116389,18.821429,12.172857,6.157144,21.936257,87.421429,NaN,NaN,49.463273,5.344226,2.347098,4.436429,0.454006,4.055060,4.281096,14.714286,5.663361,9.000000,2018.0
2018-09-16,0.215467,2.261644,5.233140,3.000000,-4.773969,-0.412471,10.492558,2.845857,48.809896,13.043263,12.963929,12.829634,13.270229,13.054157,13.391249,997.289543,12.088216,16.010000,8.007429,7.600000,25.380736,78.390043,NaN,NaN,46.377942,4.812163,3.597129,6.992857,0.493139,5.158837,4.840583,11.571429,5.652783,9.000000,2018.0
2018-09-23,0.223367,1.712126,4.448849,2.571429,-2.163504,-0.186927,9.508771,6.400143,49.428463,12.610564,12.509593,12.566171,12.642974,12.692807,12.646110,988.849800,12.987894,16.098571,10.015857,2.728572,22.909896,76.000111,NaN,NaN,45.773602,4.797935,5.023591,9.255286,0.440612,4.779323,4.288836,12.571429,5.655920,9.000000,2018.0
2018-09-30,0.225792,0.641207,3.567932,1.914286,-9.035873,-0.780700,8.526094,-3.576571,49.707899,9.506577,11.897609,8.948365,10.096041,9.321373,11.129226,1001.678286,8.518263,13.434286,2.555000,0.757141,20.036920,69.851676,NaN,NaN,45.561978,4.730124,3.389564,7.613714,0.376907,4.348634,3.800552,8.000000,5.640163,9.000000,2018.0
2018-10-07,0.229898,0.105472,3.428882,0.971429,-8.869028,-0.766284,7.285007,-5.778000,49.004559,7.627982,10.735367,6.978476,8.173803,7.354249,9.367172,996.505529,5.854789,10.812286,0.404286,0.871429,16.920651,81.460290,NaN,NaN,46.278269,4.717172,2.227244,5.217857,0.319027,3.684487,3.281494,5.285714,5.630671,10.000000,2018.0
2018-10-14,0.221300,0.693443,3.048877,0.585714,4.731169,0.408773,5.326912,5.978857,48.174660,9.878328,10.052735,10.098922,9.533728,10.030612,9.412619,1002.357886,12.551436,15.544286,9.313714,0.428571,12.748886,91.638947,NaN,NaN,46.939267,4.886073,4.172502,6.888714,0.247248,2.650655,2.429009,12.142857,5.654406,10.000000,2018.0
2018-10-21,0.211600,-0.239199,2.764378,0.557143,-5.107529,-0.441291,4.209062,-1.877571,47.995731,9.673143,10.350180,9.372767,9.956567,9.624163,10.258661,1005.322743,8.271319,11.870000,4.124286,0.757141,10.046731,92.418384,NaN,NaN,47.105760,4.898509,2.246547,4.641143,0.193063,2.109590,1.906409,7.714286,5.639269,10.000000,2018.0
2018-10-28,0.237893,-1.628729,2.322167,NaN,-14.974710,-1.293815,4.868413,-7.820286,55.899510,6.017338,9.735030,5.089584,6.922797,5.646527,8.388502,996.471471,3.259281,7.113857,-0.931571,0.028573,10.643893,71.269693,NaN,NaN,40.011906,4.088584,2.741225,5.796143,0.192587,2.776373,1.899453,3.000000,5.621276,10.000000,2018.0
2018-11-04,0.258369,-0.838994,1.733136,NaN,-3.900699,-0.337020,1.860061,-2.580571,47.294840,4.087002,8.184774,3.825244,4.580121,4.038527,5.930358,1003.141943,4.125808,6.564714,0.902714,5.071429,4.434144,93.900706,NaN,2.00,47.356923,5.348237,2.987864,5.548571,0.092300,0.899833,0.867928,3.571429,5.624413,10.571429,2018.0
2018-11-11,0.171151,-0.377066,0.711539,NaN,0.635351,0.054894,0.695426,4.955286,41.784067,6.526318,7.742291,6.616429,6.530771,6.665824,6.737937,1002.404186,7.222380,7.942000,6.074286,10.428571,1.815190,98.668453,NaN,0.00,51.806672,6.409261,1.868897,3.950857,0.043381,0.285195,0.366850,6.714286,5.635579,11.000000,2018.0
2018-11-18,0.188060,-0.925033,1.254809,NaN,-4.256216,-0.367737,1.460109,1.930429,48.627519,7.345365,8.031612,7.160246,7.509123,7.359840,7.659820,1013.668243,6.641991,8.330857,4.912143,2.742859,3.427063,96.326586,NaN,0.00,46.328641,5.043840,2.640815,4.912143,0.064511,0.784475,0.611123,6.142857,5.633478,11.000000,2018.0
2018-11-25,0.218014,-1.518644,0.998286,NaN,-14.434189,-1.247114,1.045275,-9.806143,50.805021,3.489121,7.643353,2.389870,4.233755,2.908034,5.967239,1017.565429,-1.972941,0.175571,-4.843857,0.000000,2.335207,89.195436,NaN,0.02,43.677448,5.517531,1.793608,3.269571,0.051023,0.558683,0.435569,-1.714286,5.602193,11.000000,2018.0
2018-12-02,0.245590,-1.752746,1.184413,NaN,-5.929360,-0.512297,1.341165,-6.560429,48.104889,0.760545,6.088254,0.022937,1.477924,0.416175,3.348187,999.567571,-0.367262,2.655571,-2.944571,7.642857,2.154372,96.702380,NaN,0.80,47.343347,4.551765,3.096160,5.026143,0.043509,0.684083,0.613572,-0.285714,5.607916,11.285714,2018.0
2018-12-09,0.706626,-1.647389,0.837466,NaN,-6.713197,-0.580020,0.869692,-6.524143,46.520333,1.630209,5.190266,1.161980,2.029336,1.432863,3.141496,984.031100,0.158493,1.874000,-2.404429,4.828571,1.632613,91.713293,NaN,2.00,48.235787,5.243880,2.121406,4.519800,0.036888,0.428754,0.404050,0.285714,5.609996,12.000000,2018.0
2018-12-16,0.727987,-1.315591,0.545360,NaN,-5.129149,-0.443159,0.858251,-9.933000,42.501817,1.463279,4.604385,0.630384,1.427329,0.887257,2.525630,1013.729857,-3.322953,-1.065143,-6.616143,0.385714,1.831566,89.189673,NaN,17.60,51.460128,6.038055,2.358082,4.213000,0.043618,0.392202,0.422432,-3.142857,5.597147,12.000000,2018.0
2018-12-23,0.743948,-0.761640,0.537940,NaN,-3.635902,-0.314142,0.547650,-6.488571,41.917989,1.513579,4.134398,0.918579,1.446394,1.088479,2.319183,1004.529171,-2.290283,-0.994143,-4.389429,0.885714,1.337160,94.103303,NaN,17.60,51.529661,6.552351,1.675201,2.988000,0.030483,0.251458,0.265709,-2.285714,5.601016,12.000000,2018.0
2018-12-30,0.643094,-1.130415,0.691650,NaN,-5.059778,-0.437165,0.962235,-11.729857,49.912244,0.778157,3.853340,0.439209,1.125261,0.665588,2.079076,1004.942857,-3.678426,-0.315571,-6.967714,0.385714,1.916525,97.769127,NaN,13.50,45.483402,4.604354,0.972748,2.956000,0.038329,0.509500,0.414406,-3.285714,5.595864,12.000000,2018.0
2019-01-06,0.605755,-1.960404,0.422131,NaN,-4.760121,-0.411274,0.454753,-2.048000,24.695420,0.509465,3.673660,0.231160,0.871861,0.429556,1.876417,1002.851000,1.882986,4.524000,-1.915000,1.900000,1.215902,99.465280,NaN,13.00,67.885875,7.418705,4.387930,10.200000,0.033737,0.112303,0.308713,1.000000,5.616346,12.000000,2018.0

In [50]:
weather.groupby(weather.index.week).mean()

,albedo,balanse,diffus,fd,fluxm,fluxs,global,grmin,ir√∏d,jt010,jt100,jt002,jt020,jt005,jt050,lp,lt,ltmax,ltmin,nb,par,rf,sd,sdman,synlig,uv,vh,vhmax,uv_amount,ir_amount,visible_amount,rounded_lt,log_kelvin_lt,month,year
dato,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,0.522856,-1.156756,0.576491,NaN,-4.352707,-0.373624,0.799852,-9.974687,50.545375,-0.102474,3.127460,-0.523807,0.361046,-0.464063,1.751782,998.739581,-3.687497,-0.831782,-6.712718,2.941279,1.568455,89.064141,3.583333,2.770000,42.732593,6.721982,2.474168,5.229128,0.047428,0.428418,0.323328,-3.535545,5.595608,2.261468,2002.958716
2,0.522913,-1.393911,0.657007,NaN,-3.204601,-0.274939,0.907990,-7.903010,50.425663,-0.049548,2.839872,-0.394562,0.366677,-0.345984,1.587187,999.012283,-2.102223,0.649691,-5.013438,2.857418,1.823948,89.577776,9.333333,4.700000,42.861452,6.712885,2.895971,5.890597,0.054467,0.481189,0.369982,-2.014286,5.601540,1.000000,2003.000000
3,0.534955,-1.305621,0.754501,NaN,-2.319218,-0.200173,1.063812,-9.512694,50.696125,0.042305,2.626501,-0.272326,0.295830,-0.230461,1.512608,998.116354,-1.696596,0.667866,-4.323106,2.786592,2.197719,87.984277,10.214286,15.410000,42.523403,6.766177,2.996521,5.860228,0.064911,0.562355,0.427209,-1.642857,5.603047,1.000000,2003.000000
4,0.694204,-1.335027,1.065792,NaN,-2.891459,-0.249368,1.564763,-10.364082,51.432539,-0.186614,2.453340,-0.587241,0.089503,-0.502708,1.360893,999.449376,-3.547572,-0.747668,-6.902991,2.413369,3.253024,88.717290,3.000000,12.700000,42.020731,6.476717,2.435746,4.994774,0.093741,0.842964,0.630995,-3.342857,5.596228,1.000000,2003.000000
5,0.596118,-1.490626,1.311572,NaN,-4.628362,-0.400731,2.038750,-8.249459,52.062488,-0.332703,2.307180,-0.774556,-0.015306,-0.693731,1.383525,998.125791,-2.438593,0.612244,-5.649161,2.478989,4.300667,86.104037,0.935714,9.100000,41.662841,6.272810,2.702564,5.566054,0.117392,1.117920,0.801950,-2.290476,5.600342,1.589862,2003.000000
6,0.596141,-1.045338,1.605497,NaN,-3.331065,-0.286210,2.452602,-10.457827,50.117533,-0.346004,2.181920,-0.810951,-0.082849,-0.652602,1.279542,997.850371,-3.084740,-0.097032,-6.262429,2.560571,5.250246,86.721755,4.414286,14.220000,43.501894,6.307161,2.685033,5.193810,0.141366,1.294708,1.019441,-2.933333,5.597919,2.000000,2003.000000
7,0.601430,-1.008177,2.031146,NaN,-1.911772,-0.165430,3.262562,-9.858490,50.583161,-0.245576,2.065405,-0.541612,-0.028449,-0.512598,1.207063,1001.247792,-2.733722,0.494221,-6.048332,1.951111,7.049160,84.616113,4.364286,19.220000,43.330036,6.108552,2.575949,5.107500,0.181406,1.736062,1.341484,-2.561905,5.599244,2.000000,2003.000000
8,0.606861,-0.858879,2.495885,NaN,-2.374347,-0.203888,4.202693,-9.496786,51.307058,-0.379866,1.963733,-0.725711,-0.153116,-0.675098,1.119193,999.835317,-1.950301,1.576382,-5.881359,2.096216,9.123938,83.157951,5.457143,18.700000,42.730487,5.974234,2.601336,5.421604,0.230113,2.257372,1.720761,-1.838095,5.602150,2.000000,2003.000000
9,0.570156,-0.535949,2.932772,NaN,-1.233872,-0.105745,5.077131,-8.976439,51.163172,-0.163223,1.882277,-0.407411,-0.014067,-0.374188,1.112312,995.284783,-1.324576,1.989691,-5.026438,1.934536,11.079018,82.852550,6.585714,17.460000,42.990439,5.845480,2.802894,5.652737,0.274846,2.711135,2.092449,-1.252381,5.604476,2.552995,2003.000000
10,0.546767,-0.078233,3.311383,NaN,-0.881354,-0.076580,5.818449,-7.791000,49.763900,0.072934,1.884791,-0.229890,0.162683,-0.097086,1.183701,999.918279,-0.137634,3.308272,-3.814028,2.040957,12.871577,82.172183,8.600000,16.920000,44.390324,5.845967,2.841814,5.791005,0.311010,3.016844,2.464547,-0.223810,5.608875,3.000000,2003.000000
11,0.490489,0.561149,3.900587,NaN,-0.361428,-0.030572,7.858696,-8.639663,51.168193,0.276331,1.862244,-0.015582,0.309268,0.127035,1.250759,1002.941173,0.490132,4.862267,-3.575166,1.373886,17.177924,76.265113,2.764286,20.000000,43.429149,5.402658,2.792895,5.802883,0.395449,4.150157,3.313091,0.414286,5.611175,3.000000,2003.000000
12,0.400694,1.538709,4.061659,NaN,-0.433689,-0.037681,9.393707,-8.011541,51.924589,0.387770,1.849661,0.012462,0.386334,0.220151,1.314851,1001.278366,1.446664,6.008461,-3.044544,1.345918,20.442763,73.506982,0.507143,17.100000,43.058474,5.248705,2.714733,5.752690,0.456036,5.015357,3.891248,1.228571,5.614671,3.000000,2003.000000
13,0.348315,2.527834,4.605123,NaN,1.838932,0.159019,9.994356,-6.901061,51.078411,0.815917,1.885788,0.639822,0.758180,0.789766,1.436300,1000.211029,2.566735,6.980231,-1.832769,2.035372,21.954565,74.704259,0.000000,6.857143,43.681251,5.259345,2.719498,5.698453,0.490918,5.287436,4.235549,2.277512,5.618771,3.193548,2003.000000
14,0.314869,3.378652,5.097409,NaN,3.160712,0.272000,10.700083,-5.001327,50.798041,1.702055,2.053384,1.979510,1.675651,1.928154,1.911267,999.807420,3.398317,7.617000,-0.869060,2.105820,23.522943,73.810897,0.000000,12.000000,43.886659,5.300219,2.911094,5.867918,0.523648,5.598754,4.566906,2.990476,5.621798,3.930876,2003.000000
15,0.254389,4.287453,5.684671,NaN,3.702974,0.320968,11.486538,-3.103563,50.711348,3.242808,2.466611,3.221146,3.069506,3.405159,2.759777,1000.355852,4.796308,9.283350,0.339613,2.294382,25.225587,74.730299,0.000000,5.000000,44.054783,5.233869,2.880744,5.797658,0.555691,5.995459,4.935388,4.352381,5.626840,4.000000,2003.000000
16,0.240504,5.328135,6.145030,NaN,5.382314,0.460679,13.279215,-4.419219,51.560029,4.428688,3.021686,4.889173,4.108348,4.701772,3.650868,1002.870147,5.439978,10.220424,0.603161,1.732604,29.093450,71.794453,0.028571,1.111111,43.369769,5.070202,2.859107,5.975738,0.633700,7.000600,5.644915,4.976190,5.629156,4.000000,2003.000000
17,0.239106,5.544191,6.241318,NaN,6.081458,0.525008,13.799576,-3.454948,50.567780,6.161688,3.689858,6.668506,5.615572,6.459418,4.722881,1005.079143,7.170234,12.275207,2.034903,1.461340,30.580763,72.313667,0.342857,1.110000,44.267860,5.164360,2.671929,5.668396,0.662114,7.165501,5.971960,6.690476,5.635343,4.050691,2003.000000
18,0.229487,6.932959,6.531687,1.466667,6.638207,0.573826,15.837841,-2.742122,50.644478,7.760690,4.536493,8.167127,7.167281,7.947116,5.998709,1003.679291,8.856256,13.596060,3.515396,2.339029,35.148850,68.251503,0.000000,0.000000,44.243109,5.115793,2.807818,6.021547,0.761120,8.203972,6.904073,8.371429,5.641345,4.788018,2003.000000
19,0.232713,7.574760,6.985025,2.794737,6.613101,0.570223,17.238814,-1.106367,50.955564,9.233612,5.448361,9.671392,8.676229,9.488742,7.286907,1001.050052,10.112031,15.103083,4.646645,1.795493,37.938376,67.828726,0.428571,0.600000,44.027619,5.112623,2.860200,6.029950,0.826296,8.933657,7.399934,9.657143,5.645757,5.000000,2003.000000
20,0.234868,7.826878,7.655523,2.826800,6.238767,0.539957,17.676677,0.875806,50.515538,10.089858,6.372377,10.493651,9.520993,10.278352,8.368732,1001.434297,10.550160,15.482645,5.319161,1.965421,39.339970,69.490190,0.000000,0.000000,44.327822,5.150975,3.044549,6.313571,0.879981,9.071944,7.828061,10.057143,5.647331,5.000000,2003.000000
21,0.237721,8.509487,8.131796,3.059236,6.682354,0.576948,18.860735,2.174959,50.772954,11.363822,7.209854,11.756779,10.765769,11.557087,9.409041,1001.111715,12.074679,16.649355,6.794355,1.848762,42.307341,68.704528,0.000000,0.000000,44.157462,5.078295,3.082298,6.374355,0.933939,9.686398,8.322275,11.576190,5.652688,5.000000,2003.000000
22,0.232668,9.047663,7.660236,3.094749,7.492531,0.647194,19.464916,3.698561,50.301002,12.509368,8.048838,12.967734,11.847976,12.740426,10.379042,1002.240404,13.237590,17.930138,7.959959,2.100329,44.224088,68.000953,0.000000,0.000000,44.422110,5.130159,2.759567,5.724177,0.971989,9.948730,8.752270,12.761905,5.656756,5.414747,2003.000000
23,0.231286,9.133250,7.775028,3.550130,6.770897,0.583786,20.138506,3.960949,50.738300,13.662924,8.887435,14.090071,13.042527,13.897358,11.474427,1002.374561,14.361389,19.040645,8.741608,2.347346,45.407773,67.206154,0.000000,NaN,44.110529,5.129968,2.737328,5.837153,0.996730,10.342182,8.913508,13.885714,5.660681,5.995392,2003.000000
24,0.229853,9.401849,8.087208,3.453975,5.915393,0.510609,20.085729,4.832265,50.548216,14.313479,9.677372,14.719006,13.775053,14.530819,12.310659,998.778966,14.445634,18.929447,9.251023,2.542219,45.890225,68.892121,0.000000,NaN,44.203540,5.180159,2.935184,6.026703,1.025595,10.242911,8.983081,13.966667,5.660997,6.000000,2003.000000
25,0.218414,8.950682,8.541154,3.078131,5.663072,0.489094,18.942749,4.640857,50.129404,14.885203,10.408275,15.151048,14.359199,15.086622,12.954968,998.437054,14.606125,18.853226,9.751991,2.931914,42.872317,71.770591,0.000000,NaN,44.543917,5.333544,2.972454,6.050053,0.960414,9.598776,8.319757,14.161905,5.661556,6.000000,2003.000000
26,0.216488,9.113251,8.217942,3.373205,6.527299,0.564738,19.047392,6.013551,49.989914,15.710974,11.021465,16.155405,15.109288,15.899674,13.645094,1000.276152,15.450035,19.880599,10.503032,3.053850,43.023029,73.012879,0.000000,NaN,44.708886,5.302034,2.767129,5.687832,0.958156,9.594970,8.434334,14.947619,5.664483,6.193548,2003.000000
27,0.217470,9.988911,8.407639,3.732106,7.083984,0.605511,19.891526,8.106418,50.024469,16.657146,11.682826,17.514436,15.953916,16.895996,14.374760,999.585345,16.847702,21.416728,11.610134,2.112920,45.384298,73.252274,0.000000,NaN,44.753426,5.222104,2.738890,5.757937,1.002232,9.990597,8.898697,16.400000,5.669311,6.930876,2003.000000
28,0.216947,8.952930,7.873416,3.474292,3.901326,0.337117,18.223479,7.604786,49.715608,16.872148,12.327914,17.549109,16.312712,17.040620,15.006058,998.272889,16.422328,20.658341,11.754585,3.570660,41.837119,74.405256,0.000000,NaN,44.885260,5.399133,2.844697,5.824486,0.941103,9.163441,8.118935,15.942857,5.667854,7.000000,2003.000000
29,0.220604,8.756226,8.295805,3.538784,3.799178,0.328820,17.908223,6.708939,49.640880,17.087760,12.765359,17.755571,16.548022,17.285737,15.279578,1000.203206,16.680990,21.233963,11.448488,2.286825,41.141735,74.570436,0.000000,NaN,45.002859,5.341673,2.454752,5.327156,0.922016,8.916168,7.994958,16.190476,5.668748,7.000000,2003.000000
30,0.218738,8.355049,7.408732,3.386917,4.072077,0.351887,17.327564,8.350276,49.661224,17.442593,13.174548,18.214431,16.905802,17.598012,15.628293,1000.530987,17.498879,22.033041,12.314415,2.669710,39.960389,76.299817,0.000000,NaN,45.019655,5.335710,2.589446,5.583220,0.885372,8.782315,7.823777,17.033333,5.671562,7.013825,2003.000000
31,0.220324,8.114306,7.177591,3.125758,2.752394,0.236624,16.776948,7.335714,49.971412,17.268480,13.534095,17.969300,16.817086,17.219041,15.808440,1000.303742,16.889968,21.500369,11.855705,3.384563,38.698460,77.247072,0.000000,NaN,44.720661,5.306510,2.499023,5.478826,0.859747,8.436278,7.406781,16.395238,5.669467,7.682028,2003.000000
32,0.220668,7.439643,6.756780,2.835879,2.308035,0.199432,15.027911,-64.476429,49.871431,16.797956,13.685963,17.332718,16.428510,16.831530,15.696373,1001.279420,16.296560,20.870276,11.244060,3.441667,34.601025,77.157641,0.000000,NaN,44.748375,5.376092,2.501819,5.344857,0.774436,7.611147,6.684457,15.785714,5.667420,8.000000,2003.000000
33,0.223317,6.725852,6.362336,2.534198,3.170957,0.274192,14.314476,6.541184,50.054803,16.530381,13.783545,17.116476,16.191598,16.518114,15.603143,999.906739,16.015610,20.605392,11.234276,4.210244,32.989539,78.267926,0.000000,NaN,44.561901,5.360003,2.657429,5.534414,0.734860,7.187116,6.263813,15.523810,5.666451,8.000000,2003.000000
34,0.230800,5.882001,5.841619,2.358276,2.191245,0.191134,13.490295,4.650969,50.497725,15.885137,13.757695,16.299637,15.697181,15.873480,15.321404,999.711089,15.006856,19.684470,9.918594,3.203922,31.074414,78.692965,0.000000,NaN,44.186512,5.281593,2.488214,5.416418,0.684668,6.771972,5.801580,14.495238,5.662952,8.000000,2003.000000
35,0.231547,4.821079,5.474162,2.115174,-9.028351,0.013287,11.890087,3.148082,50.358460,14.757549,13.536002,14.921008,14.686668,14.834387,14.326117,1000.633064,13.743080,18.280000,8.840935,3.342488,27.408316,78.350555,0.000000,NaN,44.255057,5.375437,2.587519,5.412627,0.609393,6.084059,5.169504,13.271429,5.658557,8.294931,2003.000000
36,0.230585,3.913677,4.680023,1.781730,-0.453996,-0.009263,10.555581,432.634255,50.391008,14.064613,13.262535,14.237178,14.002772,14.029537,14.145957,1001.276634,13.079091,17.370461,8.321023,3.188454,24.210565,79.769238,0.000000,NaN,44.186433,5.422861,2.599588,5.411879,0.542274,5.469265,4.569523,12.600000,5.656237,8.972350,2003.000000
37,0.236998,3.024159,4.212990,1.893652,-1.921271,-0.166002,9.421078,366.546802,50.773576,12.923680,12.849640,13.210938,12.898303,12.836053,13.399520,1000.996211,11.940259,16.225161,7.065000,2.747892,21.522539,79.062477,0.000000,NaN,43.795134,5.399311,2.716863,5.541000,0.478533,4.813603,3.984634,11.457143,5.652246,9.000000,2003.000000
38,0.234804,2.355731,3.873378,1.484078,-1.412873,-0.121684,7.736924,502.456551,50.368268,12.059570,12.324854,12.169273,12.119715,12.066031,12.642681,1001.637627,11.143633,15.145714,6.890396,3.567561,17.686389,82.581073,0.000000,NaN,44.135604,5.525082,2.720532,5.399727,0.398966,4.020923,3.361318,10.671429,5.649443,9.000000,2003.000000
39,0.238716,1.807541,3.369085,1.196512,-2.966400,-0.249446,7.077151,501.733714,51.125647,10.913794,11.901175,10.861513,11.139957,10.905713,11.977374,1001.246724,9.594024,13.737278,5.167773,3.215728,15.989478,81.422773,0.000000,NaN,43.434949,5.464955,2.594769,5.415546,0.359096,3.755810,3.019507,9.104762,5.643957,9.110599,2003.000000
40,0.240077,1.173581,2.804374,1.050945,-3.256942,-0.281594,5.716486,141.550755,50.964475,9.785393,11.262972,9.583864,10.068729,9.709598,11.032733,999.913816,8.372191,12.429557,4.288600,3.834000,12.889574,83.805290,0.000000,NaN,43.486143,5.554798,2.637743,5.444823,0.290806,3.006046,2.414019,7.857143,5.639634,9.870968,2003.000000
41,0.243216,0.439695,2.618094,1.115302,-4.469781,-0.383182,4.826052,-1.230959,51.379774,8.496738,10.595623,8.267599,8.878887,8.269497,10.108329,1003.497089,7.118100,10.835010,3.191286,3.049286,10.874921,82.722489,0.000000,NaN,43.069634,5.542406,2.533765,5.146152,0.249138,2.542958,1.999742,6.652381,5.635147,10.000000,2003.000000
42,0.234510,-0.043362,1.957172,0.959822,-5.078995,-0.421630,3.505909,-1.739031,49.983645,7.107697,9.862174,6.778406,7.651506,6.956712,9.056477,1002.582519,5.330408,8.430519,1.870295,2.536230,7.888314,85.227959,0.000000,NaN,44.159081,5.856697,2.476088,4.913005,0.184660,1.867306,1.465982,4.928571,5.628727,10.000000,2003.000000
43,0.245539,-0.455371,1.636788,1.010952,-4.079354,-0.368466,2.828564,-1.017510,50.565703,5.949663,8.978593,6.094211,6.495652,5.659579,7.880361,997.830254,5.006777,7.908257,1.556171,4.081606,6.204568,85.750287,0.000000,NaN,43.569748,5.877195,2.885207,5.540069,0.145196,1.530428,1.149405,4.652381,5.627551,10.000000,2003.000000
44,0.249036,-0.580422,1.382999,0.146923,-5.146813,-0.445051,2.278128,-3.053990,51.253840,5.011353,8.265607,4.892054,5.500690,4.742419,7.077380,996.255284,3.824237,6.681009,0.562767,4.591624,5.020196,87.930555,0.444444,1.142857,42.807544,5.940143,2.682409,5.193000,0.120762,1.221138,0.909759,3.528571,5.623287,10.552995,2003.000000
45,0.257968,-0.923795,1.128281,0.000000,-5.537395,-0.478133,1.787044,-3.395735,51.071337,4.093422,7.492162,3.819719,4.605209,3.761110,6.228068,998.169060,2.440683,5.257359,-0.457765,3.499476,3.838537,89.411309,0.846154,0.000000,42.962478,6.046721,2.586600,4.956532,0.094744,0.947784,0.694131,2.228571,5.618274,11.000000,2003.000000
46,0.316698,-1.136355,0.973157,0.000000,-5.351893,-0.462671,1.340906,-3.975163,51.410987,3.162282,6.768638,2.878585,3.634549,2.909621,5.396757,998.974999,1.803595,4.144456,-0.974281,3.569688,2.878112,89.974083,3.000000,1.850000,42.472706,6.136262,2.632863,5.049139,0.073522,0.738180,0.535850,1.614286,5.615964,11.000000,2003.000000
47,0.368834,-1.298441,0.773918,0.000000,-4.832086,-0.417805,1.024675,-5.129102,50.265481,2.404341,6.077986,2.288929,2.899747,2.085867,4.602407,998.486756,0.421129,2.730055,-2.582419,3.457037,2.163235,88.655362,0.142857,0.788889,43.355310,6.410539,2.904843,5.646137,0.059266,0.538226,0.410478,0.342857,5.610879,11.000000,2003.000000
48,0.411937,-1.233426,0.667271,0.000000,-5.146597,-0.444379,0.893224,-6.886602,49.906319,1.693128,5.402325,1.398644,2.154296,1.386529,3.894785,998.591144,-0.656140,1.798687,-3.654650,2.975936,1.854650,89.546585,3.000000,2.100000,43.726425,6.438409,2.583250,5.133758,0.050469,0.480488,0.377756,-0.595238,5.606897,11.294931,2003.000000
49,0.479251,-1.379716,0.589326,0.000000,-4.289759,-0.370551,0.774637,-8.251724,49.312270,1.362393,4.803718,1.104840,1.761486,1.038066,3.432396,996.159978,-0.461350,1.894184,-3.620714,3.083607,1.531715,89.003328,2.142857,2.300000,44.282857,6.426493,2.729654,5.859323,0.045029,0.418243,0.336290,-0.414286,5.607640,11.972350,2003.000000
50,0.438319,-1.435015,0.532340,0.000000,-5.213005,-0.450901,0.739629,-8.750245,51.848407,0.887800,4.340336,0.572717,1.293706,0.528324,2.984707,1001.561605,-2.120296,0.537691,-5.505862,2.190449,1.432383,90.270089,4.000000,10.800000,41.913820,6.239978,2.295421,4.871240,0.041662,0.409740,0.295446,-1.980952,5.601515,12.000000,2003.000000
51,0.457352,-1.407621,0.506376,0.000000,-5.448861,-0.470908,0.683231,-8.702612,52.026453,0.292529,3.917662,-0.212784,0.745491,-0.075834,2.515520,1000.833800,-2.579881,0.210544,-5.731770,1.825714,1.347399,90.115996,6.285714,13.800000,41.625128,6.439210,2.647563,5.580786,0.039407,0.375365,0.271254,-2.414286,5.599739,12.000000,2003.000000
52,0.519752,-1.272232,0.525050,0.000000,-4.077459,-0.352784,0.698406,-7.897633,49.991906,0.117358,3.548890,-0.287825,0.538424,-0.211537,2.170991,993.724333,-2.603342,-0.001364,-5.761194,2.941667,1.369151,90.196089,3.250000,6.800000,43.510517,6.525982,2.790219,5.741380,0.041143,0.380950,0.291628,-2.433962,5.599685,11.442396,2003.050691
53,0.517997,-1.129333,0.478275,0.000000,0.306927,0.028850,0.637192,-13.816750,50.895935,0.212252,3.597405,-0.007907,0.573007,-0.205040,2.265635,1000.564893,-3.137164,-0.388684,-5.640368,5.446429,1.319917,92.071096,0.000000,NaN,42.538504,6.565561,3.064719,5.987083,0.038694,0.346957,0.251542,-3.085714,5.597639,7.078947,2002.736842

## Saving a Pandas DataFrame

In [88]:
weekly_weather_mean.to_excel('weekly_weather.xlsx')

## Statistics in Python

We can use several tools for statistics in Python, the two most common are StatsModels and scipy.stats. We will use the former to perform a simple ANOVA analysis

### One-way ANOVA
We start by performing an ANOVA to test whether the month variable is statistically significant.

In [52]:
from statsmodels.formula.api import ols

In [59]:
model = ols('lt ~ C(month, Treatment)', data=weather).fit()

In [58]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                     lt   R-squared:                       0.767
Model:                            OLS   Adj. R-squared:                  0.767
Method:                 Least Squares   F-statistic:                     3272.
Date:                Fri, 21 Jun 2019   Prob (F-statistic):               0.00
Time:                        11:53:04   Log-Likelihood:                -30406.
No. Observations:               10957   AIC:                         6.084e+04
Df Residuals:                   10945   BIC:                         6.092e+04
Df Model:                          11
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept         -2.6485      0.127    -20.799      0.000      -2.898      -2.399
C(month)[T.2]      0.3220      0.184      1.747      0.081      -0.039       0.683
C(month)[T.3]      3.3119      0.180     18.386      0.000       2.959       3.665
C(month)[T.4]      7.9230      0.182     43.635      0.000       7.567       8.279
C(month)[T.5]     13.4978      0.180     74.955      0.000      13.145      13.851
C(month)[T.6]     17.2184      0.182     94.829      0.000      16.863      17.574
C(month)[T.7]     19.4750      0.180    108.147      0.000      19.122      19.828
C(month)[T.8]     18.2850      0.180    101.538      0.000      17.932      18.638
C(month)[T.9]     14.1689      0.182     78.034      0.000      13.813      14.525
C(month)[T.10]     8.7808      0.180     48.761      0.000       8.428       9.134
C(month)[T.11]     4.2212      0.182     23.248      0.000       3.865       4.577
C(month)[T.12]     0.5790      0.180      3.215      0.001       0.226       0.932
==============================================================================
Omnibus:                      522.087   Durbin-Watson:                   0.397
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              747.836
Skew:                          -0.447   Prob(JB):                    4.07e-163
Kurtosis:                       3.916   Cond. No.                         12.8
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [62]:
model = ols('lt ~ 0 + C(month, Treatment)', data=weather).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                     lt   R-squared:                       0.767
Model:                            OLS   Adj. R-squared:                  0.767
Method:                 Least Squares   F-statistic:                     3272.
Date:                Fri, 21 Jun 2019   Prob (F-statistic):               0.00
Time:                        11:55:36   Log-Likelihood:                -30406.
No. Observations:               10957   AIC:                         6.084e+04
Df Residuals:                   10945   BIC:                         6.092e+04
Df Model:                          11
Covariance Type:            nonrobust
===========================================================================================
                              coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------
C(month, Treatment)[1]     -2.6485      0.127    -20.799      0.000      -2.898      -2.399
C(month, Treatment)[2]     -2.3264      0.133    -17.446      0.000      -2.588      -2.065
C(month, Treatment)[3]      0.6634      0.127      5.207      0.000       0.414       0.913
C(month, Treatment)[4]      5.2745      0.129     40.749      0.000       5.021       5.528
C(month, Treatment)[5]     10.8493      0.127     85.203      0.000      10.600      11.099
C(month, Treatment)[6]     14.5699      0.129    112.561      0.000      14.316      14.824
C(month, Treatment)[7]     16.8265      0.127    132.144      0.000      16.577      17.076
C(month, Treatment)[8]     15.6365      0.127    122.798      0.000      15.387      15.886
C(month, Treatment)[9]     11.5204      0.129     89.001      0.000      11.267      11.774
C(month, Treatment)[10]     6.1323      0.127     48.159      0.000       5.883       6.382
C(month, Treatment)[11]     1.5727      0.129     12.150      0.000       1.319       1.826
C(month, Treatment)[12]    -2.0695      0.127    -16.252      0.000      -2.319      -1.820
==============================================================================
Omnibus:                      522.087   Durbin-Watson:                   0.397
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              747.836
Skew:                          -0.447   Prob(JB):                    4.07e-163
Kurtosis:                       3.916   Cond. No.                         1.05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

Converting this to a one-way ANOVA table.

In [64]:
from statsmodels.stats.anova import anova_lm

In [65]:
anova_lm(model)

                          df         sum_sq       mean_sq            F  PR(>F)
C(month, Treatment)     12.0  988409.973068  82367.497756  5462.297311     0.0
Residual             10945.0  165042.693857     15.079278          NaN     NaN

## Some datavisualisation with Pandas

In [83]:
%matplotlib notebook

In [84]:
weather.plot.scatter(x='lt', y='jt100', s=1)  # s <- size