# Introduction to data analysis with Python and Pandas
### Yngve Mardal Moe

## Agenda:

 1. Loading data from excel
 2. Computing summary statistics from this data
 3. Grouping the data
 4. Perfroming statistical tests on the data
 5. Creating simple plots for exploratory analysis

## Part 1: Loading data from Excel
Before we can load data from Excel, we must import the Pandas module, which implements data frames in Python. You can think of a data frame as an Excel spreadsheet in Python.

In [1]:
import pandas as pd

In [2]:
weather = pd.read_excel('weather_data.xlsx')

To inspect variable's values, we have a Python cell with that variable's name, like this:

In [3]:
weather

,Unnamed: 0,dato,albedo,balanse,diffus,fd,fluxm,fluxs,global,grmin,...,nb,par,rf,sd,sdman,synlig,uv,vh,vhmax,vr
0,0,1988-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1988-01-02 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,1988-01-03 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,1988-01-04 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,1988-01-05 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5,1988-01-06 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,6,1988-01-07 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,7,1988-01-08 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,8,1988-01-09 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,9,1988-01-10 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,10,1988-01-11 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,11,1988-01-12 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,12,1988-01-13 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,13,1988-01-14 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,14,1988-01-15 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,15,1988-01-16 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,16,1988-01-17 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,17,1988-01-18 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,18,1988-01-19 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,19,1988-01-20 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,20,1988-01-21 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,21,1988-01-22 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,22,1988-01-23 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,23,1988-01-24 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,24,1988-01-25 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,25,1988-01-26 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,26,1988-01-27 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,27,1988-01-28 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,28,1988-01-29 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,29,1988-01-30 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11293,11293,2018-12-02 00:10:00,0.172544,-0.561167,0.460905,NaN,3.291177,0.284358,0.421363,-0.038,...,12.0,0.853293,99.96528,NaN,NaN,29.562620,4.857520,2.898785,4.087,Ø
11294,11294,2018-12-03 22:10:00,0.108175,0.017563,0.393376,NaN,6.200490,0.535722,0.384140,4.363,...,8.6,0.906667,100.00000,NaN,0.0,49.578825,5.572815,1.775410,4.439,Ø
11295,11295,2018-12-04 00:10:00,0.221060,-3.654298,0.729919,NaN,-7.121333,-0.615283,0.811693,-7.964,...,4.7,1.853481,72.02778,NaN,0.0,56.351354,5.366416,3.472875,6.210,NV
11296,11296,2018-12-05 00:10:00,0.223798,-4.569000,2.154242,NaN,-14.243610,-1.230648,2.455054,-12.370,...,0.0,3.244609,75.22916,NaN,0.0,43.363145,2.417055,1.735375,4.125,S
11297,11297,2018-12-06 00:10:00,0.291290,-1.070306,0.619717,NaN,-10.252400,-0.885807,0.556293,-11.660,...,7.4,1.142509,98.10416,NaN,0.0,27.872674,4.789706,NaN,NaN,NaN
11298,11298,2018-12-07 00:10:00,0.784074,-0.066208,0.530192,NaN,-8.185083,-0.707191,0.498974,-1.009,...,8.5,1.359652,99.86806,NaN,10.0,47.503921,7.088299,NaN,NaN,NaN
11299,11299,2018-12-08 00:10:00,2.595680,-0.668164,0.611927,NaN,-7.103809,-0.613769,0.291119,-3.369,...,4.4,0.854312,99.50000,NaN,NaN,63.582288,6.657282,2.113271,4.013,N
11300,11300,2018-12-09 00:10:00,0.722303,-1.521313,0.822890,NaN,-6.286635,-0.543165,1.090572,-13.660,...,0.2,2.067057,97.26389,NaN,NaN,49.398304,4.815586,1.510097,3.812,NV
11301,11301,2018-12-10 00:10:00,0.751300,-2.938722,0.779939,NaN,-5.871264,-0.507277,0.849219,-10.030,...,0.0,2.018458,76.17361,NaN,19.0,47.459701,6.518459,2.992194,6.235,NV
11302,11302,2018-12-11 00:10:00,0.707177,-2.817427,0.563883,NaN,-5.402417,-0.466769,1.406764,-14.990,...,0.0,2.828161,75.13465,NaN,18.0,32.623007,4.175883,2.616361,4.832,N
11303,11303,2018-12-12 22:10:00,0.552113,-1.607687,0.568240,NaN,-5.413264,-0.467706,1.891487,-17.580,...,0.0,3.027292,98.19514,NaN,17.0,55.550530,3.112250,NaN,NaN,NaN
11304,11304,2018-12-13 22:10:00,0.788596,-0.294080,0.486171,NaN,-5.202694,-0.449513,0.468615,-6.274,...,0.2,1.268141,95.26389,NaN,17.0,56.518423,7.329727,2.540396,4.167,N
11305,11305,2018-12-14 00:10:00,0.757965,-0.361724,0.496776,NaN,-4.907326,-0.423993,0.487178,-9.380,...,0.0,1.302357,91.85764,NaN,17.0,55.553818,7.039352,1.822951,3.288,N
11306,11306,2018-12-15 00:10:00,0.790336,-0.451263,0.465728,NaN,-4.855365,-0.419503,0.449248,-8.450,...,1.0,1.207986,93.70764,NaN,NaN,56.633357,7.238503,1.509257,2.697,N
11307,11307,2018-12-16 00:10:00,0.748424,-0.738231,0.456784,NaN,-4.251715,-0.367348,0.455249,-2.827,...,1.5,1.168568,93.99514,NaN,NaN,55.882061,6.852209,2.667333,4.059,Ø
11308,11308,2018-12-17 22:10:00,0.725240,-0.873497,1.135281,NaN,-3.555465,-0.307192,1.270855,-11.490,...,1.1,2.706872,99.37917,NaN,20.0,44.146908,4.064932,1.076243,2.788,N
11309,11309,2018-12-18 00:10:00,0.837900,-0.271274,0.598734,NaN,-3.485184,-0.301120,0.559267,-4.897,...,0.6,1.501040,99.65278,NaN,19.0,48.695974,6.620986,0.909535,2.079,N
11310,11310,2018-12-19 00:10:00,0.711765,-0.527623,0.233392,NaN,-3.408437,-0.294489,0.225485,-3.135,...,3.3,0.626588,99.52847,NaN,19.0,44.108957,7.993443,1.842535,3.027,Ø
11311,11311,2018-12-20 00:10:00,0.816733,-1.097929,0.187892,NaN,-3.567246,-0.308210,0.174457,-0.207,...,0.7,0.509647,96.31389,NaN,16.0,63.549099,8.211211,2.526660,3.815,Ø
11312,11312,2018-12-21 22:10:00,0.701868,-0.515824,0.375762,NaN,-3.557246,-0.307346,0.364153,-2.831,...,0.5,0.999070,87.70069,NaN,14.0,55.053363,7.073397,2.953264,3.941,NØ
11313,11313,2018-12-22 00:10:00,0.752722,-0.722865,0.338192,NaN,-3.582708,-0.309546,0.323534,-5.060,...,0.0,0.911864,83.18840,NaN,NaN,58.624908,7.161972,1.692528,3.571,N
11314,11314,2018-12-23 00:10:00,0.661407,-1.322467,0.896327,NaN,-4.295028,-0.371090,0.915799,-17.800,...,0.0,2.105036,92.95972,NaN,NaN,46.528415,4.740515,0.725639,1.695,NV
11315,11315,2018-12-24 00:10:00,0.684347,-0.834153,0.873651,NaN,-6.058024,-0.523413,0.984602,-18.520,...,0.0,1.962061,98.82570,NaN,NaN,41.302402,4.434298,NaN,NaN,NaN
11316,11316,2018-12-25 00:10:00,0.669676,-2.126344,0.477907,NaN,-5.256490,-0.454161,0.606802,-10.280,...,0.0,1.571380,91.06236,NaN,14.0,62.261698,5.535252,1.300396,4.915,Ø
11317,11317,2018-12-26 00:10:00,0.684592,-0.875690,0.503858,NaN,-4.962451,-0.428756,0.461216,-11.080,...,0.5,0.966637,96.40625,NaN,NaN,33.970474,5.182296,0.841278,1.848,Ø
11318,11318,2018-12-27 00:10:00,0.648644,-1.037384,0.520922,NaN,-3.859840,-0.333490,0.542782,-7.409,...,1.8,1.339207,99.99931,NaN,13.0,55.943656,5.693554,0.776569,2.105,NØ
11319,11319,2018-12-28 00:10:00,0.458021,-1.520098,0.991158,NaN,-4.974732,-0.429817,1.719382,-12.720,...,0.0,2.614267,98.92361,NaN,NaN,39.267257,2.795783,NaN,NaN,NaN
11320,11320,2018-12-29 00:10:00,0.879624,-0.617260,0.577520,NaN,-5.268014,-0.455156,0.613190,-11.050,...,0.1,1.723672,99.43750,NaN,NaN,47.482347,5.616233,NaN,NaN,NaN
11321,11321,2018-12-30 00:10:00,0.476756,-0.901978,0.896532,NaN,-5.038892,-0.435360,1.807672,-11.050,...,0.3,3.238451,99.72916,NaN,NaN,38.155978,2.973062,NaN,NaN,NaN
11322,11322,2018-12-31 22:10:00,0.605755,-1.960404,0.422131,NaN,-4.760121,-0.411274,0.454753,-2.048,...,1.9,1.215902,99.46528,NaN,13.0,67.885875,7.418705,4.387930,10.200,S

We see that Pandas contracts many of the rows into a [...]. We can change this by modifying the Pandas settings

In [4]:
pd.set_option('max_columns', 100)

In [5]:
weather

,Unnamed: 0,dato,albedo,balanse,diffus,fd,fluxm,fluxs,global,grmin,irød,jt010,jt100,jt002,jt020,jt005,jt050,lp,lt,ltmax,ltmin,nb,par,rf,sd,sdman,synlig,uv,vh,vhmax,vr
0,0,1988-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.100000,5.900,3.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1988-01-02 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.700000,5.300,1.500,20.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,1988-01-03 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.300000,2.100,0.200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,1988-01-04 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.100000,0.400,-0.100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,1988-01-05 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.100000,0.600,-0.500,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5,1988-01-06 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.500000,0.200,-1.400,3.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,6,1988-01-07 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.300000,0.200,-5.600,0.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,7,1988-01-08 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-6.200000,-4.500,-10.700,0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,8,1988-01-09 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.500000,2.900,-4.900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,9,1988-01-10 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.200000,5.800,1.900,5.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,10,1988-01-11 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.700000,3.600,0.900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,11,1988-01-12 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.200000,4.300,-2.800,2.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,12,1988-01-13 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.600000,4.600,3.000,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,13,1988-01-14 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.200000,3.900,2.300,1.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,14,1988-01-15 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.100000,4.300,1.800,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,15,1988-01-16 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.700000,1.800,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,16,1988-01-17 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.400000,1.300,0.000,1.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,17,1988-01-18 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.300000,2.400,0.100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,18,1988-01-19 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.400000,3.000,-0.800,7.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,19,1988-01-20 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.700000,2.300,1.000,5.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,20,1988-01-21 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.900000,3.500,0.300,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,21,1988-01-22 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,3.500,0.400,9.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,22,1988-01-23 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.400,-1.100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,23,1988-01-24 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.100000,-0.400,-1.700,8.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,24,1988-01-25 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.400,-0.700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,25,1988-01-26 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.600000,0.000,-0.800,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,26,1988-01-27 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.300000,0.300,-0.500,12.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,27,1988-01-28 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.300000,0.700,0.000,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,28,1988-01-29 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.900000,0.100,-2.800,2.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,29,1988-01-30 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-3.300000,-2.800,-3.900,16.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11293,11293,2018-12-02 00:10:00,0.172544,-0.561167,0.460905,NaN,3.291177,0.284358,0.421363,-0.038,65.57986,1.039569,5.445042,0.737660,1.422431,0.832167,2.793424,984.5229,4.220986,4.773,2.480,12.0,0.853293,99.96528,NaN,NaN,29.562620,4.857520,2.898785,4.087,Ø
11294,11294,2018-12-03 22:10:00,0.108175,0.017563,0.393376,NaN,6.200490,0.535722,0.384140,4.363,44.84836,2.410222,5.309354,2.739563,2.247729,2.601854,2.943118,973.7991,5.776055,7.378,4.749,8.6,0.906667,100.00000,NaN,0.0,49.578825,5.572815,1.775410,4.439,Ø
11295,11295,2018-12-04 00:10:00,0.221060,-3.654298,0.729919,NaN,-7.121333,-0.615283,0.811693,-7.964,38.28223,3.107917,5.253472,2.774570,2.969076,2.952181,3.321132,987.1948,3.013479,4.880,-1.672,4.7,1.853481,72.02778,NaN,0.0,56.351354,5.366416,3.472875,6.210,NV
11296,11296,2018-12-05 00:10:00,0.223798,-4.569000,2.154242,NaN,-14.243610,-1.230648,2.455054,-12.370,54.21980,1.867806,5.264812,0.946854,2.501972,1.445979,3.536944,1004.8450,-2.114458,0.578,-5.752,0.0,3.244609,75.22916,NaN,0.0,43.363145,2.417055,1.735375,4.125,S
11297,11297,2018-12-06 00:10:00,0.291290,-1.070306,0.619717,NaN,-10.252400,-0.885807,0.556293,-11.660,67.33762,1.261222,5.252576,0.446042,1.917250,0.868993,3.374979,998.6358,-2.138097,0.326,-5.997,7.4,1.142509,98.10416,NaN,0.0,27.872674,4.789706,NaN,NaN,NaN
11298,11298,2018-12-07 00:10:00,0.784074,-0.066208,0.530192,NaN,-8.185083,-0.707191,0.498974,-1.009,45.40778,0.994896,5.191764,0.393667,1.603500,0.723257,3.100965,983.6542,-0.204861,0.300,-0.596,8.5,1.359652,99.86806,NaN,10.0,47.503921,7.088299,NaN,NaN,NaN
11299,11299,2018-12-08 00:10:00,2.595680,-0.668164,0.611927,NaN,-7.103809,-0.613769,0.291119,-3.369,29.76043,0.851104,5.081000,0.394417,1.494625,0.703340,2.917847,968.7765,-0.546965,0.081,-1.948,4.4,0.854312,99.50000,NaN,NaN,63.582288,6.657282,2.113271,4.013,N
11300,11300,2018-12-09 00:10:00,0.722303,-1.521313,0.822890,NaN,-6.286635,-0.543165,1.090572,-13.660,45.78611,0.918299,4.978882,0.438750,1.471201,0.734437,2.795486,971.3123,-2.675701,-0.425,-5.615,0.2,2.067057,97.26389,NaN,NaN,49.398304,4.815586,1.510097,3.812,NV
11301,11301,2018-12-10 00:10:00,0.751300,-2.938722,0.779939,NaN,-5.871264,-0.507277,0.849219,-10.030,46.02184,1.465993,4.872576,0.506958,1.459549,0.804660,2.696285,988.6810,1.157403,3.766,-4.173,0.0,2.018458,76.17361,NaN,19.0,47.459701,6.518459,2.992194,6.235,NV
11302,11302,2018-12-11 00:10:00,0.707177,-2.817427,0.563883,NaN,-5.402417,-0.466769,1.406764,-14.990,63.20111,1.901778,4.759597,0.588812,1.461493,0.863778,2.646722,1009.6670,0.758868,3.735,-6.743,0.0,2.828161,75.13465,NaN,18.0,32.623007,4.175883,2.616361,4.832,N
11303,11303,2018-12-12 22:10:00,0.552113,-1.607687,0.568240,NaN,-5.413264,-0.467706,1.891487,-17.580,41.33722,1.466694,4.693028,0.650132,1.483299,0.917424,2.607875,1020.4720,-6.032153,-2.048,-9.460,0.0,3.027292,98.19514,NaN,17.0,55.550530,3.112250,NaN,NaN,NaN
11304,11304,2018-12-13 22:10:00,0.788596,-0.294080,0.486171,NaN,-5.202694,-0.449513,0.468615,-6.274,36.15185,1.682854,4.605542,0.644826,1.459250,0.901535,2.530319,1022.9900,-5.462028,-4.929,-6.217,0.2,1.268141,95.26389,NaN,17.0,56.518423,7.329727,2.540396,4.167,N
11305,11305,2018-12-14 00:10:00,0.757965,-0.361724,0.496776,NaN,-4.907326,-0.423993,0.487178,-9.380,37.40683,1.807743,4.520215,0.668917,1.401708,0.912125,2.456951,1023.6290,-7.549840,-6.223,-9.140,0.0,1.302357,91.85764,NaN,17.0,55.553818,7.039352,1.822951,3.288,N
11306,11306,2018-12-15 00:10:00,0.790336,-0.451263,0.465728,NaN,-4.855365,-0.419503,0.449248,-8.450,36.12814,0.982826,4.422111,0.677195,1.370590,0.907062,2.394778,1021.1680,-5.627292,-1.944,-8.540,1.0,1.207986,93.70764,NaN,NaN,56.633357,7.238503,1.509257,2.697,N
11307,11307,2018-12-16 00:10:00,0.748424,-0.738231,0.456784,NaN,-4.251715,-0.367348,0.455249,-2.827,37.26573,0.935063,4.357625,0.675847,1.355417,0.904215,2.346479,1009.5020,-0.505632,0.187,-2.040,1.5,1.168568,93.99514,NaN,NaN,55.882061,6.852209,2.667333,4.059,Ø
11308,11308,2018-12-17 22:10:00,0.725240,-0.873497,1.135281,NaN,-3.555465,-0.307192,1.270855,-11.490,51.78816,1.007007,4.282896,0.798264,1.367646,0.963757,2.335264,1007.1630,-3.102604,-1.375,-5.237,1.1,2.706872,99.37917,NaN,20.0,44.146908,4.064932,1.076243,2.788,N
11309,11309,2018-12-18 00:10:00,0.837900,-0.271274,0.598734,NaN,-3.485184,-0.301120,0.559267,-4.897,44.68304,1.072222,4.216403,0.854632,1.397778,1.036910,2.322208,1011.2080,-4.164535,-2.751,-5.016,0.6,1.501040,99.65278,NaN,19.0,48.695974,6.620986,0.909535,2.079,N
11310,11310,2018-12-19 00:10:00,0.711765,-0.527623,0.233392,NaN,-3.408437,-0.294489,0.225485,-3.135,47.89760,1.196875,4.164993,0.916305,1.438201,1.072410,2.313292,1006.1320,-0.015722,1.486,-2.931,3.3,0.626588,99.52847,NaN,19.0,44.108957,7.993443,1.842535,3.027,Ø
11311,11311,2018-12-20 00:10:00,0.816733,-1.097929,0.187892,NaN,-3.567246,-0.308210,0.174457,-0.207,28.23969,1.282688,4.107924,0.955861,1.462951,1.109847,2.316410,1004.1960,0.983722,1.450,0.062,0.7,0.509647,96.31389,NaN,16.0,63.549099,8.211211,2.526660,3.815,Ø
11312,11312,2018-12-21 22:10:00,0.701868,-0.515824,0.375762,NaN,-3.557246,-0.307346,0.364153,-2.831,37.87324,1.750306,4.079236,0.992243,1.478194,1.158118,2.314333,1000.1270,-1.064292,0.037,-2.503,0.5,0.999070,87.70069,NaN,14.0,55.053363,7.073397,2.953264,3.941,NØ
11313,11313,2018-12-22 00:10:00,0.752722,-0.722865,0.338192,NaN,-3.582708,-0.309546,0.323534,-5.060,34.21312,2.527778,4.049812,1.008451,1.497750,1.178979,2.323424,999.5062,-3.300639,-2.533,-4.271,0.0,0.911864,83.18840,NaN,NaN,58.624908,7.161972,1.692528,3.571,N
11314,11314,2018-12-23 00:10:00,0.661407,-1.322467,0.896327,NaN,-4.295028,-0.371090,0.915799,-17.800,48.73107,1.758174,4.039521,0.904299,1.482236,1.099333,2.309347,1003.3720,-5.367910,-3.273,-10.830,0.0,2.105036,92.95972,NaN,NaN,46.528415,4.740515,0.725639,1.695,NV
11315,11315,2018-12-24 00:10:00,0.684347,-0.834153,0.873651,NaN,-6.058024,-0.523413,0.984602,-18.520,54.26330,1.096764,3.988354,0.650195,1.379646,0.887687,2.250625,1007.2970,-7.872431,-2.061,-12.770,0.0,1.962061,98.82570,NaN,NaN,41.302402,4.434298,NaN,NaN,NaN
11316,11316,2018-12-25 00:10:00,0.669676,-2.126344,0.477907,NaN,-5.256490,-0.454161,0.606802,-10.280,32.20305,0.885320,3.954708,0.493354,1.217285,0.752347,2.191604,1002.8690,-1.082090,5.844,-5.023,0.0,1.571380,91.06236,NaN,14.0,62.261698,5.535252,1.300396,4.915,Ø
11317,11317,2018-12-26 00:10:00,0.684592,-0.875690,0.503858,NaN,-4.962451,-0.428756,0.461216,-11.080,60.84723,0.722833,3.893701,0.442549,1.146104,0.672882,2.096153,1004.6770,-1.380521,0.976,-5.676,0.5,0.966637,96.40625,NaN,NaN,33.970474,5.182296,0.841278,1.848,Ø
11318,11318,2018-12-27 00:10:00,0.648644,-1.037384,0.520922,NaN,-3.859840,-0.333490,0.542782,-7.409,38.36279,0.694146,3.838215,0.449583,1.094819,0.664396,2.068958,1000.7770,-1.244958,0.695,-4.085,1.8,1.339207,99.99931,NaN,13.0,55.943656,5.693554,0.776569,2.105,NØ
11319,11319,2018-12-28 00:10:00,0.458021,-1.520098,0.991158,NaN,-4.974732,-0.429817,1.719382,-12.720,57.93696,0.775146,3.810514,0.444639,1.082417,0.668576,2.049465,1005.8380,-6.232451,-4.125,-8.200,0.0,2.614267,98.92361,NaN,NaN,39.267257,2.795783,NaN,NaN,NaN
11320,11320,2018-12-29 00:10:00,0.879624,-0.617260,0.577520,NaN,-5.268014,-0.455156,0.613190,-11.050,46.90142,0.660903,3.759500,0.332375,1.023354,0.542597,1.984889,1003.8350,-4.474945,-1.800,-7.296,0.1,1.723672,99.43750,NaN,NaN,47.482347,5.616233,NaN,NaN,NaN
11321,11321,2018-12-30 00:10:00,0.476756,-0.901978,0.896532,NaN,-5.038892,-0.435360,1.807672,-11.050,58.87096,0.611986,3.728389,0.261771,0.933201,0.470632,1.911840,1009.3070,-3.461583,-1.738,-5.724,0.3,3.238451,99.72916,NaN,NaN,38.155978,2.973062,NaN,NaN,NaN
11322,11322,2018-12-31 22:10:00,0.605755,-1.960404,0.422131,NaN,-4.760121,-0.411274,0.454753,-2.048,24.69542,0.509465,3.673660,0.231160,0.871861,0.429556,1.876417,1002.8510,1.882986,4.524,-1.915,1.9,1.215902,99.46528,NaN,13.0,67.885875,7.418705,4.387930,10.200,S

We can look at the top five rows through the ``head()`` function.

In [6]:
weather.head()

,Unnamed: 0,dato,albedo,balanse,diffus,fd,fluxm,fluxs,global,grmin,irød,jt010,jt100,jt002,jt020,jt005,jt050,lp,lt,ltmax,ltmin,nb,par,rf,sd,sdman,synlig,uv,vh,vhmax,vr
0,0,1988-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.1,5.9,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1988-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.7,5.3,1.5,20.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,1988-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.3,2.1,0.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,1988-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.1,0.4,-0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,1988-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.1,0.6,-0.5,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Similarly, we can look at the last five rows through the ``tail()`` function

In [7]:
weather.tail()

,Unnamed: 0,dato,albedo,balanse,diffus,fd,fluxm,fluxs,global,grmin,irød,jt010,jt100,jt002,jt020,jt005,jt050,lp,lt,ltmax,ltmin,nb,par,rf,sd,sdman,synlig,uv,vh,vhmax,vr
11318,11318,2018-12-27 00:10:00,0.648644,-1.037384,0.520922,NaN,-3.859840,-0.333490,0.542782,-7.409,38.36279,0.694146,3.838215,0.449583,1.094819,0.664396,2.068958,1000.777,-1.244958,0.695,-4.085,1.8,1.339207,99.99931,NaN,13.0,55.943656,5.693554,0.776569,2.105,NØ
11319,11319,2018-12-28 00:10:00,0.458021,-1.520098,0.991158,NaN,-4.974732,-0.429817,1.719382,-12.720,57.93696,0.775146,3.810514,0.444639,1.082417,0.668576,2.049465,1005.838,-6.232451,-4.125,-8.200,0.0,2.614267,98.92361,NaN,NaN,39.267257,2.795783,NaN,NaN,NaN
11320,11320,2018-12-29 00:10:00,0.879624,-0.617260,0.577520,NaN,-5.268014,-0.455156,0.613190,-11.050,46.90142,0.660903,3.759500,0.332375,1.023354,0.542597,1.984889,1003.835,-4.474945,-1.800,-7.296,0.1,1.723672,99.43750,NaN,NaN,47.482347,5.616233,NaN,NaN,NaN
11321,11321,2018-12-30 00:10:00,0.476756,-0.901978,0.896532,NaN,-5.038892,-0.435360,1.807672,-11.050,58.87096,0.611986,3.728389,0.261771,0.933201,0.470632,1.911840,1009.307,-3.461583,-1.738,-5.724,0.3,3.238451,99.72916,NaN,NaN,38.155978,2.973062,NaN,NaN,NaN
11322,11322,2018-12-31 22:10:00,0.605755,-1.960404,0.422131,NaN,-4.760121,-0.411274,0.454753,-2.048,24.69542,0.509465,3.673660,0.231160,0.871861,0.429556,1.876417,1002.851,1.882986,4.524,-1.915,1.9,1.215902,99.46528,NaN,13.0,67.885875,7.418705,4.387930,10.200,S

Now, notice that the data frame has a column "dato" that contains the date of each measurement as well as an uninformative index (numbers from 0 through to 11323). We can remove the index and use the dates instead with the ``set_index`` method.

In [8]:
weather = weather.set_index('dato')

Let us now look at the head and tail of this data frame once more

In [9]:
weather.head()

,Unnamed: 0,albedo,balanse,diffus,fd,fluxm,fluxs,global,grmin,irød,jt010,jt100,jt002,jt020,jt005,jt050,lp,lt,ltmax,ltmin,nb,par,rf,sd,sdman,synlig,uv,vh,vhmax,vr
dato,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1988-01-01,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.1,5.9,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988-01-02,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.7,5.3,1.5,20.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988-01-03,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.3,2.1,0.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988-01-04,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.1,0.4,-0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1988-01-05,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.1,0.6,-0.5,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
weather.tail()

,Unnamed: 0,albedo,balanse,diffus,fd,fluxm,fluxs,global,grmin,irød,jt010,jt100,jt002,jt020,jt005,jt050,lp,lt,ltmax,ltmin,nb,par,rf,sd,sdman,synlig,uv,vh,vhmax,vr
dato,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2018-12-27 00:10:00,11318,0.648644,-1.037384,0.520922,NaN,-3.859840,-0.333490,0.542782,-7.409,38.36279,0.694146,3.838215,0.449583,1.094819,0.664396,2.068958,1000.777,-1.244958,0.695,-4.085,1.8,1.339207,99.99931,NaN,13.0,55.943656,5.693554,0.776569,2.105,NØ
2018-12-28 00:10:00,11319,0.458021,-1.520098,0.991158,NaN,-4.974732,-0.429817,1.719382,-12.720,57.93696,0.775146,3.810514,0.444639,1.082417,0.668576,2.049465,1005.838,-6.232451,-4.125,-8.200,0.0,2.614267,98.92361,NaN,NaN,39.267257,2.795783,NaN,NaN,NaN
2018-12-29 00:10:00,11320,0.879624,-0.617260,0.577520,NaN,-5.268014,-0.455156,0.613190,-11.050,46.90142,0.660903,3.759500,0.332375,1.023354,0.542597,1.984889,1003.835,-4.474945,-1.800,-7.296,0.1,1.723672,99.43750,NaN,NaN,47.482347,5.616233,NaN,NaN,NaN
2018-12-30 00:10:00,11321,0.476756,-0.901978,0.896532,NaN,-5.038892,-0.435360,1.807672,-11.050,58.87096,0.611986,3.728389,0.261771,0.933201,0.470632,1.911840,1009.307,-3.461583,-1.738,-5.724,0.3,3.238451,99.72916,NaN,NaN,38.155978,2.973062,NaN,NaN,NaN
2018-12-31 22:10:00,11322,0.605755,-1.960404,0.422131,NaN,-4.760121,-0.411274,0.454753,-2.048,24.69542,0.509465,3.673660,0.231160,0.871861,0.429556,1.876417,1002.851,1.882986,4.524,-1.915,1.9,1.215902,99.46528,NaN,13.0,67.885875,7.418705,4.387930,10.200,S

We can look at a single column through the indexing operator ``[ ]``

In [11]:
# Show the air temperature column ('lt')
weather['lt']

dato
1988-01-01 00:00:00    5.100000
1988-01-02 00:00:00    3.700000
1988-01-03 00:00:00    1.300000
1988-01-04 00:00:00    0.100000
1988-01-05 00:00:00   -0.100000
1988-01-06 00:00:00   -0.500000
1988-01-07 00:00:00   -1.300000
1988-01-08 00:00:00   -6.200000
1988-01-09 00:00:00    0.500000
1988-01-10 00:00:00    4.200000
1988-01-11 00:00:00    1.700000
1988-01-12 00:00:00    0.200000
1988-01-13 00:00:00    3.600000
1988-01-14 00:00:00    3.200000
1988-01-15 00:00:00    3.100000
1988-01-16 00:00:00    0.700000
1988-01-17 00:00:00    0.400000
1988-01-18 00:00:00    1.300000
1988-01-19 00:00:00    0.400000
1988-01-20 00:00:00    1.700000
1988-01-21 00:00:00    1.900000
1988-01-22 00:00:00    2.000000
1988-01-23 00:00:00    0.000000
1988-01-24 00:00:00   -1.100000
1988-01-25 00:00:00    0.000000
1988-01-26 00:00:00   -0.600000
1988-01-27 00:00:00    0.300000
1988-01-28 00:00:00    0.300000
1988-01-29 00:00:00   -0.900000
1988-01-30 00:00:00   -3.300000
                         ...
2018-12-02 00:10:00    4.220986
2018-12-03 22:10:00    5.776055
2018-12-04 00:10:00    3.013479
2018-12-05 00:10:00   -2.114458
2018-12-06 00:10:00   -2.138097
2018-12-07 00:10:00   -0.204861
2018-12-08 00:10:00   -0.546965
2018-12-09 00:10:00   -2.675701
2018-12-10 00:10:00    1.157403
2018-12-11 00:10:00    0.758868
2018-12-12 22:10:00   -6.032153
2018-12-13 22:10:00   -5.462028
2018-12-14 00:10:00   -7.549840
2018-12-15 00:10:00   -5.627292
2018-12-16 00:10:00   -0.505632
2018-12-17 22:10:00   -3.102604
2018-12-18 00:10:00   -4.164535
2018-12-19 00:10:00   -0.015722
2018-12-20 00:10:00    0.983722
2018-12-21 22:10:00   -1.064292
2018-12-22 00:10:00   -3.300639
2018-12-23 00:10:00   -5.367910
2018-12-24 00:10:00   -7.872431
2018-12-25 00:10:00   -1.082090
2018-12-26 00:10:00   -1.380521
2018-12-27 00:10:00   -1.244958
2018-12-28 00:10:00   -6.232451
2018-12-29 00:10:00   -4.474945
2018-12-30 00:10:00   -3.461583
2018-12-31 22:10:00    1.882986
Name: lt, Length: 11323, dtype: float64

We can access multiple columns if we index with lists

In [12]:
# Show the air temperature ('lt') and air pressure ('lp') columns
weather[['lt', 'lp']]

                           lt         lp
dato
1988-01-01 00:00:00  5.100000        NaN
1988-01-02 00:00:00  3.700000        NaN
1988-01-03 00:00:00  1.300000        NaN
1988-01-04 00:00:00  0.100000        NaN
1988-01-05 00:00:00 -0.100000        NaN
1988-01-06 00:00:00 -0.500000        NaN
1988-01-07 00:00:00 -1.300000        NaN
1988-01-08 00:00:00 -6.200000        NaN
1988-01-09 00:00:00  0.500000        NaN
1988-01-10 00:00:00  4.200000        NaN
1988-01-11 00:00:00  1.700000        NaN
1988-01-12 00:00:00  0.200000        NaN
1988-01-13 00:00:00  3.600000        NaN
1988-01-14 00:00:00  3.200000        NaN
1988-01-15 00:00:00  3.100000        NaN
1988-01-16 00:00:00  0.700000        NaN
1988-01-17 00:00:00  0.400000        NaN
1988-01-18 00:00:00  1.300000        NaN
1988-01-19 00:00:00  0.400000        NaN
1988-01-20 00:00:00  1.700000        NaN
1988-01-21 00:00:00  1.900000        NaN
1988-01-22 00:00:00  2.000000        NaN
1988-01-23 00:00:00  0.000000        NaN
1988-01-24 00:00:00 -1.100000        NaN
1988-01-25 00:00:00  0.000000        NaN
1988-01-26 00:00:00 -0.600000        NaN
1988-01-27 00:00:00  0.300000        NaN
1988-01-28 00:00:00  0.300000        NaN
1988-01-29 00:00:00 -0.900000        NaN
1988-01-30 00:00:00 -3.300000        NaN
...                       ...        ...
2018-12-02 00:10:00  4.220986   984.5229
2018-12-03 22:10:00  5.776055   973.7991
2018-12-04 00:10:00  3.013479   987.1948
2018-12-05 00:10:00 -2.114458  1004.8450
2018-12-06 00:10:00 -2.138097   998.6358
2018-12-07 00:10:00 -0.204861   983.6542
2018-12-08 00:10:00 -0.546965   968.7765
2018-12-09 00:10:00 -2.675701   971.3123
2018-12-10 00:10:00  1.157403   988.6810
2018-12-11 00:10:00  0.758868  1009.6670
2018-12-12 22:10:00 -6.032153  1020.4720
2018-12-13 22:10:00 -5.462028  1022.9900
2018-12-14 00:10:00 -7.549840  1023.6290
2018-12-15 00:10:00 -5.627292  1021.1680
2018-12-16 00:10:00 -0.505632  1009.5020
2018-12-17 22:10:00 -3.102604  1007.1630
2018-12-18 00:10:00 -4.164535  1011.2080
2018-12-19 00:10:00 -0.015722  1006.1320
2018-12-20 00:10:00  0.983722  1004.1960
2018-12-21 22:10:00 -1.064292  1000.1270
2018-12-22 00:10:00 -3.300639   999.5062
2018-12-23 00:10:00 -5.367910  1003.3720
2018-12-24 00:10:00 -7.872431  1007.2970
2018-12-25 00:10:00 -1.082090  1002.8690
2018-12-26 00:10:00 -1.380521  1004.6770
2018-12-27 00:10:00 -1.244958  1000.7770
2018-12-28 00:10:00 -6.232451  1005.8380
2018-12-29 00:10:00 -4.474945  1003.8350
2018-12-30 00:10:00 -3.461583  1009.3070
2018-12-31 22:10:00  1.882986  1002.8510

[11323 rows x 2 columns]

And we can do more advanced indexing through the ``loc`` attribute

In [13]:
# Show the percentage infra-red ('irød') and percentage ultra-violet ('uv') columns for the first of december 2018
weather.loc['2018-12-01', ['irød', 'uv']]

                         irød        uv
dato
2018-12-01 00:10:00  43.09908  4.339202

If the index is timestamps, then we can get all values for specific months this way

In [14]:
# Show the percentage infra-red ('irød') and percentage ultra-violet ('uv') columns for the month of december 2018
weather.loc['2018-01', ['irød', 'uv']]

                         irød        uv
dato
2018-01-01 00:10:00  41.68492  4.944655
2018-01-02 00:10:00  50.90939  4.407947
2018-01-03 22:10:00  50.43779  6.166358
2018-01-04 00:10:00  41.68610  6.385012
2018-01-05 00:10:00  31.26810  6.911481
2018-01-06 00:10:00  71.58167  3.922499
2018-01-07 00:10:00  47.92217  5.154746
2018-01-08 22:10:00  64.19691  3.270998
2018-01-09 00:10:00  37.52836  7.166275
2018-01-10 22:10:00  52.97937  4.112136
2018-01-11 00:10:00  35.87284  7.394621
2018-01-12 22:10:00  41.11026  7.070111
2018-01-13 22:10:00  37.29935  7.415319
2018-01-14 22:10:00  46.05742  7.180796
2018-01-15 00:10:00  55.25262  5.453138
2018-01-16 00:10:00  34.93584  6.255599
2018-01-17 00:10:00  44.82857  5.902848
2018-01-18 00:10:00  38.41044  6.866032
2018-01-19 22:10:00  36.99257  6.845589
2018-01-20 00:10:00  45.70993  6.542763
2018-01-21 00:10:00  44.80058  5.839026
2018-01-22 22:10:00  40.41504  5.909199
2018-01-23 00:10:00  41.22897  6.826710
2018-01-24 00:10:00  32.82938  6.696863
2018-01-25 00:10:00  39.85447  5.288078
2018-01-26 22:10:00  49.41974  4.743165
2018-01-27 22:10:00  55.11729  3.391768
2018-01-28 22:10:00  45.21668  5.240556
2018-01-29 00:10:00  46.11165  6.277312
2018-01-30 00:10:00  48.43203  5.639763
2018-01-31 00:10:00  35.21358  4.951124

Pandas uses the ISO standard for dates, that is YYYY-MM-DD

## Excersices:

 1. Extract solely the 'uv' column from the data frame
 2. Extract the 'uv' and 'irød' column from the data frame
 3. Extract all columns from december 2009

You have 10 minutes.

## Solutions:

In [15]:
# Problem 1:
weather['uv']

dato
1988-01-01 00:00:00         NaN
1988-01-02 00:00:00         NaN
1988-01-03 00:00:00         NaN
1988-01-04 00:00:00         NaN
1988-01-05 00:00:00         NaN
1988-01-06 00:00:00         NaN
1988-01-07 00:00:00         NaN
1988-01-08 00:00:00         NaN
1988-01-09 00:00:00         NaN
1988-01-10 00:00:00         NaN
1988-01-11 00:00:00         NaN
1988-01-12 00:00:00         NaN
1988-01-13 00:00:00         NaN
1988-01-14 00:00:00         NaN
1988-01-15 00:00:00         NaN
1988-01-16 00:00:00         NaN
1988-01-17 00:00:00         NaN
1988-01-18 00:00:00         NaN
1988-01-19 00:00:00         NaN
1988-01-20 00:00:00         NaN
1988-01-21 00:00:00         NaN
1988-01-22 00:00:00         NaN
1988-01-23 00:00:00         NaN
1988-01-24 00:00:00         NaN
1988-01-25 00:00:00         NaN
1988-01-26 00:00:00         NaN
1988-01-27 00:00:00         NaN
1988-01-28 00:00:00         NaN
1988-01-29 00:00:00         NaN
1988-01-30 00:00:00         NaN
                         ...
2018-12-02 00:10:00    4.857520
2018-12-03 22:10:00    5.572815
2018-12-04 00:10:00    5.366416
2018-12-05 00:10:00    2.417055
2018-12-06 00:10:00    4.789706
2018-12-07 00:10:00    7.088299
2018-12-08 00:10:00    6.657282
2018-12-09 00:10:00    4.815586
2018-12-10 00:10:00    6.518459
2018-12-11 00:10:00    4.175883
2018-12-12 22:10:00    3.112250
2018-12-13 22:10:00    7.329727
2018-12-14 00:10:00    7.039352
2018-12-15 00:10:00    7.238503
2018-12-16 00:10:00    6.852209
2018-12-17 22:10:00    4.064932
2018-12-18 00:10:00    6.620986
2018-12-19 00:10:00    7.993443
2018-12-20 00:10:00    8.211211
2018-12-21 22:10:00    7.073397
2018-12-22 00:10:00    7.161972
2018-12-23 00:10:00    4.740515
2018-12-24 00:10:00    4.434298
2018-12-25 00:10:00    5.535252
2018-12-26 00:10:00    5.182296
2018-12-27 00:10:00    5.693554
2018-12-28 00:10:00    2.795783
2018-12-29 00:10:00    5.616233
2018-12-30 00:10:00    2.973062
2018-12-31 22:10:00    7.418705
Name: uv, Length: 11323, dtype: float64

In [16]:
weather[['uv', 'irød']]

                           uv      irød
dato
1988-01-01 00:00:00       NaN       NaN
1988-01-02 00:00:00       NaN       NaN
1988-01-03 00:00:00       NaN       NaN
1988-01-04 00:00:00       NaN       NaN
1988-01-05 00:00:00       NaN       NaN
1988-01-06 00:00:00       NaN       NaN
1988-01-07 00:00:00       NaN       NaN
1988-01-08 00:00:00       NaN       NaN
1988-01-09 00:00:00       NaN       NaN
1988-01-10 00:00:00       NaN       NaN
1988-01-11 00:00:00       NaN       NaN
1988-01-12 00:00:00       NaN       NaN
1988-01-13 00:00:00       NaN       NaN
1988-01-14 00:00:00       NaN       NaN
1988-01-15 00:00:00       NaN       NaN
1988-01-16 00:00:00       NaN       NaN
1988-01-17 00:00:00       NaN       NaN
1988-01-18 00:00:00       NaN       NaN
1988-01-19 00:00:00       NaN       NaN
1988-01-20 00:00:00       NaN       NaN
1988-01-21 00:00:00       NaN       NaN
1988-01-22 00:00:00       NaN       NaN
1988-01-23 00:00:00       NaN       NaN
1988-01-24 00:00:00       NaN       NaN
1988-01-25 00:00:00       NaN       NaN
1988-01-26 00:00:00       NaN       NaN
1988-01-27 00:00:00       NaN       NaN
1988-01-28 00:00:00       NaN       NaN
1988-01-29 00:00:00       NaN       NaN
1988-01-30 00:00:00       NaN       NaN
...                       ...       ...
2018-12-02 00:10:00  4.857520  65.57986
2018-12-03 22:10:00  5.572815  44.84836
2018-12-04 00:10:00  5.366416  38.28223
2018-12-05 00:10:00  2.417055  54.21980
2018-12-06 00:10:00  4.789706  67.33762
2018-12-07 00:10:00  7.088299  45.40778
2018-12-08 00:10:00  6.657282  29.76043
2018-12-09 00:10:00  4.815586  45.78611
2018-12-10 00:10:00  6.518459  46.02184
2018-12-11 00:10:00  4.175883  63.20111
2018-12-12 22:10:00  3.112250  41.33722
2018-12-13 22:10:00  7.329727  36.15185
2018-12-14 00:10:00  7.039352  37.40683
2018-12-15 00:10:00  7.238503  36.12814
2018-12-16 00:10:00  6.852209  37.26573
2018-12-17 22:10:00  4.064932  51.78816
2018-12-18 00:10:00  6.620986  44.68304
2018-12-19 00:10:00  7.993443  47.89760
2018-12-20 00:10:00  8.211211  28.23969
2018-12-21 22:10:00  7.073397  37.87324
2018-12-22 00:10:00  7.161972  34.21312
2018-12-23 00:10:00  4.740515  48.73107
2018-12-24 00:10:00  4.434298  54.26330
2018-12-25 00:10:00  5.535252  32.20305
2018-12-26 00:10:00  5.182296  60.84723
2018-12-27 00:10:00  5.693554  38.36279
2018-12-28 00:10:00  2.795783  57.93696
2018-12-29 00:10:00  5.616233  46.90142
2018-12-30 00:10:00  2.973062  58.87096
2018-12-31 22:10:00  7.418705  24.69542

[11323 rows x 2 columns]

In [17]:
weather.loc['2009-12']

,Unnamed: 0,albedo,balanse,diffus,fd,fluxm,fluxs,global,grmin,irød,jt010,jt100,jt002,jt020,jt005,jt050,lp,lt,ltmax,ltmin,nb,par,rf,sd,sdman,synlig,uv,vh,vhmax,vr
dato,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2009-12-01 00:10:00,8005,0.274576,NaN,0.695129,NaN,-11.010810,-0.951334,1.495469,-14.090,61.15839,2.270347,6.127764,1.387063,3.210181,1.882306,5.384326,996.9003,-3.577958,0.175,-7.650,0.3,3.181359,88.78264,NaN,NaN,33.676688,5.164922,1.261451,3.810,NV
2009-12-02 00:10:00,8006,0.311659,NaN,1.000009,NaN,-9.687014,-0.836958,1.180046,-15.870,57.08417,1.383111,6.026326,0.550889,2.313639,1.017132,4.997882,1003.9530,-6.510139,-3.994,-9.090,0.2,2.538777,98.44167,NaN,NaN,37.534954,5.380876,NaN,NaN,N
2009-12-03 00:10:00,8007,0.322989,NaN,0.710723,NaN,-8.346215,-0.721113,1.025527,-16.660,53.10945,0.996694,5.911062,0.197375,1.875354,0.638549,4.613791,1001.9190,-5.315236,-1.572,-9.830,0.0,2.034937,93.88959,NaN,NaN,41.250816,5.639734,NaN,NaN,N
2009-12-04 00:10:00,8008,0.730894,NaN,0.254301,NaN,-6.691389,-0.578136,0.239330,-2.203,29.70520,0.906014,5.800208,0.183083,1.620132,0.593965,4.227424,1002.6690,0.385500,1.638,-2.010,1.1,0.685172,97.35625,NaN,NaN,60.776220,9.518580,2.021549,3.574,NØ
2009-12-05 00:10:00,8009,0.281584,NaN,0.230930,NaN,-5.749361,-0.496745,0.226419,0.007,42.87600,0.871271,5.645201,0.238632,1.513583,0.576868,4.034403,1000.5250,1.662229,2.904,0.876,NaN,0.547456,97.33403,NaN,NaN,48.862768,8.261232,2.512000,4.195,Ø
2009-12-06 00:10:00,8010,0.177415,NaN,0.199884,NaN,-4.945920,-0.427328,0.188261,1.275,40.81519,0.870674,5.502465,0.316479,1.467104,0.629660,3.842653,997.4350,2.504215,2.848,1.814,NaN,0.495961,95.56528,NaN,NaN,50.440132,8.744678,3.097819,5.744,Ø
2009-12-07 00:10:00,8011,0.449000,NaN,0.344391,NaN,-4.144889,-0.358118,0.341447,-0.094,31.04566,0.956472,5.368354,0.460271,1.442507,0.787208,3.717590,995.4832,1.003090,1.975,0.356,22.3,0.873463,98.82014,NaN,NaN,60.620685,8.333655,1.403104,4.859,N
2009-12-08 00:10:00,8012,0.212549,NaN,0.451971,NaN,-0.014368,-0.001241,0.463178,0.429,56.40244,1.414882,5.166327,1.199132,1.599132,1.340354,3.459430,1004.4300,3.514444,4.311,1.212,4.2,1.017885,98.28403,NaN,NaN,37.651420,5.946140,1.228278,3.189,Ø
2009-12-09 00:10:00,8013,0.141813,NaN,0.363969,NaN,-0.224069,-0.019360,0.352551,-0.069,41.60045,1.813514,5.010340,1.565944,1.955486,1.747583,3.535194,1010.7790,2.040604,3.318,1.456,0.3,0.808736,98.12014,NaN,NaN,50.735297,7.664253,1.175924,2.351,Ø
2009-12-10 00:10:00,8014,0.094173,NaN,0.187028,NaN,-0.023125,-0.001998,0.172566,0.767,35.05928,2.076944,4.958347,1.848076,2.192479,2.044215,3.536417,1012.6560,2.047312,2.357,1.561,0.1,0.457037,98.02778,NaN,NaN,55.179933,9.760787,1.041014,2.093,N
2009-12-11 00:10:00,8015,0.203085,NaN,0.510560,NaN,-1.367715,-0.118171,0.504905,-4.623,45.88816,2.148618,4.817458,1.825493,2.333576,2.028049,3.582840,1019.9310,1.517375,2.570,0.395,0.5,1.176687,97.48194,NaN,NaN,46.620774,7.491066,1.333486,3.239,NV
2009-12-12 00:10:00,8016,0.139416,NaN,0.715987,NaN,-3.680795,-0.318021,0.750939,-9.440,47.17845,1.837854,4.714264,1.354715,2.152174,1.612201,3.726889,1022.6480,1.015847,2.638,-2.689,NaN,1.743426,92.57639,NaN,NaN,46.318172,6.503378,1.686354,3.363,NV
2009-12-13 00:10:00,8017,0.323582,NaN,0.946063,NaN,-6.278066,-0.542425,1.330705,-11.950,58.36236,1.182646,4.651701,0.542944,1.743965,0.872715,3.638604,1017.0510,-3.477375,0.428,-5.997,NaN,2.563795,95.96250,NaN,NaN,37.277230,4.360410,0.669118,2.222,NØ
2009-12-14 00:10:00,8018,0.225625,NaN,0.341368,NaN,-5.209871,-0.450133,0.384439,-8.340,57.08839,0.876986,4.603111,0.277250,1.440861,0.596049,3.460090,1010.7480,-1.977681,-0.186,-5.297,0.3,0.894939,98.87431,NaN,NaN,34.808833,8.102777,1.920104,4.646,S
2009-12-15 00:10:00,8019,0.749785,NaN,0.489375,NaN,-4.268379,-0.368788,0.577486,-8.580,35.24427,0.823187,4.572354,0.270875,1.347687,0.564521,3.271118,1004.4220,-2.350965,-0.275,-5.813,1.6,1.437302,91.56597,NaN,NaN,56.227422,8.528308,2.343736,5.506,N
2009-12-16 00:10:00,8020,0.616134,NaN,0.601082,NaN,-3.996337,-0.345284,0.562960,-10.090,59.15768,0.710076,4.497445,0.174056,1.256319,0.435611,3.276132,1005.4960,-4.438201,-2.861,-6.786,0.2,1.129348,83.64166,NaN,NaN,33.534805,7.307515,3.910153,5.561,N
2009-12-17 00:10:00,8021,0.756304,NaN,0.760405,NaN,-4.005212,-0.346050,1.103114,-11.820,60.83089,0.525590,4.421125,-0.006660,1.059778,0.271903,3.026826,1016.1920,-8.664320,-5.105,-10.510,0.0,2.247511,78.17639,NaN,NaN,33.533445,5.635665,5.042028,7.840,N
2009-12-18 00:10:00,8022,0.679371,NaN,0.800636,NaN,-4.073257,-0.351929,1.084758,-20.830,64.32146,0.355007,4.369354,-0.310590,0.963951,0.077743,3.017354,1012.1450,-12.313960,-9.660,-16.590,0.0,2.186245,85.22500,NaN,NaN,30.132640,5.545900,2.062326,5.216,N
2009-12-19 00:10:00,8023,0.554411,NaN,0.410517,NaN,-3.924611,-0.339086,0.469276,-14.980,49.70554,0.225701,4.281333,-0.436694,0.867125,-0.071417,2.951146,996.0879,-8.852104,-5.371,-15.270,NaN,1.156646,91.17291,NaN,NaN,42.834537,7.459923,2.399465,5.208,SØ
2009-12-20 00:10:00,8024,0.725766,NaN,0.776854,NaN,-3.869997,-0.334368,0.841812,-18.560,53.91669,0.233889,4.211847,-0.453250,0.761333,-0.102625,2.793681,990.6934,-8.921805,-7.400,-11.790,NaN,1.818854,91.03680,NaN,NaN,39.573353,6.509957,1.904153,3.595,N
2009-12-21 00:10:00,8025,0.673242,NaN,0.430909,NaN,-4.088302,-0.353229,0.492437,-19.980,43.51076,0.116736,4.123722,-0.543778,0.676937,-0.172347,2.673563,987.8306,-9.033611,-7.640,-13.710,0.2,1.169077,91.30625,NaN,NaN,48.436268,8.052972,1.199507,3.123,N
2009-12-22 00:10:00,8026,0.732237,-0.377434,0.293614,NaN,-3.922458,-0.338900,0.280952,-10.130,45.80558,0.030854,4.028271,-0.515583,0.609090,-0.196597,2.537819,982.1859,-7.433590,-5.557,-9.490,0.0,0.668012,92.65764,NaN,NaN,45.574293,8.620127,1.966347,4.245,N
2009-12-23 00:10:00,8027,0.711111,-0.708543,0.607769,NaN,-3.224361,-0.278585,0.584944,-7.370,52.39628,0.002174,4.000187,-0.509222,0.636708,-0.185062,2.515257,981.0308,-5.309104,-3.320,-6.020,0.3,1.279385,89.21111,NaN,NaN,40.691676,6.912044,2.250264,5.937,N
2009-12-24 00:10:00,8028,1.165785,-0.401140,0.094642,NaN,-2.130809,-0.184102,0.124064,-2.997,21.11484,0.023319,3.986958,-0.376424,0.584576,-0.084431,2.456486,987.0928,-0.165069,0.762,-3.356,NaN,0.387788,96.79236,NaN,NaN,68.574390,10.310770,3.782944,6.822,SØ
2009-12-25 00:10:00,8029,0.823481,-0.276577,0.379337,NaN,-1.537253,-0.132819,0.366526,-0.353,38.40665,0.040229,3.885722,-0.248806,0.621708,-0.053486,2.486910,987.2713,-0.840319,-0.386,-1.508,NaN,0.950399,94.70695,NaN,NaN,52.144952,9.448398,4.472084,6.905,N
2009-12-26 00:10:00,8030,0.872378,-0.928063,0.758937,NaN,-1.421722,-0.122837,0.772583,-0.692,45.45272,0.057681,3.774368,-0.194299,0.711167,-0.030250,2.416938,983.3243,-6.293056,-0.892,-15.830,NaN,1.875808,96.22986,NaN,NaN,47.336097,7.211183,3.286653,6.090,N
2009-12-27 00:10:00,8031,0.755402,0.048922,0.616890,NaN,-1.760191,-0.152081,0.620956,-1.463,44.41245,0.062514,3.744340,-0.163653,0.716403,-0.003757,2.406528,982.8683,-8.394125,-6.144,-14.160,NaN,1.530434,97.12153,NaN,NaN,46.882677,8.704873,1.027326,3.252,NØ
2009-12-28 00:10:00,8032,1.005402,-0.848195,0.571681,NaN,-2.026295,-0.175072,1.033226,-22.230,55.24380,0.098062,3.721639,-0.148722,0.717493,-0.002708,2.374924,983.3594,-10.438940,-6.360,-14.890,43.8,2.361447,96.62708,NaN,NaN,37.907881,6.848319,NaN,NaN,NØ
2009-12-29 00:10:00,8033,1.073127,-0.881063,0.609109,NaN,-2.130583,-0.184082,1.396417,-28.210,53.41901,0.121264,3.532681,-0.149354,0.665542,-0.015431,2.283958,993.8040,-15.701250,-11.090,-19.210,0.0,2.459159,92.96944,NaN,NaN,41.539188,5.041802,NaN,NaN,NØ
2009-12-30 00:10:00,8034,1.209811,-0.948056,0.707935,NaN,-2.221083,-0.191902,1.334852,-30.460,62.21787,0.144451,3.509951,-0.197319,0.666611,0.000715,2.295903,997.2886,-19.614170,-15.480,-22.700,NaN,2.620516,89.45416,NaN,NaN,32.563528,5.218602,NaN,NaN,NØ
2009-12-31 00:10:00,8035,1.002582,-0.624451,0.878178,NaN,-2.341378,-0.202295,1.077688,-27.560,54.83232,0.171132,3.490035,-0.220021,0.668799,0.011472,2.259292,994.3251,-14.264370,-7.830,-21.550,0.4,2.295917,93.55556,NaN,NaN,38.756568,6.411112,NaN,NaN,NØ

## Part 2: Mathematics on dataframes
### Behind the scenes: NumPy
Pandas data frames use a package called NumPy (Numerical Python) to perform efficient mathematics on large datasets. NumPy is a highly optimised C tool that offers an easy-to-use interface to linear algebra libraries such as Intel MKL and BLAS. As a consequence, numerical Python code will often perform as well if not better than code written in other languages.

We will not learn about NumPy in this course, but use some if its functions. The basics of NumPy was introduced in the intro to Python module and a more in-depth course will be offered in August.

In [18]:
import numpy as np

### Let us start with some simple arithmetic
The ``'uv'``, ``'irød'`` and ``'synlig'`` columns contain the percentage of the global radiation (``'global'``) that was ultra-violet, infra-red and visible, respectively. Let us therefore create new columns that contain the amount, not percentages.

In [19]:
weather['uv_amount'] = weather['uv']*weather['global']/100
weather['ir_amount'] = weather['irød']*weather['global']/100
weather['visible_amount'] = weather['synlig']*weather['global']/100

In [20]:
weather.tail()

,Unnamed: 0,albedo,balanse,diffus,fd,fluxm,fluxs,global,grmin,irød,jt010,jt100,jt002,jt020,jt005,jt050,lp,lt,ltmax,ltmin,nb,par,rf,sd,sdman,synlig,uv,vh,vhmax,vr,uv_amount,ir_amount,visible_amount
dato,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2018-12-27 00:10:00,11318,0.648644,-1.037384,0.520922,NaN,-3.859840,-0.333490,0.542782,-7.409,38.36279,0.694146,3.838215,0.449583,1.094819,0.664396,2.068958,1000.777,-1.244958,0.695,-4.085,1.8,1.339207,99.99931,NaN,13.0,55.943656,5.693554,0.776569,2.105,NØ,0.030904,0.208226,0.303652
2018-12-28 00:10:00,11319,0.458021,-1.520098,0.991158,NaN,-4.974732,-0.429817,1.719382,-12.720,57.93696,0.775146,3.810514,0.444639,1.082417,0.668576,2.049465,1005.838,-6.232451,-4.125,-8.200,0.0,2.614267,98.92361,NaN,NaN,39.267257,2.795783,NaN,NaN,NaN,0.048070,0.996158,0.675154
2018-12-29 00:10:00,11320,0.879624,-0.617260,0.577520,NaN,-5.268014,-0.455156,0.613190,-11.050,46.90142,0.660903,3.759500,0.332375,1.023354,0.542597,1.984889,1003.835,-4.474945,-1.800,-7.296,0.1,1.723672,99.43750,NaN,NaN,47.482347,5.616233,NaN,NaN,NaN,0.034438,0.287595,0.291157
2018-12-30 00:10:00,11321,0.476756,-0.901978,0.896532,NaN,-5.038892,-0.435360,1.807672,-11.050,58.87096,0.611986,3.728389,0.261771,0.933201,0.470632,1.911840,1009.307,-3.461583,-1.738,-5.724,0.3,3.238451,99.72916,NaN,NaN,38.155978,2.973062,NaN,NaN,NaN,0.053743,1.064194,0.689735
2018-12-31 22:10:00,11322,0.605755,-1.960404,0.422131,NaN,-4.760121,-0.411274,0.454753,-2.048,24.69542,0.509465,3.673660,0.231160,0.871861,0.429556,1.876417,1002.851,1.882986,4.524,-1.915,1.9,1.215902,99.46528,NaN,13.0,67.885875,7.418705,4.387930,10.200,S,0.033737,0.112303,0.308713

We can now rename the ``uv``, ``irød`` and ``synlig`` columns to give them more sensible names.

In [21]:
weather = weather.rename(
    {
        'uv': 'uv_percentage',
        'irød': 'ir_percentage',
        'synlig': 'visible_percentage'
    },  # This is a dictionary
    axis=1
)

### We can also compute summary statistics on Pandas data frames
The mean is computed with the ``DataFrame.mean()`` method and the standard deviation is computed with the ``DataFrame.std()`` method.

In [26]:
print('Mean')
weather.mean()

Mean

Unnamed: 0            5661.000000
albedo                   0.334882
balanse                  3.116438
diffus                   4.158940
fd                       2.557109
fluxm                    0.048990
fluxs                    0.020836
global                   9.157744
grmin                   33.661247
ir_percentage           50.634207
jt010                    7.280770
jt100                    7.148726
jt002                    7.233166
jt020                    7.126354
jt005                    7.242559
jt050                    7.540423
lp                    1000.022702
lt                       6.377937
ltmax                   10.196489
ltmin                    2.191760
nb                       2.703469
par                     20.525249
rf                      79.941759
sd                       2.168282
sdman                    8.543985
visible_percentage      43.691033
uv_percentage            5.686159
vh                       2.710846
vhmax                    5.576081
uv_amount                0.462978
ir_amount                4.775528
visible_amount           4.015093
dtype: float64

In [27]:
print('Standard deviation:')
weather.std()

Standard deviation:

Unnamed: 0            3268.812883
albedo                   0.225832
balanse                  4.869500
diffus                   3.289472
fd                       1.713003
fluxm                   18.684980
fluxs                    0.860714
global                   8.231386
grmin                  517.371215
ir_percentage            6.446930
jt010                    6.691971
jt100                    4.375169
jt002                    7.070294
jt020                    6.392470
jt005                    6.871104
jt050                    5.508264
lp                      12.446097
lt                       8.037329
ltmax                    8.761555
ltmin                    7.750335
nb                       6.084917
par                     18.557807
rf                      14.589230
sd                       4.645082
sdman                   11.983551
visible_percentage       5.903798
uv_percentage            1.231517
vh                       1.355322
vhmax                    2.316607
uv_amount                0.387988
ir_amount                4.266682
visible_amount           3.622270
dtype: float64

### Exercise:
Compute the median of the weather data frame

In [28]:
print('Median: ')
weather.median()

Median:

Unnamed: 0            5661.000000
albedo                   0.240000
balanse                  1.403642
diffus                   3.462354
fd                       2.394997
fluxm                    0.256625
fluxs                    0.021455
global                   6.636849
grmin                   -1.060000
ir_percentage           50.799770
jt010                    6.606208
jt100                    6.600000
jt002                    6.400000
jt020                    6.340927
jt005                    6.697535
jt050                    7.062048
lp                    1000.527000
lt                       6.306361
ltmax                   10.090000
ltmin                    2.278000
nb                       0.100000
par                     14.928625
rf                      82.631599
sd                       0.000000
sdman                    1.000000
visible_percentage      43.884343
uv_percentage            5.391731
vh                       2.446858
vhmax                    5.287000
uv_amount                0.363645
ir_amount                3.491697
visible_amount           2.917559
dtype: float64

### Advanced transformations
Sometimes, we want to perform more "advanced" transformations on our data frame. To do this, we need NumPy.

Let us demonstrate a case where these "advanced" transformations are useful. We want to round our air-pressure and column to the nearest integer, the simplest way to do this is to do a type-cast, transforming our double-precision floats to ints.

In [25]:
rounded_pressure = weather['lt'].astype(int)

ValueError: Cannot convert non-finite values (NA or inf) to integer

Here we get a ``ValueError``. The reason for this error is that the international standard for integer numbers do not have support for NAN and infinity values. If we drop these, then we can easily perform the type-cast.

In [29]:
weather.isna() # See NAN values

,Unnamed: 0,albedo,balanse,diffus,fd,fluxm,fluxs,global,grmin,ir_percentage,jt010,jt100,jt002,jt020,jt005,jt050,lp,lt,ltmax,ltmin,nb,par,rf,sd,sdman,visible_percentage,uv_percentage,vh,vhmax,vr,uv_amount,ir_amount,visible_amount
dato,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1988-01-01 00:00:00,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True
1988-01-02 00:00:00,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True
1988-01-03 00:00:00,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True
1988-01-04 00:00:00,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True
1988-01-05 00:00:00,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True
1988-01-06 00:00:00,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True
1988-01-07 00:00:00,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True
1988-01-08 00:00:00,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True
1988-01-09 00:00:00,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True
1988-01-10 00:00:00,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True
1988-01-11 00:00:00,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True
1988-01-12 00:00:00,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True
1988-01-13 00:00:00,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True
1988-01-14 00:00:00,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True
1988-01-15 00:00:00,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True
1988-01-16 00:00:00,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True
1988-01-17 00:00:00,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True
1988-01-18 00:00:00,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True
1988-01-19 00:00:00,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True
1988-01-20 00:00:00,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True
1988-01-21 00:00:00,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True
1988-01-22 00:00:00,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True
1988-01-23 00:00:00,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True
1988-01-24 00:00:00,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True
1988-01-25 00:00:00,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True
1988-01-26 00:00:00,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True
1988-01-27 00:00:00,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True
1988-01-28 00:00:00,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True
1988-01-29 00:00:00,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True
1988-01-30 00:00:00,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-12-02 00:10:00,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False
2018-12-03 22:10:00,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
2018-12-04 00:10:00,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
2018-12-05 00:10:00,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
2018-12-06 00:10:00,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,True,True,False,False,False
2018-12-07 00:10:00,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,True,True,False,False,False
2018-12-08 00:10:00,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False
2018-12-09 00:10:00,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False
2018-12-10 00:10:00,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
2018-12-11 00:10:00,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
2018-12-12 22:10:00,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,True,True,False,False,False
2018-12-13 22:10:00,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
2018-12-14 00:10:00,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
2018-12-15 00:10:00,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False
2018-12-16 00:10:00,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False
2018-12-17 22:10:00,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
2018-12-18 00:10:00,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
2018-12-19 00:10:00,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
2018-12-20 00:10:00,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
2018-12-21 22:10:00,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
2018-12-22 00:10:00,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False
2018-12-23 00:10:00,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False
2018-12-24 00:10:00,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,True,True,True,False,False,False
2018-12-25 00:10:00,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
2018-12-26 00:10:00,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False
2018-12-27 00:10:00,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
2018-12-28 00:10:00,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,True,True,True,False,False,False
2018-12-29 00:10:00,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,True,True,True,False,False,False
2018-12-30 00:10:00,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,True,True,True,False,False,False
2018-12-31 22:10:00,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False

In [25]:
weather.isna().sum()

Unnamed: 0                0
albedo                  676
balanse                 552
diffus                  482
fd                     9373
fluxm                  2376
fluxs                  2406
global                  382
grmin                  6218
ir_percentage           718
jt010                   644
jt100                   489
jt002                  2363
jt020                   693
jt005                   966
jt050                   789
lp                     2293
lt                      366
ltmax                    34
ltmin                    34
nb                     1132
par                     505
rf                      482
sd                    10869
sdman                 11057
visible_percentage      845
uv_percentage           585
vh                      841
vhmax                   876
vr                      727
uv_amount               585
ir_amount               720
visible_amount          845
dtype: int64

In [30]:
lt_rounded = weather['lt'].dropna().astype(int)
lt_rounded

dato
1988-01-01 00:00:00    5
1988-01-02 00:00:00    3
1988-01-03 00:00:00    1
1988-01-04 00:00:00    0
1988-01-05 00:00:00    0
1988-01-06 00:00:00    0
1988-01-07 00:00:00   -1
1988-01-08 00:00:00   -6
1988-01-09 00:00:00    0
1988-01-10 00:00:00    4
1988-01-11 00:00:00    1
1988-01-12 00:00:00    0
1988-01-13 00:00:00    3
1988-01-14 00:00:00    3
1988-01-15 00:00:00    3
1988-01-16 00:00:00    0
1988-01-17 00:00:00    0
1988-01-18 00:00:00    1
1988-01-19 00:00:00    0
1988-01-20 00:00:00    1
1988-01-21 00:00:00    1
1988-01-22 00:00:00    2
1988-01-23 00:00:00    0
1988-01-24 00:00:00   -1
1988-01-25 00:00:00    0
1988-01-26 00:00:00    0
1988-01-27 00:00:00    0
1988-01-28 00:00:00    0
1988-01-29 00:00:00    0
1988-01-30 00:00:00   -3
                      ..
2018-12-02 00:10:00    4
2018-12-03 22:10:00    5
2018-12-04 00:10:00    3
2018-12-05 00:10:00   -2
2018-12-06 00:10:00   -2
2018-12-07 00:10:00    0
2018-12-08 00:10:00    0
2018-12-09 00:10:00   -2
2018-12-10 00:10:00    1
2018-12-11 00:10:00    0
2018-12-12 22:10:00   -6
2018-12-13 22:10:00   -5
2018-12-14 00:10:00   -7
2018-12-15 00:10:00   -5
2018-12-16 00:10:00    0
2018-12-17 22:10:00   -3
2018-12-18 00:10:00   -4
2018-12-19 00:10:00    0
2018-12-20 00:10:00    0
2018-12-21 22:10:00   -1
2018-12-22 00:10:00   -3
2018-12-23 00:10:00   -5
2018-12-24 00:10:00   -7
2018-12-25 00:10:00   -1
2018-12-26 00:10:00   -1
2018-12-27 00:10:00   -1
2018-12-28 00:10:00   -6
2018-12-29 00:10:00   -4
2018-12-30 00:10:00   -3
2018-12-31 22:10:00    1
Name: lt, Length: 10957, dtype: int32

If we then add this row to our data frame, we see that it is transformed back to floats (but with no decimal points).

In [31]:
weather['lt_rounded'] = lt_rounded

In [32]:
weather['lt_rounded']

dato
1988-01-01 00:00:00    5.0
1988-01-02 00:00:00    3.0
1988-01-03 00:00:00    1.0
1988-01-04 00:00:00    0.0
1988-01-05 00:00:00    0.0
1988-01-06 00:00:00    0.0
1988-01-07 00:00:00   -1.0
1988-01-08 00:00:00   -6.0
1988-01-09 00:00:00    0.0
1988-01-10 00:00:00    4.0
1988-01-11 00:00:00    1.0
1988-01-12 00:00:00    0.0
1988-01-13 00:00:00    3.0
1988-01-14 00:00:00    3.0
1988-01-15 00:00:00    3.0
1988-01-16 00:00:00    0.0
1988-01-17 00:00:00    0.0
1988-01-18 00:00:00    1.0
1988-01-19 00:00:00    0.0
1988-01-20 00:00:00    1.0
1988-01-21 00:00:00    1.0
1988-01-22 00:00:00    2.0
1988-01-23 00:00:00    0.0
1988-01-24 00:00:00   -1.0
1988-01-25 00:00:00    0.0
1988-01-26 00:00:00    0.0
1988-01-27 00:00:00    0.0
1988-01-28 00:00:00    0.0
1988-01-29 00:00:00    0.0
1988-01-30 00:00:00   -3.0
                      ...
2018-12-02 00:10:00    4.0
2018-12-03 22:10:00    5.0
2018-12-04 00:10:00    3.0
2018-12-05 00:10:00   -2.0
2018-12-06 00:10:00   -2.0
2018-12-07 00:10:00    0.0
2018-12-08 00:10:00    0.0
2018-12-09 00:10:00   -2.0
2018-12-10 00:10:00    1.0
2018-12-11 00:10:00    0.0
2018-12-12 22:10:00   -6.0
2018-12-13 22:10:00   -5.0
2018-12-14 00:10:00   -7.0
2018-12-15 00:10:00   -5.0
2018-12-16 00:10:00    0.0
2018-12-17 22:10:00   -3.0
2018-12-18 00:10:00   -4.0
2018-12-19 00:10:00    0.0
2018-12-20 00:10:00    0.0
2018-12-21 22:10:00   -1.0
2018-12-22 00:10:00   -3.0
2018-12-23 00:10:00   -5.0
2018-12-24 00:10:00   -7.0
2018-12-25 00:10:00   -1.0
2018-12-26 00:10:00   -1.0
2018-12-27 00:10:00   -1.0
2018-12-28 00:10:00   -6.0
2018-12-29 00:10:00   -4.0
2018-12-30 00:10:00   -3.0
2018-12-31 22:10:00    1.0
Name: lt_rounded, Length: 11323, dtype: float64

Another way of doing this, without dropping the NAN values, is through numpy universal functions (numpy ufuncs). A universal function is a function that can be applied pointwise to arrays. In this case, we use the round function.

More information about universal functions can be found here: https://docs.scipy.org/doc/numpy/reference/ufuncs.html

In [33]:
lt_rounded = np.round(weather['lt'])

In [34]:
lt_rounded

dato
1988-01-01 00:00:00    5.0
1988-01-02 00:00:00    4.0
1988-01-03 00:00:00    1.0
1988-01-04 00:00:00    0.0
1988-01-05 00:00:00   -0.0
1988-01-06 00:00:00   -0.0
1988-01-07 00:00:00   -1.0
1988-01-08 00:00:00   -6.0
1988-01-09 00:00:00    0.0
1988-01-10 00:00:00    4.0
1988-01-11 00:00:00    2.0
1988-01-12 00:00:00    0.0
1988-01-13 00:00:00    4.0
1988-01-14 00:00:00    3.0
1988-01-15 00:00:00    3.0
1988-01-16 00:00:00    1.0
1988-01-17 00:00:00    0.0
1988-01-18 00:00:00    1.0
1988-01-19 00:00:00    0.0
1988-01-20 00:00:00    2.0
1988-01-21 00:00:00    2.0
1988-01-22 00:00:00    2.0
1988-01-23 00:00:00    0.0
1988-01-24 00:00:00   -1.0
1988-01-25 00:00:00    0.0
1988-01-26 00:00:00   -1.0
1988-01-27 00:00:00    0.0
1988-01-28 00:00:00    0.0
1988-01-29 00:00:00   -1.0
1988-01-30 00:00:00   -3.0
                      ...
2018-12-02 00:10:00    4.0
2018-12-03 22:10:00    6.0
2018-12-04 00:10:00    3.0
2018-12-05 00:10:00   -2.0
2018-12-06 00:10:00   -2.0
2018-12-07 00:10:00   -0.0
2018-12-08 00:10:00   -1.0
2018-12-09 00:10:00   -3.0
2018-12-10 00:10:00    1.0
2018-12-11 00:10:00    1.0
2018-12-12 22:10:00   -6.0
2018-12-13 22:10:00   -5.0
2018-12-14 00:10:00   -8.0
2018-12-15 00:10:00   -6.0
2018-12-16 00:10:00   -1.0
2018-12-17 22:10:00   -3.0
2018-12-18 00:10:00   -4.0
2018-12-19 00:10:00   -0.0
2018-12-20 00:10:00    1.0
2018-12-21 22:10:00   -1.0
2018-12-22 00:10:00   -3.0
2018-12-23 00:10:00   -5.0
2018-12-24 00:10:00   -8.0
2018-12-25 00:10:00   -1.0
2018-12-26 00:10:00   -1.0
2018-12-27 00:10:00   -1.0
2018-12-28 00:10:00   -6.0
2018-12-29 00:10:00   -4.0
2018-12-30 00:10:00   -3.0
2018-12-31 22:10:00    2.0
Name: lt, Length: 11323, dtype: float64

### Saving our improved dataset
We might be interested in saving our data after performing transformations above. To do this, we can simply call the ``DataFrame.to_excel`` method.

In [31]:
weather.to_excel('weather_improved.xlsx')

### Another example with universal functions: The logarithm

Let's imagine that we, for some reason, is interested in the logarithm of the temperature (in kelvin). Then we can create our own universal function to do this.

In [32]:
def log_kelvin(temperature):
    return np.log(temperature + 273)

In [33]:
weather['log_kelvin_lt'] = log_kelvin(weather['lt'])

In [34]:
weather['log_kelvin_lt'].mean()

5.632149075735982

## Grouping data
Pandas offers a useful interface for grouping operations – ``DataFrame.groupby``. With this operation, we can group the dataframe based on information in specific columns (or the index). Let us start by creating a month-column that we group by.

In [36]:
weather['month'] = weather.index.month
weather

,Unnamed: 0,albedo,balanse,diffus,fd,fluxm,fluxs,global,grmin,ir_percentage,jt010,jt100,jt002,jt020,jt005,jt050,lp,lt,ltmax,ltmin,nb,par,rf,sd,sdman,visible_percentage,uv_percentage,vh,vhmax,vr,uv_amount,ir_amount,visible_amount,lt_rounded,month
dato,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1988-01-01 00:00:00,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.100000,5.900,3.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,1
1988-01-02 00:00:00,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.700000,5.300,1.500,20.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1
1988-01-03 00:00:00,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.300000,2.100,0.200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1
1988-01-04 00:00:00,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.100000,0.400,-0.100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1
1988-01-05 00:00:00,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.100000,0.600,-0.500,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1
1988-01-06 00:00:00,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.500000,0.200,-1.400,3.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1
1988-01-07 00:00:00,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.300000,0.200,-5.600,0.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,1
1988-01-08 00:00:00,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-6.200000,-4.500,-10.700,0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-6.0,1
1988-01-09 00:00:00,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.500000,2.900,-4.900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1
1988-01-10 00:00:00,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.200000,5.800,1.900,5.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,1
1988-01-11 00:00:00,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.700000,3.600,0.900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1
1988-01-12 00:00:00,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.200000,4.300,-2.800,2.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1
1988-01-13 00:00:00,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.600000,4.600,3.000,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1
1988-01-14 00:00:00,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.200000,3.900,2.300,1.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1
1988-01-15 00:00:00,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.100000,4.300,1.800,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1
1988-01-16 00:00:00,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.700000,1.800,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1
1988-01-17 00:00:00,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.400000,1.300,0.000,1.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1
1988-01-18 00:00:00,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.300000,2.400,0.100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1
1988-01-19 00:00:00,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.400000,3.000,-0.800,7.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1
1988-01-20 00:00:00,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.700000,2.300,1.000,5.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1
1988-01-21 00:00:00,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.900000,3.500,0.300,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1
1988-01-22 00:00:00,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,3.500,0.400,9.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1
1988-01-23 00:00:00,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.400,-1.100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1
1988-01-24 00:00:00,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.100000,-0.400,-1.700,8.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,1
1988-01-25 00:00:00,24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.400,-0.700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1
1988-01-26 00:00:00,25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.600000,0.000,-0.800,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1
1988-01-27 00:00:00,26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.300000,0.300,-0.500,12.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1
1988-01-28 00:00:00,27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.300000,0.700,0.000,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1
1988-01-29 00:00:00,28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.900000,0.100,-2.800,2.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1
1988-01-30 00:00:00,29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-3.300000,-2.800,-3.900,16.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-3.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-12-02 00:10:00,11293,0.172544,-0.561167,0.460905,NaN,3.291177,0.284358,0.421363,-0.038,65.57986,1.039569,5.445042,0.737660,1.422431,0.832167,2.793424,984.5229,4.220986,4.773,2.480,12.0,0.853293,99.96528,NaN,NaN,29.562620,4.857520,2.898785,4.087,Ø,0.020468,0.276329,0.124566,4.0,12
2018-12-03 22:10:00,11294,0.108175,0.017563,0.393376,NaN,6.200490,0.535722,0.384140,4.363,44.84836,2.410222,5.309354,2.739563,2.247729,2.601854,2.943118,973.7991,5.776055,7.378,4.749,8.6,0.906667,100.00000,NaN,0.0,49.578825,5.572815,1.775410,4.439,Ø,0.021407,0.172280,0.190452,5.0,12
2018-12-04 00:10:00,11295,0.221060,-3.654298,0.729919,NaN,-7.121333,-0.615283,0.811693,-7.964,38.28223,3.107917,5.253472,2.774570,2.969076,2.952181,3.321132,987.1948,3.013479,4.880,-1.672,4.7,1.853481,72.02778,NaN,0.0,56.351354,5.366416,3.472875,6.210,NV,0.043559,0.310734,0.457400,3.0,12
2018-12-05 00:10:00,11296,0.223798,-4.569000,2.154242,NaN,-14.243610,-1.230648,2.455054,-12.370,54.21980,1.867806,5.264812,0.946854,2.501972,1.445979,3.536944,1004.8450,-2.114458,0.578,-5.752,0.0,3.244609,75.22916,NaN,0.0,43.363145,2.417055,1.735375,4.125,S,0.059340,1.331125,1.064589,-2.0,12
2018-12-06 00:10:00,11297,0.291290,-1.070306,0.619717,NaN,-10.252400,-0.885807,0.556293,-11.660,67.33762,1.261222,5.252576,0.446042,1.917250,0.868993,3.374979,998.6358,-2.138097,0.326,-5.997,7.4,1.142509,98.10416,NaN,0.0,27.872674,4.789706,NaN,NaN,NaN,0.026645,0.374594,0.155054,-2.0,12
2018-12-07 00:10:00,11298,0.784074,-0.066208,0.530192,NaN,-8.185083,-0.707191,0.498974,-1.009,45.40778,0.994896,5.191764,0.393667,1.603500,0.723257,3.100965,983.6542,-0.204861,0.300,-0.596,8.5,1.359652,99.86806,NaN,10.0,47.503921,7.088299,NaN,NaN,NaN,0.035369,0.226573,0.237032,0.0,12
2018-12-08 00:10:00,11299,2.595680,-0.668164,0.611927,NaN,-7.103809,-0.613769,0.291119,-3.369,29.76043,0.851104,5.081000,0.394417,1.494625,0.703340,2.917847,968.7765,-0.546965,0.081,-1.948,4.4,0.854312,99.50000,NaN,NaN,63.582288,6.657282,2.113271,4.013,N,0.019381,0.086638,0.185100,0.0,12
2018-12-09 00:10:00,11300,0.722303,-1.521313,0.822890,NaN,-6.286635,-0.543165,1.090572,-13.660,45.78611,0.918299,4.978882,0.438750,1.471201,0.734437,2.795486,971.3123,-2.675701,-0.425,-5.615,0.2,2.067057,97.26389,NaN,NaN,49.398304,4.815586,1.510097,3.812,NV,0.052517,0.499330,0.538724,-2.0,12
2018-12-10 00:10:00,11301,0.751300,-2.938722,0.779939,NaN,-5.871264,-0.507277,0.849219,-10.030,46.02184,1.465993,4.872576,0.506958,1.459549,0.804660,2.696285,988.6810,1.157403,3.766,-4.173,0.0,2.018458,76.17361,NaN,19.0,47.459701,6.518459,2.992194,6.235,NV,0.055356,0.390826,0.403037,1.0,12
2018-12-11 00:10:00,11302,0.707177,-2.817427,0.563883,NaN,-5.402417,-0.466769,1.406764,-14.990,63.20111,1.901778,4.759597,0.588812,1.461493,0.863778,2.646722,1009.6670,0.758868,3.735,-6.743,0.0,2.828161,75.13465,NaN,18.0,32.623007,4.175883,2.616361,4.832,N,0.058745,0.889090,0.458929,0.0,12
2018-12-12 22:10:00,11303,0.552113,-1.607687,0.568240,NaN,-5.413264,-0.467706,1.891487,-17.580,41.33722,1.466694,4.693028,0.650132,1.483299,0.917424,2.607875,1020.4720,-6.032153,-2.048,-9.460,0.0,3.027292,98.19514,NaN,17.0,55.550530,3.112250,NaN,NaN,NaN,0.058868,0.781888,1.050731,-6.0,12
2018-12-13 22:10:00,11304,0.788596,-0.294080,0.486171,NaN,-5.202694,-0.449513,0.468615,-6.274,36.15185,1.682854,4.605542,0.644826,1.459250,0.901535,2.530319,1022.9900,-5.462028,-4.929,-6.217,0.2,1.268141,95.26389,NaN,17.0,56.518423,7.329727,2.540396,4.167,N,0.034348,0.169413,0.264854,-5.0,12
2018-12-14 00:10:00,11305,0.757965,-0.361724,0.496776,NaN,-4.907326,-0.423993,0.487178,-9.380,37.40683,1.807743,4.520215,0.668917,1.401708,0.912125,2.456951,1023.6290,-7.549840,-6.223,-9.140,0.0,1.302357,91.85764,NaN,17.0,55.553818,7.039352,1.822951,3.288,N,0.034294,0.182238,0.270646,-7.0,12
2018-12-15 00:10:00,11306,0.790336,-0.451263,0.465728,NaN,-4.855365,-0.419503,0.449248,-8.450,36.12814,0.982826,4.422111,0.677195,1.370590,0.907062,2.394778,1021.1680,-5.627292,-1.944,-8.540,1.0,1.207986,93.70764,NaN,NaN,56.633357,7.238503,1.509257,2.697,N,0.032519,0.162305,0.254424,-5.0,12
2018-12-16 00:10:00,11307,0.748424,-0.738231,0.456784,NaN,-4.251715,-0.367348,0.455249,-2.827,37.26573,0.935063,4.357625,0.675847,1.355417,0.904215,2.346479,1009.5020,-0.505632,0.187,-2.040,1.5,1.168568,93.99514,NaN,NaN,55.882061,6.852209,2.667333,4.059,Ø,0.031195,0.169652,0.254402,0.0,12
2018-12-17 22:10:00,11308,0.725240,-0.873497,1.135281,NaN,-3.555465,-0.307192,1.270855,-11.490,51.78816,1.007007,4.282896,0.798264,1.367646,0.963757,2.335264,1007.1630,-3.102604,-1.375,-5.237,1.1,2.706872,99.37917,NaN,20.0,44.146908,4.064932,1.076243,2.788,N,0.051659,0.658152,0.561043,-3.0,12
2018-12-18 00:10:00,11309,0.837900,-0.271274,0.598734,NaN,-3.485184,-0.301120,0.559267,-4.897,44.68304,1.072222,4.216403,0.854632,1.397778,1.036910,2.322208,1011.2080,-4.164535,-2.751,-5.016,0.6,1.501040,99.65278,NaN,19.0,48.695974,6.620986,0.909535,2.079,N,0.037029,0.249898,0.272341,-4.0,12
2018-12-19 00:10:00,11310,0.711765,-0.527623,0.233392,NaN,-3.408437,-0.294489,0.225485,-3.135,47.89760,1.196875,4.164993,0.916305,1.438201,1.072410,2.313292,1006.1320,-0.015722,1.486,-2.931,3.3,0.626588,99.52847,NaN,19.0,44.108957,7.993443,1.842535,3.027,Ø,0.018024,0.108002,0.099459,0.0,12
2018-12-20 00:10:00,11311,0.816733,-1.097929,0.187892,NaN,-3.567246,-0.308210,0.174457,-0.207,28.23969,1.282688,4.107924,0.955861,1.462951,1.109847,2.316410,1004.1960,0.983722,1.450,0.062,0.7,0.509647,96.31389,NaN,16.0,63.549099,8.211211,2.526660,3.815,Ø,0.014325,0.049266,0.110866,0.0,12
2018-12-21 22:10:00,11312,0.701868,-0.515824,0.375762,NaN,-3.557246,-0.307346,0.364153,-2.831,37.87324,1.750306,4.079236,0.992243,1.478194,1.158118,2.314333,1000.1270,-1.064292,0.037,-2.503,0.5,0.999070,87.70069,NaN,14.0,55.053363,7.073397,2.953264,3.941,NØ,0.025758,0.137917,0.200479,-1.0,12
2018-12-22 00:10:00,11313,0.752722,-0.722865,0.338192,NaN,-3.582708,-0.309546,0.323534,-5.060,34.21312,2.527778,4.049812,1.008451,1.497750,1.178979,2.323424,999.5062,-3.300639,-2.533,-4.271,0.0,0.911864,83.18840,NaN,NaN,58.624908,7.161972,1.692528,3.571,N,0.023171,0.110691,0.189671,-3.0,12
2018-12-23 00:10:00,11314,0.661407,-1.322467,0.896327,NaN,-4.295028,-0.371090,0.915799,-17.800,48.73107,1.758174,4.039521,0.904299,1.482236,1.099333,2.309347,1003.3720,-5.367910,-3.273,-10.830,0.0,2.105036,92.95972,NaN,NaN,46.528415,4.740515,0.725639,1.695,NV,0.043414,0.446279,0.426107,-5.0,12
2018-12-24 00:10:00,11315,0.684347,-0.834153,0.873651,NaN,-6.058024,-0.523413,0.984602,-18.520,54.26330,1.096764,3.988354,0.650195,1.379646,0.887687,2.250625,1007.2970,-7.872431,-2.061,-12.770,0.0,1.962061,98.82570,NaN,NaN,41.302402,4.434298,NaN,NaN,NaN,0.043660,0.534278,0.406664,-7.0,12
2018-12-25 00:10:00,11316,0.669676,-2.126344,0.477907,NaN,-5.256490,-0.454161,0.606802,-10.280,32.20305,0.885320,3.954708,0.493354,1.217285,0.752347,2.191604,1002.8690,-1.082090,5.844,-5.023,0.0,1.571380,91.06236,NaN,14.0,62.261698,5.535252,1.300396,4.915,Ø,0.033588,0.195409,0.377805,-1.0,12
2018-12-26 00:10:00,11317,0.684592,-0.875690,0.503858,NaN,-4.962451,-0.428756,0.461216,-11.080,60.84723,0.722833,3.893701,0.442549,1.146104,0.672882,2.096153,1004.6770,-1.380521,0.976,-5.676,0.5,0.966637,96.40625,NaN,NaN,33.970474,5.182296,0.841278,1.848,Ø,0.023902,0.280637,0.156677,-1.0,12
2018-12-27 00:10:00,11318,0.648644,-1.037384,0.520922,NaN,-3.859840,-0.333490,0.542782,-7.409,38.36279,0.694146,3.838215,0.449583,1.094819,0.664396,2.068958,1000.7770,-1.244958,0.695,-4.085,1.8,1.339207,99.99931,NaN,13.0,55.943656,5.693554,0.776569,2.105,NØ,0.030904,0.208226,0.303652,-1.0,12
2018-12-28 00:10:00,11319,0.458021,-1.520098,0.991158,NaN,-4.974732,-0.429817,1.719382,-12.720,57.93696,0.775146,3.810514,0.444639,1.082417,0.668576,2.049465,1005.8380,-6.232451,-4.125,-8.200,0.0,2.614267,98.92361,NaN,NaN,39.267257,2.795783,NaN,NaN,NaN,0.048070,0.996158,0.675154,-6.0,12
2018-12-29 00:10:00,11320,0.879624,-0.617260,0.577520,NaN,-5.268014,-0.455156,0.613190,-11.050,46.90142,0.660903,3.759500,0.332375,1.023354,0.542597,1.984889,1003.8350,-4.474945,-1.800,-7.296,0.1,1.723672,99.43750,NaN,NaN,47.482347,5.616233,NaN,NaN,NaN,0.034438,0.287595,0.291157,-4.0,12
2018-12-30 00:10:00,11321,0.476756,-0.901978,0.896532,NaN,-5.038892,-0.435360,1.807672,-11.050,58.87096,0.611986,3.728389,0.261771,0.933201,0.470632,1.911840,1009.3070,-3.461583,-1.738,-5.724,0.3,3.238451,99.72916,NaN,NaN,38.155978,2.973062,NaN,NaN,NaN,0.053743,1.064194,0.689735,-3.0,12
2018-12-31 22:10:00,11322,0.605755,-1.960404,0.422131,NaN,-4.760121,-0.411274,0.454753,-2.048,24.69542,0.509465,3.673660,0.231160,0.871861,0.429556,1.876417,1002.8510,1.882986,4.524,-1.915,1.9,1.215902,99.46528,NaN,13.0,67.885875,7.418705,4.387930,10.200,S,0.033737,0.112303,0.308713,1.0,12

We are now ready to group the dataframe by the value in the month column

In [37]:
weather.groupby(weather['month'])

Wait... What happened here? Well, when we perform a ``groupby`` operation on the month column, we create 12 new data frames (one for each month) and compute the mean for each data frame. The ``DataFrameGroupBy`` object is the container of these twelve data frames, one data frame for each of the unique values of the ``month`` column. The figure below demonstrate how the ``groupby`` operation work.
<img src="groupby.png" alt="drawing" width="800"/>

The usefulness of of the ``groupby`` operation becomes apparent once we use aggregation (also known as reduction) functions on it. Let us, for example, compute the mean of each row as a function of month.

In [37]:
weather.groupby(weather['month']).mean()

,Unnamed: 0,albedo,balanse,diffus,fd,fluxm,fluxs,global,grmin,ir_percentage,jt010,jt100,jt002,jt020,jt005,jt050,lp,lt,ltmax,ltmin,nb,par,rf,sd,sdman,visible_percentage,uv_percentage,vh,vhmax,uv_amount,ir_amount,visible_amount,lt_rounded,log_kelvin_lt
month,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,5494.129032,0.576290,-1.327403,0.807633,NaN,-3.197319,-0.275320,1.147371,-9.324145,50.737009,-0.103263,2.708579,-0.472967,0.242851,-0.422143,1.516468,998.426378,-2.648489,0.039490,-5.636071,2.652294,2.356126,88.667176,6.017857,8.927273,42.588789,6.663097,2.673763,5.430006,0.069039,0.613216,0.463400,-2.525806,5.599527
2,5520.422374,0.585779,-0.994159,2.023248,NaN,-2.586172,-0.222870,3.288178,-9.515172,51.067871,-0.303540,2.083003,-0.665687,-0.062679,-0.589772,1.224957,998.982206,-2.326450,0.898955,-5.746568,2.221637,7.096589,84.750212,3.998246,16.830000,42.810643,6.102609,2.726839,5.423426,0.183090,1.761076,1.344570,-2.206368,5.600741
3,5553.387097,0.473343,0.861134,3.825906,NaN,-0.160723,-0.013715,7.906774,-8.326237,51.012467,0.320577,1.873289,0.039998,0.347081,0.180215,1.271347,1000.416952,0.663428,4.751788,-3.503341,1.704707,17.323149,77.072037,4.187931,15.523810,43.560902,5.487687,2.762913,5.740201,0.397194,4.187327,3.310596,0.540366,5.611798
4,5583.887097,0.260724,4.605714,5.826006,NaN,4.560446,0.392995,12.185827,-3.878684,50.770781,4.011935,2.854604,4.240446,3.674601,4.248816,3.337575,1001.800937,5.274515,9.836783,0.632758,2.034570,26.856941,73.584072,0.086667,4.765789,44.014357,5.214600,2.820466,5.819732,0.589585,6.358593,5.238843,4.825556,5.628546
5,5614.387097,0.234172,7.965406,7.381541,2.841231,6.653774,0.574755,17.890620,0.319297,50.747468,10.094823,6.227333,10.492027,9.508806,10.332636,8.185120,1002.121939,10.849306,15.694901,5.470263,1.891663,39.828232,68.168495,0.096774,0.150000,44.162120,5.097060,2.916147,6.115052,0.873838,9.227209,7.837405,10.364516,5.648367
6,5644.887097,0.224904,9.164776,8.159775,3.387248,6.356127,0.548929,19.563571,4.734269,50.336732,14.417567,9.774996,14.860073,13.837226,14.635050,12.348497,1000.054751,14.569947,19.025925,9.413918,2.624761,44.391928,69.907581,0.000000,NaN,44.405287,5.224943,2.844272,5.890922,0.985658,9.949662,8.690347,14.094444,5.661419
7,5675.387097,0.218341,9.016934,7.935507,3.524832,4.533191,0.390244,18.375615,7.632463,49.818423,17.016289,12.529080,17.746668,16.438869,17.193734,15.101972,999.718365,16.826548,21.329823,11.719114,2.797679,42.118644,74.654198,0.000000,NaN,44.865845,5.318069,2.648819,5.609593,0.938762,9.259180,8.227459,16.358065,5.669246
8,5706.387097,0.225253,6.577065,6.342983,2.559505,0.210065,0.198356,14.223156,-10.249343,50.122659,16.323914,13.702338,16.794489,16.032941,16.315127,15.482797,1000.275075,15.636469,20.224859,10.696004,3.511639,32.780529,78.000755,0.000000,NaN,44.510271,5.347937,2.562693,5.458456,0.729857,7.176087,6.237385,15.138710,5.665130
9,5736.887097,0.235592,2.933991,4.097570,1.616527,-1.579586,-0.129463,8.968385,370.747622,50.695325,12.590957,12.628203,12.702697,12.640561,12.523064,13.039788,1001.538903,11.520368,15.805335,6.879758,3.024179,20.500809,80.480487,0.000000,NaN,43.880664,5.431517,2.641628,5.425961,0.457779,4.666077,3.866958,11.044444,5.650755
10,5767.387097,0.241506,0.190386,2.164501,0.989414,-4.405676,-0.379122,3.940239,79.309161,50.607849,7.556540,9.984979,7.385467,8.026256,7.324187,9.285327,1000.186887,6.132303,9.478480,2.505058,3.662703,8.807080,84.965400,0.000000,4.000000,43.640882,5.753758,2.625996,5.239594,0.203910,2.090324,1.644218,5.708602,5.631597
11,5797.887097,0.320631,-1.094317,0.944422,0.000000,-5.084117,-0.439323,1.411056,-4.299427,50.948877,3.168577,6.717228,2.956102,3.624933,2.870800,5.338126,998.492711,1.572713,4.084258,-1.360142,3.556695,3.012742,89.119761,1.289474,1.013953,42.900280,6.209988,2.713606,5.231757,0.076386,0.765346,0.562289,1.427778,5.615092
12,5828.387097,0.471917,-1.354443,0.544837,0.000000,-4.845287,-0.418902,0.730623,-8.556184,50.792585,0.698567,4.204406,0.317610,1.121059,0.345806,2.825331,998.340526,-2.069497,0.571923,-5.264557,2.665098,1.432716,89.966217,3.935484,8.621622,42.845689,6.393451,2.599228,5.499084,0.042002,0.399281,0.300864,-1.930108,5.601658

Here, we see the average value for each row dependent on which month it was. We can use any of the builtin dataframe aggregation functions. Let us, for example compute the standard deviation for each column as a function of month.

In [38]:
grouped = weather.groupby(weather['month'])
grouped.std()

,Unnamed: 0,albedo,balanse,diffus,fd,fluxm,fluxs,global,grmin,ir_percentage,jt010,jt100,jt002,jt020,jt005,jt050,lp,lt,ltmax,ltmin,nb,par,rf,sd,sdman,visible_percentage,uv_percentage,vh,vhmax,uv_amount,ir_amount,visible_amount,lt_rounded
month,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,3268.623077,0.357090,1.457970,0.390413,NaN,8.853264,0.763132,0.719693,7.765757,9.833814,0.876397,0.642133,1.215784,0.951418,1.081687,0.815314,15.239205,5.331491,4.867803,6.206099,5.110708,1.437378,10.893147,9.178019,12.486148,9.074743,1.696557,1.711918,2.990230,0.034839,0.440983,0.280109,5.007194
2,3269.702803,0.259479,1.306435,0.896610,NaN,8.731549,0.754414,1.869183,7.679120,7.551283,0.975153,0.462950,1.309450,0.798290,1.177332,0.729292,15.611154,5.006977,4.589365,6.117056,4.450950,3.810084,12.292707,3.569538,11.958865,6.749305,1.239096,1.572620,2.676177,0.081296,1.125755,0.722406,4.669336
3,3268.594209,0.248220,2.007351,1.581578,NaN,8.343175,0.720941,3.843804,7.036987,5.859919,1.357848,0.559231,1.379279,1.231371,1.416349,0.922060,13.635463,3.885646,4.257704,5.009401,4.336080,8.024195,15.188312,5.462892,16.936435,5.001552,1.071112,1.438992,2.514848,0.152755,2.241925,1.511670,3.525880
4,3268.650178,0.117344,2.704386,2.245359,NaN,8.560861,0.738511,5.651297,4.760625,4.520834,2.658770,1.230606,2.857821,2.497941,2.708941,2.019117,17.191448,3.108770,4.249569,3.397870,4.988929,12.052793,16.036285,0.292119,8.686625,3.892122,0.940294,1.217904,1.962987,0.220363,3.171727,2.336697,3.049756
5,3268.594209,0.021157,3.613746,2.678072,1.533218,8.516523,0.736004,6.739305,5.139026,3.303280,2.186833,1.545422,2.392623,2.106427,2.241017,1.987769,8.501936,3.522505,4.558055,3.434376,4.466313,14.848902,14.982025,0.538816,0.670820,2.857778,0.750254,1.069634,1.780479,0.276342,3.645378,2.866184,3.518891
6,3268.650178,0.028739,4.255960,2.732736,1.673683,7.845911,0.677778,7.255854,4.207247,2.672951,1.635363,1.180561,1.848416,1.557177,1.767498,1.374143,7.251841,2.812113,3.758450,2.747146,5.865509,16.247509,14.472025,0.000000,NaN,2.413972,0.705182,1.000597,1.580035,0.298321,3.838824,3.177947,2.816401
7,3268.594209,0.017266,3.861757,2.439160,1.793838,10.986257,0.947072,6.565942,3.831283,2.461820,1.308394,0.863541,1.489320,1.199103,1.458339,0.995692,7.683739,2.490782,3.531819,2.583065,6.843135,14.822625,11.842028,0.000000,NaN,2.222705,0.669280,0.972321,1.633833,0.274670,3.409273,2.924868,2.520052
8,3268.594209,0.020629,3.231382,2.078141,1.287987,55.887692,0.747037,5.337301,336.271307,2.946597,1.633487,0.788695,1.754199,1.497990,1.715655,1.145258,7.283660,2.507855,3.219328,3.089441,7.456279,12.081557,10.470591,0.000000,NaN,2.624312,0.679518,0.985620,1.545688,0.228589,2.816008,2.298877,2.502336
9,3268.650178,0.032065,2.491768,1.705014,1.048099,9.095359,0.764330,4.161281,1564.173849,4.110238,1.990240,1.051848,2.138075,1.920579,2.150489,2.391639,10.540666,2.828776,3.090207,4.009205,6.809080,9.411879,10.684638,0.000000,NaN,3.600993,0.846674,1.292110,2.036921,0.179114,2.288589,1.727141,2.828864
10,3268.594209,0.077053,1.905481,1.093445,0.853369,10.392227,0.906038,2.517572,747.922517,5.816663,2.547081,1.411179,2.756020,2.303261,2.712890,1.965713,12.569908,3.723546,3.642959,4.554070,7.181124,5.524074,11.999199,0.000000,5.656854,5.080465,1.079799,1.447386,2.242523,0.106307,1.437035,1.003424,3.601822
11,3268.650178,0.199042,1.321548,0.501449,0.000000,9.171087,0.792380,0.998859,6.268862,8.196274,2.257919,1.394528,2.452851,2.200382,2.449862,1.922632,12.132290,4.321419,4.210819,4.822428,7.272729,2.085752,10.744851,1.829309,2.115991,7.524624,1.480176,1.587464,2.625522,0.042481,0.613747,0.364654,3.965410
12,3268.594209,0.281917,1.563647,0.257282,0.000000,8.517558,0.735770,0.419100,7.356069,11.995787,1.423687,1.066522,1.675565,1.364527,1.619347,1.461145,15.492229,5.450340,5.052632,6.062478,6.219457,0.769531,10.291803,2.743908,6.997426,11.215149,1.632008,1.673800,3.354652,0.016201,0.264894,0.178081,5.114665

We can also use the builtin numpy reduction functions on a ``DataFrameGroupBy`` object. Let us demonstrate by taking the sum of each column as a function of month.

In [39]:
np.sum(grouped)

,Unnamed: 0,albedo,balanse,diffus,fd,fluxm,fluxs,global,grmin,ir_percentage,jt010,jt100,jt002,jt020,jt005,jt050,lp,lt,ltmax,ltmin,nb,par,rf,sd,sdman,visible_percentage,uv_percentage,vh,vhmax,uv_amount,ir_amount,visible_amount,lt_rounded
month,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,5279858,503.677481,-1173.423831,745.445614,0.000000,-2350.029396,-203.461576,1059.023354,-4046.679001,46525.837486,-92.007676,2418.761052,-350.468576,216.866387,-350.801172,1301.129412,771783.590129,-2463.094660,37.870998,-5404.992003,2127.139990,2174.704004,81396.467717,337.0,392.8,38926.153009,6116.723246,2272.698499,4572.064999,63.378212,562.319483,423.547977,-2349.0
2,4835890,465.108253,-823.163647,1663.109557,0.000000,-1776.700164,-153.111926,2709.458538,-3758.492999,41875.654490,-251.634953,1733.058724,-469.975184,-52.148564,-457.663130,948.116976,705281.437097,-1972.829282,787.485000,-5033.993996,1628.460000,5833.396537,69834.175026,227.9,673.2,34719.431446,4973.626558,2162.383266,4289.929997,149.218149,1444.081916,1090.446327,-1871.0
3,5336805,417.488877,787.076919,3485.400487,0.000000,-122.792744,-10.478574,7226.791430,-3613.587001,46472.357311,273.131844,1712.185765,30.998296,317.231724,153.543471,1083.187783,775323.137731,616.324177,4561.716001,-3363.207002,1452.409999,15816.034679,69056.545160,242.9,652.0,39161.250627,4944.405571,2431.363227,5062.857001,357.872026,3814.655246,2976.225683,502.0
4,5193015,219.790004,3997.760177,5091.929344,0.000000,3219.674950,277.454142,10650.412860,-1609.654000,44322.891502,3185.476188,2420.704047,3057.361337,3071.966339,3420.296823,2653.372022,730312.883073,4747.063460,9148.207994,588.465000,1633.759992,23446.109228,64459.647093,2.6,181.1,38292.490164,4536.702365,2380.473675,4923.492997,512.938999,5551.051667,4557.793177,4343.0
5,5395426,220.355887,7551.204828,6886.977876,528.468981,5156.674522,445.435050,17067.651824,138.575000,48362.337049,9519.418022,5947.103291,7942.464809,8966.804118,9588.686045,7563.051259,776644.503110,10089.854562,15082.799997,5256.923005,1753.571982,37000.427744,65100.912323,3.0,3.0,40849.960735,4719.877871,2615.783883,5491.317002,809.173684,8793.529747,7249.599796,9639.0
6,5249745,202.638595,8284.957228,7180.602065,1188.923976,4741.670696,409.500834,17607.214236,1988.393000,45353.395671,13033.480699,8846.371542,11115.334507,12093.735159,13230.085026,10804.934847,750041.063333,13112.952259,17694.110001,8754.943998,2357.034979,38221.450418,62287.654482,0.0,0.0,37566.872548,4420.302161,2517.180535,5166.339001,833.866421,8944.745803,7352.033839,12685.0
7,5454047,202.839234,8340.664176,7268.924064,1491.003988,3495.090407,300.878129,17070.946613,3312.489000,44936.217381,15791.115940,11626.986027,13753.667942,14745.665738,15852.622842,13546.468672,774781.732908,15648.689695,20497.960000,11262.068996,2613.031987,39001.864333,67188.778223,0.0,0.0,40468.992257,4940.486054,2436.913747,5177.653999,872.110336,8351.780364,7421.167635,15213.0
8,5483838,204.754897,5899.627382,5727.713907,1008.444996,154.187863,145.196737,12943.071832,-4448.214998,44007.694977,14642.550693,12085.461723,12310.360701,14269.317494,13851.543019,13779.689163,762209.606883,14541.916232,19436.089978,10278.859991,3192.080008,29797.500428,69810.675662,0.0,0.0,39080.017942,4861.274333,2291.047575,4928.986001,663.440057,6300.604536,5476.423687,14079.0
9,5335305,214.153448,2666.998170,3618.154465,619.129993,-1178.370828,-96.449746,8152.262008,154972.506000,44054.237711,11445.180260,11466.408060,9476.212029,11199.536800,10657.127099,11814.047503,719104.932229,10368.330831,14698.961974,6398.174996,2670.349997,18635.235467,73156.763033,0.0,0.0,38132.296864,4937.248517,2308.783092,4769.420001,416.121525,4054.820853,3360.386266,9940.0
10,5542459,221.219538,180.295143,2049.782769,150.391004,-3405.587493,-281.308706,3731.406501,34420.176002,44281.867540,6702.650816,9096.316323,5524.329414,6637.713407,6262.179828,8403.221266,742138.669798,5703.042205,8814.986001,2329.704002,3157.249989,8084.899056,80207.337754,0.0,8.0,38185.771757,5281.949889,2376.526295,4589.884000,187.189340,1829.033287,1438.690715,5309.0
11,5392035,279.590527,-931.263472,854.701591,0.000000,-3813.087851,-329.492387,1285.471626,-1801.460001,42746.108134,2839.045055,6105.960556,2172.735179,3222.565601,2486.112781,4852.356302,748869.533088,1415.441446,3798.359999,-1264.932000,2927.160010,2672.302471,79851.306044,49.0,43.6,35392.730898,5539.309400,2355.409912,4541.165000,68.136698,642.125653,463.888386,1285.0
12,5601080,413.871092,-1213.580737,514.326337,0.000000,-3682.418259,-318.365706,691.169085,-3713.384002,44037.171009,662.940266,3989.981677,246.147544,1063.885348,317.449678,2681.238747,773713.907378,-1924.632375,549.618002,-5059.238998,2038.799995,1358.215208,84298.345743,122.0,319.0,37018.674934,5786.072782,2266.526860,4740.210004,38.011358,346.176674,259.946128,-1795.0

## Statistical analysis in Python

Let us now perform two simple statistical tests, one-way ANOVA and multi-way ANOVA. 

### ANOVA
We start by performing an ANOVA to test whether the month variable is statistically significant.

In [40]:
from statsmodels.formula.api import ols

Then we create a linear model, where air temperature (``lt``) is dependent on the categorical variable ``month`` (the ``C(month)`` term ensures that month is regarded as a categorical variable). We then fit the model and view its summary. To do this, we use the Patsy modelling language to design the model and let statsmodels create the appropriate statistical model.

In [45]:
model = ols('lt ~ 0 + C(month, Treatment)', data=weather).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                     lt   R-squared:                       0.767
Model:                            OLS   Adj. R-squared:                  0.767
Method:                 Least Squares   F-statistic:                     3272.
Date:                Thu, 20 Jun 2019   Prob (F-statistic):               0.00
Time:                        23:51:40   Log-Likelihood:                -30406.
No. Observations:               10957   AIC:                         6.084e+04
Df Residuals:                   10945   BIC:                         6.092e+04
Df Model:                          11
Covariance Type:            nonrobust
===========================================================================================
                              coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------
C(month, Treatment)[1]     -2.6485      0.127    -20.799      0.000      -2.898      -2.399
C(month, Treatment)[2]     -2.3264      0.133    -17.446      0.000      -2.588      -2.065
C(month, Treatment)[3]      0.6634      0.127      5.207      0.000       0.414       0.913
C(month, Treatment)[4]      5.2745      0.129     40.749      0.000       5.021       5.528
C(month, Treatment)[5]     10.8493      0.127     85.203      0.000      10.600      11.099
C(month, Treatment)[6]     14.5699      0.129    112.561      0.000      14.316      14.824
C(month, Treatment)[7]     16.8265      0.127    132.144      0.000      16.577      17.076
C(month, Treatment)[8]     15.6365      0.127    122.798      0.000      15.387      15.886
C(month, Treatment)[9]     11.5204      0.129     89.001      0.000      11.267      11.774
C(month, Treatment)[10]     6.1323      0.127     48.159      0.000       5.883       6.382
C(month, Treatment)[11]     1.5727      0.129     12.150      0.000       1.319       1.826
C(month, Treatment)[12]    -2.0695      0.127    -16.252      0.000      -2.319      -1.820
==============================================================================
Omnibus:                      522.087   Durbin-Watson:                   0.397
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              747.836
Skew:                          -0.447   Prob(JB):                    4.07e-163
Kurtosis:                       3.916   Cond. No.                         1.05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

Here we use Patsy to describe the statistical model of interest. The ``0 + `` part ensures that the average temperature is regarded as the baseline temperature.

### One-way ANOVA
Let us now create a standard ANOVA table to assess whether or not there is a statistically significant difference between the different month variables.

In [46]:
from statsmodels.stats.anova import anova_lm

In [47]:
anova_lm(model)

                          df         sum_sq       mean_sq            F  PR(>F)
C(month, Treatment)     12.0  988409.973068  82367.497756  5462.297311     0.0
Residual             10945.0  165042.693857     15.079278          NaN     NaN

Notice how the ANOVA model automatically ignores missing values (i.e. NAN values). Let us perform a multi-way ANOVA test, where we control for weekday and month. To do this, we first create a weekday column.

In [48]:
weather['weekday'] = weather.index.day

### Multi-way ANOVA
Now, we can easily perform a multi-way ANOVA test.

In [49]:
multi_way_model = ols('lt ~ 0 + C(month) + C(weekday) + C(weekday)*C(month)', data=weather).fit()
anova_lm(multi_way_model, typ=3)

C:\NMBU\Miniconda3\lib\site-packages\statsmodels\base\model.py:1532: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 330, but rank is 324
  'rank is %d' % (J, J_), ValueWarning)

                            sum_sq       df           F        PR(>F)
C(month)              32682.375356     12.0  193.924774  0.000000e+00
C(weekday)              540.383575     30.0    1.282572  1.383369e-01
C(weekday):C(month)   16038.468116    330.0    3.460588  2.492619e-82
Residual             148742.830096  10591.0         NaN           NaN

Thus, we see that there is an influence of month on the temperature, but not an influence on weekday on the air temperature (as expected). Weirly enough, there is a statistically significant influence on the interaction of weekday and month, which probably means that our data does not satisfy the ANOVA constraints. This is clear, since daily temperatures are not IID.